# Aula Prática 2 — Deep Learning (P1-10)

**Dataset:** Malaria Cell Images (NIH, ~27.5k imagens, 2 classes)  
**Objetivo:** Caracterização, divisão sem fugas, baseline CNN, curvas e diagnóstico.  
**Seed:** 42 em tudo  
**NOTA:** O conjunto de teste **NÃO** é avaliado nesta aula.

In [1]:
# ─── Imports e configuração global ───────────────────────────────────────
import os, re, hashlib, shutil, pathlib, warnings, time
import numpy as np
import pandas as pd
from PIL import Image
from collections import Counter
import matplotlib
matplotlib.use('Agg')  # backend não-interativo para garantir que funciona headless
import matplotlib.pyplot as plt

# Seed global
SEED = 42
np.random.seed(SEED)

# Keras 3 + PyTorch backend
os.environ['KERAS_BACKEND'] = 'torch'
import torch
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

import keras
keras.utils.set_random_seed(SEED)

# Caminhos
ROOT = pathlib.Path(os.path.abspath(os.path.join(os.getcwd(), '..')))
DATA_RAW = ROOT / 'data' / 'raw'
AULA2 = ROOT / 'aula2'
SPLITS_D1 = ROOT / 'splits'

# Verificação
print(f'ROOT:     {ROOT}')
print(f'DATA_RAW: {DATA_RAW} (existe: {DATA_RAW.exists()})')
print(f'Keras:    {keras.__version__}')
print(f'PyTorch:  {torch.__version__}')
print(f'GPU:      {torch.cuda.get_device_name(0) if torch.cuda.is_available() else "Sem GPU"}')

ROOT:     C:\Users\vilar\Desktop\Mestrado\deeeplearning
DATA_RAW: C:\Users\vilar\Desktop\Mestrado\deeeplearning\data\raw (existe: True)
Keras:    3.15.1
PyTorch:  2.11.0+cu128
GPU:      NVIDIA GeForce RTX 5060 Laptop GPU

---
## 2.1 — Caracterização do Dataset

In [2]:
# ─── 2.1a  Listar todas as imagens ──────────────────────────────────────
# Percorre cell_images/ dentro de data/raw/ e recolhe jpg/jpeg/png

IMG_DIR = DATA_RAW / 'cell_images'
VALID_EXT = {'.jpg', '.jpeg', '.png'}

records = []
for class_dir in sorted(IMG_DIR.iterdir()):
    if not class_dir.is_dir():
        continue
    # Ignorar a pasta cell_images/cell_images (aninhada do zip)
    if class_dir.name == 'cell_images':
        continue
    label = class_dir.name
    for f in sorted(class_dir.iterdir()):
        if f.suffix.lower() in VALID_EXT:
            records.append({'path': str(f), 'label': label, 'filename': f.name})

df = pd.DataFrame(records)
print(f'Total de imagens encontradas: {len(df)}')
df.head()

Total de imagens encontradas: 27558

,path,label,filename
0,C:\Users\vilar\Desktop\Mestrado\deeeplearning\...,Parasitized,C100P61ThinF_IMG_20150918_144104_cell_162.png
1,C:\Users\vilar\Desktop\Mestrado\deeeplearning\...,Parasitized,C100P61ThinF_IMG_20150918_144104_cell_163.png
2,C:\Users\vilar\Desktop\Mestrado\deeeplearning\...,Parasitized,C100P61ThinF_IMG_20150918_144104_cell_164.png
3,C:\Users\vilar\Desktop\Mestrado\deeeplearning\...,Parasitized,C100P61ThinF_IMG_20150918_144104_cell_165.png
4,C:\Users\vilar\Desktop\Mestrado\deeeplearning\...,Parasitized,C100P61ThinF_IMG_20150918_144104_cell_166.png

In [3]:
# ─── 2.1b  Extrair ID de doente (grupo) com a regex do D1 ──────────────
# Regex: ^(C\d+(?:P\d+)?)  — extrai o código do paciente/lâmina

GROUP_REGEX = r'^(C\d+(?:P\d+)?)'

def extract_group(filename):
    m = re.match(GROUP_REGEX, filename)
    return m.group(1) if m else 'UNKNOWN'

df['grupo'] = df['filename'].apply(extract_group)

n_unknown = (df['grupo'] == 'UNKNOWN').sum()
print(f'Imagens sem grupo identificado: {n_unknown}')
print(f'Grupos únicos: {df["grupo"].nunique()}')
df[['filename', 'label', 'grupo']].head(10)

Imagens sem grupo identificado: 0
Grupos únicos: 200

                                        filename        label    grupo
0  C100P61ThinF_IMG_20150918_144104_cell_162.png  Parasitized  C100P61
1  C100P61ThinF_IMG_20150918_144104_cell_163.png  Parasitized  C100P61
2  C100P61ThinF_IMG_20150918_144104_cell_164.png  Parasitized  C100P61
3  C100P61ThinF_IMG_20150918_144104_cell_165.png  Parasitized  C100P61
4  C100P61ThinF_IMG_20150918_144104_cell_166.png  Parasitized  C100P61
5  C100P61ThinF_IMG_20150918_144104_cell_167.png  Parasitized  C100P61
6  C100P61ThinF_IMG_20150918_144104_cell_168.png  Parasitized  C100P61
7  C100P61ThinF_IMG_20150918_144104_cell_169.png  Parasitized  C100P61
8  C100P61ThinF_IMG_20150918_144104_cell_170.png  Parasitized  C100P61
9  C100P61ThinF_IMG_20150918_144104_cell_171.png  Parasitized  C100P61

In [4]:
# ─── 2.1c  Value counts por classe ─────────────────────────────────────
vc_abs = df['label'].value_counts()
vc_pct = df['label'].value_counts(normalize=True) * 100

dist_df = pd.DataFrame({'N.º imagens': vc_abs, '% do total': vc_pct.round(2)})
dist_df.index.name = 'Classe'
print('=== Distribuição por classe ===')
display(dist_df)
print(f'\nTotal: {len(df)} imagens')

=== Distribuição por classe ===

             N.º imagens  % do total
Classe
Parasitized        13779        50.0
Uninfected         13779        50.0

Total: 27558 imagens

In [5]:
# ─── 2.1d  Dimensão típica por classe + deteção de imagens corrompidas ─
widths, heights, corrupted_paths = [], [], []

for idx, row in df.iterrows():
    try:
        with Image.open(row['path']) as img:
            img.verify()  # Verifica integridade
        # Re-open para obter dimensões (verify() invalida o objeto)
        with Image.open(row['path']) as img:
            w, h = img.size
            widths.append(w)
            heights.append(h)
    except Exception as e:
        corrupted_paths.append((row['path'], str(e)))
        widths.append(None)
        heights.append(None)

df['width'] = widths
df['height'] = heights

print(f'Imagens corrompidas: {len(corrupted_paths)}')
if corrupted_paths:
    for p, e in corrupted_paths:
        print(f'  {p}: {e}')

# Dimensão típica por classe (mediana, min, max)
dim_stats = df.dropna(subset=['width', 'height']).groupby('label').agg(
    mediana_w=('width', 'median'),
    mediana_h=('height', 'median'),
    min_w=('width', 'min'),
    max_w=('width', 'max'),
    min_h=('height', 'min'),
    max_h=('height', 'max'),
).astype(int)

dim_stats['Dimensão típica'] = dim_stats.apply(
    lambda r: f"{r['mediana_w']}×{r['mediana_h']}", axis=1
)
dim_stats['Intervalo'] = dim_stats.apply(
    lambda r: f"({r['min_w']}–{r['max_w']}) × ({r['min_h']}–{r['max_h']})", axis=1
)

print('\n=== Dimensões por classe ===')
display(dim_stats[['Dimensão típica', 'Intervalo']])

Imagens corrompidas: 0

=== Dimensões por classe ===

            Dimensão típica            Intervalo
label
Parasitized         133×133  (46–394) × (40–385)
Uninfected          130×130  (49–247) × (49–235)

In [6]:
# ─── 2.1e  Deteção de duplicados por MD5 ───────────────────────────────

def file_md5(filepath):
    h = hashlib.md5()
    with open(filepath, 'rb') as f:
        for chunk in iter(lambda: f.read(8192), b''):
            h.update(chunk)
    return h.hexdigest()

print('A calcular MD5 de todas as imagens...')
df['md5'] = df['path'].apply(file_md5)

# Duplicados: mesmo md5
dup_mask = df.duplicated(subset='md5', keep=False)
n_dup_groups = df[dup_mask]['md5'].nunique()
n_dup_total = dup_mask.sum()

print(f'\nImagens com hash duplicado: {n_dup_total} (em {n_dup_groups} grupos de duplicados)')

if n_dup_total > 0:
    # Mostrar alguns exemplos
    dup_examples = df[dup_mask].sort_values('md5').head(10)
    display(dup_examples[['filename', 'label', 'grupo', 'md5']])
    
    # Duplicados entre classes?
    cross_class = df[dup_mask].groupby('md5')['label'].nunique()
    cross_class_dup = (cross_class > 1).sum()
    print(f'Duplicados entre classes diferentes: {cross_class_dup}')

A calcular MD5 de todas as imagens...

Imagens com hash duplicado: 0 (em 0 grupos de duplicados)

In [7]:
# ─── 2.1f  Tabela final de caracterização ──────────────────────────────

# Construir observações com base nos dados encontrados
def build_obs(label):
    obs_parts = []
    
    # Corrompidas nesta classe?
    n_corr = len([p for p, _ in corrupted_paths if label in p])
    if n_corr > 0:
        obs_parts.append(f'{n_corr} imagem(ns) corrompida(s)')
    
    # Duplicados nesta classe
    class_dups = df[(df['label'] == label) & dup_mask]
    if len(class_dups) > 0:
        obs_parts.append(f'{len(class_dups)} imgs com hash duplicado')
    
    # Variação de dimensão
    sub = df[df['label'] == label].dropna(subset=['width'])
    w_range = sub['width'].max() - sub['width'].min()
    h_range = sub['height'].max() - sub['height'].min()
    if w_range > 100 or h_range > 100:
        obs_parts.append(f'dimensões variáveis (range {w_range}×{h_range})')
    else:
        obs_parts.append('dimensões relativamente homogéneas')
    
    # Imagens sem grupo
    n_unk = ((df['label'] == label) & (df['grupo'] == 'UNKNOWN')).sum()
    if n_unk > 0:
        obs_parts.append(f'{n_unk} sem ID de doente')
    
    if not obs_parts:
        obs_parts.append('sem problemas detetados')
    
    return '; '.join(obs_parts)

summary_rows = []
for label in sorted(df['label'].unique()):
    sub = df[df['label'] == label]
    sub_clean = sub.dropna(subset=['width'])
    summary_rows.append({
        'Classe': label,
        'N.º imagens': len(sub),
        '%': f"{len(sub)/len(df)*100:.1f}%",
        'Dimensão típica': f"{int(sub_clean['width'].median())}×{int(sub_clean['height'].median())}",
        'Observações': build_obs(label),
    })

summary_table = pd.DataFrame(summary_rows)
print('=== Tabela 2.1 — Caracterização do Dataset ===')
display(summary_table)

# Guardar para uso posterior
summary_table.to_csv(AULA2 / 'tabela_21_caracterizacao.csv', index=False)
print(f'\nTabela guardada em aula2/tabela_21_caracterizacao.csv')

=== Tabela 2.1 — Caracterização do Dataset ===

,Classe,N.º imagens,%,Dimensão típica,Observações
0,Parasitized,13779,50.0%,133×133,dimensões variáveis (range 348×345)
1,Uninfected,13779,50.0%,130×130,dimensões variáveis (range 198×186)

Tabela guardada em aula2/tabela_21_caracterizacao.csv

---
## 2.2 — Divisão sem fugas (Group-Aware Split)

### Escolha de abordagem

**Decisão:** Reaproveitar a divisão do D1 (`splits/train.csv`, `val.csv`, `test.csv`).

**Justificação:**
- A divisão do D1 já foi feita com `GroupShuffleSplit` (seed 42), respeitando a integridade de grupos (doentes).
- Reaproveitar garante consistência entre aulas e evita resultados incomparáveis.
- Vamos validar que a divisão cumpre todos os requisitos (sem fugas de grupo, sem fugas por md5, estratificação).

In [8]:
# ─── 2.2a  Carregar splits do D1 e construir splits.csv ────────────────

train_d1 = pd.read_csv(SPLITS_D1 / 'train.csv')
val_d1   = pd.read_csv(SPLITS_D1 / 'val.csv')
test_d1  = pd.read_csv(SPLITS_D1 / 'test.csv')

train_d1['split'] = 'train'
val_d1['split']   = 'val'
test_d1['split']  = 'test'

splits_d1 = pd.concat([train_d1, val_d1, test_d1], ignore_index=True)
splits_d1.rename(columns={'relative_path': 'rel_path', 'class': 'label', 'id_grupo': 'grupo'}, inplace=True)

# Construir path absoluto para fazer join com o nosso df
splits_d1['path'] = splits_d1['rel_path'].apply(lambda p: str(DATA_RAW / p))

print(f'Total D1 splits: {len(splits_d1)}')
print(f'Total nosso df:  {len(df)}')

# Join com md5 do nosso df
splits_merged = splits_d1.merge(df[['path', 'md5']], on='path', how='left')

# Verificar se há NaN no md5 (imagens no D1 que não encontrámos)
n_missing = splits_merged['md5'].isna().sum()
print(f'Imagens no D1 sem correspondência no nosso scan: {n_missing}')

# Guardar splits.csv
splits_final = splits_merged[['path', 'label', 'grupo', 'md5', 'split']].copy()
splits_final.to_csv(AULA2 / 'splits.csv', index=False)
print(f'\nGuardado aula2/splits.csv com {len(splits_final)} linhas')
splits_final.head()

Total D1 splits: 27558
Total nosso df:  27558
Imagens no D1 sem correspondência no nosso scan: 0

Guardado aula2/splits.csv com 27558 linhas

,path,label,grupo,md5,split
0,C:\Users\vilar\Desktop\Mestrado\deeeplearning\...,Parasitized,C100P61,6b60535df837d603b2f591d154940f1a,train
1,C:\Users\vilar\Desktop\Mestrado\deeeplearning\...,Parasitized,C100P61,142cdfcc8f5d2afcdd327e4886a4fbf8,train
2,C:\Users\vilar\Desktop\Mestrado\deeeplearning\...,Parasitized,C100P61,2db29c733097f1736cdba4055e1549d6,train
3,C:\Users\vilar\Desktop\Mestrado\deeeplearning\...,Parasitized,C100P61,2fafd2198f16e9d264cd0426f164e5a6,train
4,C:\Users\vilar\Desktop\Mestrado\deeeplearning\...,Parasitized,C100P61,6da8225a1d75edded5ecb514e63f1c92,train

In [9]:
# ─── 2.2b  Verificações de integridade ─────────────────────────────────

train_s = splits_final[splits_final['split'] == 'train']
val_s   = splits_final[splits_final['split'] == 'val']
test_s  = splits_final[splits_final['split'] == 'test']

print('=== Verificação 1: Interseção de MD5 entre splits ===')
md5_train = set(train_s['md5'].dropna())
md5_val   = set(val_s['md5'].dropna())
md5_test  = set(test_s['md5'].dropna())

inter_tv = md5_train & md5_val
inter_tt = md5_train & md5_test
inter_vt = md5_val & md5_test

print(f'  train ∩ val  (md5): {len(inter_tv)}')
print(f'  train ∩ test (md5): {len(inter_tt)}')
print(f'  val   ∩ test (md5): {len(inter_vt)}')

if len(inter_tv) + len(inter_tt) + len(inter_vt) == 0:
    print('  ✅ Sem fugas por MD5!')
else:
    print('  ⚠️ AVISO: Existem hashes duplicados entre splits!')
    if inter_tv:
        print(f'    MD5s em train∩val: {list(inter_tv)[:5]}')
    if inter_tt:
        print(f'    MD5s em train∩test: {list(inter_tt)[:5]}')
    if inter_vt:
        print(f'    MD5s em val∩test: {list(inter_vt)[:5]}')

=== Verificação 1: Interseção de MD5 entre splits ===
  train ∩ val  (md5): 0
  train ∩ test (md5): 0
  val   ∩ test (md5): 0
  ✅ Sem fugas por MD5!

In [10]:
# ─── 2.2c  Verificação de interseção de GRUPOS ─────────────────────────

print('=== Verificação 2: Interseção de GRUPOS entre splits ===')
grp_train = set(train_s['grupo'])
grp_val   = set(val_s['grupo'])
grp_test  = set(test_s['grupo'])

inter_g_tv = grp_train & grp_val
inter_g_tt = grp_train & grp_test
inter_g_vt = grp_val & grp_test

print(f'  train ∩ val  (grupo): {len(inter_g_tv)}')
print(f'  train ∩ test (grupo): {len(inter_g_tt)}')
print(f'  val   ∩ test (grupo): {len(inter_g_vt)}')

if len(inter_g_tv) + len(inter_g_tt) + len(inter_g_vt) == 0:
    print('  ✅ Sem fugas de grupo!')
else:
    print('  ⚠️ AVISO: Existem grupos partilhados entre splits!')
    if inter_g_tv:
        print(f'    Grupos em train∩val: {sorted(inter_g_tv)[:10]}')
    if inter_g_tt:
        print(f'    Grupos em train∩test: {sorted(inter_g_tt)[:10]}')
    if inter_g_vt:
        print(f'    Grupos em val∩test: {sorted(inter_g_vt)[:10]}')

=== Verificação 2: Interseção de GRUPOS entre splits ===
  train ∩ val  (grupo): 0
  train ∩ test (grupo): 0
  val   ∩ test (grupo): 0
  ✅ Sem fugas de grupo!

In [11]:
# ─── 2.2d  Distribuição por classe em cada split ───────────────────────

print('=== Verificação 3: Distribuição por classe em cada split ===')
for split_name in ['train', 'val', 'test']:
    sub = splits_final[splits_final['split'] == split_name]
    pct = sub['label'].value_counts(normalize=True) * 100
    print(f'\n{split_name.upper()} ({len(sub)} imagens):')
    for cls in sorted(pct.index):
        print(f'  {cls}: {pct[cls]:.1f}%')

# Verificar desvio máximo
all_pcts = {}
for split_name in ['train', 'val', 'test']:
    sub = splits_final[splits_final['split'] == split_name]
    pct = sub['label'].value_counts(normalize=True) * 100
    all_pcts[split_name] = pct

pct_df = pd.DataFrame(all_pcts).T
max_diff = pct_df.max() - pct_df.min()
print(f'\nDesvio máximo entre splits por classe:')
for cls in max_diff.index:
    diff = max_diff[cls]
    status = '✅' if diff < 2.0 else '⚠️'
    print(f'  {cls}: {diff:.2f} pp {status}')

display(pct_df.round(2))

=== Verificação 3: Distribuição por classe em cada split ===

TRAIN (19380 imagens):
  Parasitized: 50.1%
  Uninfected: 49.9%

VAL (4107 imagens):
  Parasitized: 50.0%
  Uninfected: 50.0%

TEST (4071 imagens):
  Parasitized: 49.4%
  Uninfected: 50.6%

Desvio máximo entre splits por classe:
  Parasitized: 0.75 pp ✅
  Uninfected: 0.75 pp ✅

label  Parasitized  Uninfected
train        50.12       49.88
val          50.04       49.96
test         49.37       50.63

---
## 2.3 — Baseline CNN

In [12]:
# ─── 2.3a  Criar estrutura de pastas com cópias/symlinks ───────────────
SPLIT_DIR = AULA2 / 'split'

# Limpar se já existe
if SPLIT_DIR.exists():
    shutil.rmtree(SPLIT_DIR)

created_count = {'train': 0, 'val': 0, 'test': 0}

for _, row in splits_final.iterrows():
    src = pathlib.Path(row['path'])
    dst_dir = SPLIT_DIR / row['split'] / row['label']
    dst_dir.mkdir(parents=True, exist_ok=True)
    dst = dst_dir / src.name
    
    if not dst.exists():
        try:
            # Tentar symlink primeiro
            os.symlink(src, dst)
        except OSError:
            # Fallback para cópia no Windows sem permissões de symlink
            shutil.copy2(src, dst)
        created_count[row['split']] += 1

print('Ficheiros criados por split:')
for k, v in created_count.items():
    print(f'  {k}: {v}')

# Adicionar aula2/split/ ao .gitignore
gitignore_path = ROOT / '.gitignore'
gitignore_entry = 'aula2/split/'
with open(gitignore_path, 'r') as f:
    content = f.read()
if gitignore_entry not in content:
    with open(gitignore_path, 'a') as f:
        f.write(f'\n# Aula 2 — pastas de imagens (cópias/symlinks)\n{gitignore_entry}\n')
    print(f'\nAdicionado "{gitignore_entry}" ao .gitignore')
else:
    print(f'\n"{gitignore_entry}" já está no .gitignore')

Ficheiros criados por split:
  train: 19380
  val: 4107
  test: 4071

"aula2/split/" já está no .gitignore

In [13]:
# ─── 2.3b  Carregar datasets com Keras ─────────────────────────────────
IMG_SIZE = (180, 180)
BATCH_SIZE = 32

train_ds = keras.utils.image_dataset_from_directory(
    str(SPLIT_DIR / 'train'),
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='int',
    shuffle=True,
    seed=SEED,
)

val_ds = keras.utils.image_dataset_from_directory(
    str(SPLIT_DIR / 'val'),
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='int',
    shuffle=False,
)

class_names = train_ds.class_names
num_classes = len(class_names)
print(f'Classes: {class_names}')
print(f'Número de classes: {num_classes}')

Found 19380 files belonging to 2 classes.

Found 4107 files belonging to 2 classes.

Classes: ['Parasitized', 'Uninfected']
Número de classes: 2

In [14]:
# ─── 2.3c  Definir a CNN baseline (arquitetura exata do enunciado) ─────
from keras import layers, models

def build_baseline_cnn(num_classes, input_shape=(180, 180, 3)):
    inputs = keras.Input(shape=input_shape)
    x = layers.Rescaling(1.0 / 255)(inputs)
    
    # 4 blocos Conv2D + MaxPooling2D com filtros [32, 64, 128, 256]
    for filters in [32, 64, 128, 256]:
        x = layers.Conv2D(filters, 3, activation='relu')(x)
        x = layers.MaxPooling2D(2)(x)
    
    x = layers.GlobalAveragePooling2D()(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)
    
    model = models.Model(inputs, outputs)
    return model

model = build_baseline_cnn(num_classes)

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'],
)

model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 180, 180, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ rescaling (Rescaling)           │ (None, 180, 180, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 178, 178, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 89, 89, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 87, 87, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 43, 43, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 41, 41, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 20, 20, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 18, 18, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 9, 9, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 256)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 2)              │           514 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 388,930 (1.48 MB)

 Trainable params: 388,930 (1.48 MB)

 Non-trainable params: 0 (0.00 B)

In [15]:
# ─── 2.3d  Confirmação manual do nº de parâmetros ──────────────────────
print('=== Verificação manual dos parâmetros das duas primeiras convoluções ===\n')

# Conv2D_1: input 3 canais, 32 filtros, kernel 3×3
# Parâmetros = (kernel_h × kernel_w × input_channels + 1_bias) × n_filters
conv1_params = (3 * 3 * 3 + 1) * 32
print(f'Conv2D #1 (3→32, kernel 3×3):')
print(f'  Cálculo: (3 × 3 × 3 + 1) × 32 = ({3*3*3} + 1) × 32 = {3*3*3+1} × 32 = {conv1_params}')

# Conv2D_2: input 32 canais, 64 filtros, kernel 3×3
conv2_params = (3 * 3 * 32 + 1) * 64
print(f'\nConv2D #2 (32→64, kernel 3×3):')
print(f'  Cálculo: (3 × 3 × 32 + 1) × 64 = ({3*3*32} + 1) × 64 = {3*3*32+1} × 64 = {conv2_params}')

# Comparar com o summary
layer_configs = []
for layer in model.layers:
    if 'conv2d' in layer.name:
        layer_configs.append((layer.name, layer.count_params()))

print(f'\n--- Comparação com model.summary() ---')
print(f'Conv2D #1: cálculo manual = {conv1_params}, summary = {layer_configs[0][1]} → {"✅ OK" if conv1_params == layer_configs[0][1] else "❌ DIFERENTE"}')
print(f'Conv2D #2: cálculo manual = {conv2_params}, summary = {layer_configs[1][1]} → {"✅ OK" if conv2_params == layer_configs[1][1] else "❌ DIFERENTE"}')

=== Verificação manual dos parâmetros das duas primeiras convoluções ===

Conv2D #1 (3→32, kernel 3×3):
  Cálculo: (3 × 3 × 3 + 1) × 32 = (27 + 1) × 32 = 28 × 32 = 896

Conv2D #2 (32→64, kernel 3×3):
  Cálculo: (3 × 3 × 32 + 1) × 64 = (288 + 1) × 64 = 289 × 64 = 18496

--- Comparação com model.summary() ---
Conv2D #1: cálculo manual = 896, summary = 896 → ✅ OK
Conv2D #2: cálculo manual = 18496, summary = 18496 → ✅ OK

In [16]:
# ─── 2.3e  Treinar o modelo (30 épocas, sem callbacks) ─────────────────
EPOCHS = 30

print(f'Início do treino: {time.strftime("%H:%M:%S")}')
t0 = time.time()

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    verbose=1,
)

t1 = time.time()
train_time = t1 - t0
print(f'\nFim do treino: {time.strftime("%H:%M:%S")}')
print(f'Tempo total de treino: {train_time:.1f}s ({train_time/60:.1f} min)')

Início do treino: 13:20:43

C:\Users\vilar\Desktop\Mestrado\deeeplearning\.venv\Lib\site-packages\keras\src\trainers\epoch_iterator.py:74: UserWarning: `shuffle=True` was passed, but will be ignored since the data `x` was provided as a tf.data.Dataset. The Dataset is expected to already be shuffled (via `.shuffle(buffer_size)`).
  self.data_adapter = data_adapters.get_data_adapter(

Epoch 1/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 11:59 1s/step - accuracy: 0.4688 - loss: 0.6934

  3/606 ━━━━━━━━━━━━━━━━━━━━ 23s 39ms/step - accuracy: 0.5104 - loss: 0.6968

  5/606 ━━━━━━━━━━━━━━━━━━━━ 23s 39ms/step - accuracy: 0.5250 - loss: 0.6940

  7/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.5357 - loss: 0.6916

  9/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.5139 - loss: 0.6978

 11/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.5142 - loss: 0.6966

 13/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.5072 - loss: 0.6966

 15/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5042 - loss: 0.6957

 17/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5092 - loss: 0.6937

 19/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5164 - loss: 0.6928

 21/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5253 - loss: 0.6893

 23/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5217 - loss: 0.6915

 25/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5150 - loss: 0.6923

 27/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5266 - loss: 0.6916

 29/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5485 - loss: 0.6907

 31/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5595 - loss: 0.6899

 33/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5634 - loss: 0.6892

 35/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5696 - loss: 0.6867

 37/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5701 - loss: 0.6843

 39/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5729 - loss: 0.6816

 41/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5762 - loss: 0.6788

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5799 - loss: 0.6746

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5854 - loss: 0.6684

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5931 - loss: 0.6683

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.5938 - loss: 0.6667

 51/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.5925 - loss: 0.6666

 53/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.5908 - loss: 0.6668

 55/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.5989 - loss: 0.6646

 57/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.6031 - loss: 0.6639

 59/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.6102 - loss: 0.6628

 61/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.6168 - loss: 0.6614

 63/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.6230 - loss: 0.6590

 65/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.6308 - loss: 0.6540

 67/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.6343 - loss: 0.6540

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.6399 - loss: 0.6515

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.6413 - loss: 0.6508

 73/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.6391 - loss: 0.6515

 75/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.6404 - loss: 0.6499

 77/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.6461 - loss: 0.6474

 79/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.6523 - loss: 0.6426

 81/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.6559 - loss: 0.6473

 83/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.6619 - loss: 0.6426

 85/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.6673 - loss: 0.6376

 87/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.6728 - loss: 0.6322

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.6787 - loss: 0.6276

 91/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.6851 - loss: 0.6205

 93/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.6909 - loss: 0.6136

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.6961 - loss: 0.6083

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.7001 - loss: 0.6027

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.7045 - loss: 0.5959

101/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.7088 - loss: 0.5890

103/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.7109 - loss: 0.5855

105/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.7146 - loss: 0.5784

107/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.7185 - loss: 0.5707

109/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.7219 - loss: 0.5643

111/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.7249 - loss: 0.5676

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.7290 - loss: 0.5606

115/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.7318 - loss: 0.5570

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.7345 - loss: 0.5531

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.7353 - loss: 0.5579

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.7392 - loss: 0.5508

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.7406 - loss: 0.5487

125/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.7445 - loss: 0.5422

127/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.7483 - loss: 0.5366

129/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.7505 - loss: 0.5334

131/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.7529 - loss: 0.5296

133/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.7531 - loss: 0.5281

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.7544 - loss: 0.5253

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.7555 - loss: 0.5230

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.7556 - loss: 0.5217

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.7566 - loss: 0.5197

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.7594 - loss: 0.5165

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.7614 - loss: 0.5169

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.7640 - loss: 0.5126

149/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7668 - loss: 0.5117

151/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7692 - loss: 0.5076

153/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7708 - loss: 0.5094

155/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7720 - loss: 0.5098

157/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7723 - loss: 0.5088

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7738 - loss: 0.5059

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7752 - loss: 0.5032

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7757 - loss: 0.5047

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7761 - loss: 0.5030

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7779 - loss: 0.4998

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7798 - loss: 0.4964

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7820 - loss: 0.4930

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.7840 - loss: 0.4925

175/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7852 - loss: 0.4927

177/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7864 - loss: 0.4908

179/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7877 - loss: 0.4882

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7894 - loss: 0.4876

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7901 - loss: 0.4856

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7904 - loss: 0.4851

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7919 - loss: 0.4818

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7923 - loss: 0.4808

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7932 - loss: 0.4783

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7949 - loss: 0.4775

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7962 - loss: 0.4784

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.7977 - loss: 0.4753

199/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.7992 - loss: 0.4750

201/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.7993 - loss: 0.4745

203/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.8002 - loss: 0.4747

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.8000 - loss: 0.4743

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.8003 - loss: 0.4731

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.8011 - loss: 0.4714

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.8023 - loss: 0.4692

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.8036 - loss: 0.4669

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.8045 - loss: 0.4693

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.8056 - loss: 0.4679

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.8065 - loss: 0.4680

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.8073 - loss: 0.4662

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.8082 - loss: 0.4666

225/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8085 - loss: 0.4653

227/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8092 - loss: 0.4647

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8105 - loss: 0.4621

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8113 - loss: 0.4603

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8118 - loss: 0.4589

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8125 - loss: 0.4583

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8132 - loss: 0.4566

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8141 - loss: 0.4546

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8146 - loss: 0.4532

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8156 - loss: 0.4512

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8165 - loss: 0.4495

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.8172 - loss: 0.4476

249/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.8179 - loss: 0.4474

251/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.8182 - loss: 0.4466

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.8190 - loss: 0.4450

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.8200 - loss: 0.4430

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.8204 - loss: 0.4415

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.8214 - loss: 0.4412

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.8217 - loss: 0.4439

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.8226 - loss: 0.4432

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.8236 - loss: 0.4442

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.8243 - loss: 0.4458

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.8247 - loss: 0.4444

271/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8254 - loss: 0.4444

273/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8261 - loss: 0.4437

275/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8266 - loss: 0.4427

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8268 - loss: 0.4425

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8265 - loss: 0.4431

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8267 - loss: 0.4427

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8269 - loss: 0.4424

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8270 - loss: 0.4426

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8271 - loss: 0.4458

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8270 - loss: 0.4454

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8268 - loss: 0.4451

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.8268 - loss: 0.4448

295/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8270 - loss: 0.4454

297/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8275 - loss: 0.4444

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8279 - loss: 0.4438

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8284 - loss: 0.4430

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8288 - loss: 0.4439

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8293 - loss: 0.4426

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8298 - loss: 0.4413

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8305 - loss: 0.4396

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8313 - loss: 0.4379

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8318 - loss: 0.4364

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8323 - loss: 0.4365

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8330 - loss: 0.4361

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.8331 - loss: 0.4358

321/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8335 - loss: 0.4363

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8341 - loss: 0.4350

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8346 - loss: 0.4338

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8351 - loss: 0.4351

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8355 - loss: 0.4341

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8359 - loss: 0.4343

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8361 - loss: 0.4343

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8364 - loss: 0.4358

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8362 - loss: 0.4356

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8357 - loss: 0.4369

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8354 - loss: 0.4378

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.8344 - loss: 0.4393

345/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8333 - loss: 0.4404

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8321 - loss: 0.4414

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8315 - loss: 0.4422

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8302 - loss: 0.4433

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8296 - loss: 0.4441

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8286 - loss: 0.4449

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8276 - loss: 0.4456

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8269 - loss: 0.4463

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8261 - loss: 0.4469

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8258 - loss: 0.4473

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8262 - loss: 0.4475

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.8265 - loss: 0.4481

369/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8268 - loss: 0.4478

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8274 - loss: 0.4471

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8280 - loss: 0.4478

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8283 - loss: 0.4479

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8282 - loss: 0.4482

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8276 - loss: 0.4485

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8269 - loss: 0.4490

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8265 - loss: 0.4494

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8255 - loss: 0.4502

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8246 - loss: 0.4508

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.8240 - loss: 0.4515

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8233 - loss: 0.4519

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8224 - loss: 0.4526

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8223 - loss: 0.4531

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8220 - loss: 0.4532

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8222 - loss: 0.4534

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8220 - loss: 0.4536

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8218 - loss: 0.4537

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8221 - loss: 0.4547

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8224 - loss: 0.4545

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8226 - loss: 0.4543

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8229 - loss: 0.4538

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.8229 - loss: 0.4537

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8231 - loss: 0.4534

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8235 - loss: 0.4529

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8240 - loss: 0.4523

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8245 - loss: 0.4514

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8247 - loss: 0.4514

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8251 - loss: 0.4505

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8251 - loss: 0.4506

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8252 - loss: 0.4500

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8248 - loss: 0.4503

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8245 - loss: 0.4504

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8249 - loss: 0.4495

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.8253 - loss: 0.4496

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8252 - loss: 0.4502

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8257 - loss: 0.4493

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8258 - loss: 0.4490

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8258 - loss: 0.4485

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8255 - loss: 0.4496

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8254 - loss: 0.4495

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8253 - loss: 0.4496

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8252 - loss: 0.4495

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8251 - loss: 0.4493

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8252 - loss: 0.4490

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8255 - loss: 0.4484

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.8257 - loss: 0.4486

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8259 - loss: 0.4483

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8262 - loss: 0.4476

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8264 - loss: 0.4472

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8264 - loss: 0.4468

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8267 - loss: 0.4461

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8266 - loss: 0.4459

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8268 - loss: 0.4453

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8271 - loss: 0.4457

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8275 - loss: 0.4450

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8277 - loss: 0.4443

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8280 - loss: 0.4435

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.8281 - loss: 0.4433

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8285 - loss: 0.4423

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8289 - loss: 0.4421

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8290 - loss: 0.4417

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8292 - loss: 0.4418

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8294 - loss: 0.4413

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8295 - loss: 0.4407

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8298 - loss: 0.4400

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8301 - loss: 0.4393

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8303 - loss: 0.4398

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8308 - loss: 0.4387

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8312 - loss: 0.4378

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.8317 - loss: 0.4368

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8321 - loss: 0.4368

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8325 - loss: 0.4359

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8331 - loss: 0.4346

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8334 - loss: 0.4338

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8338 - loss: 0.4339

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8342 - loss: 0.4329

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8344 - loss: 0.4334

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8348 - loss: 0.4333

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8350 - loss: 0.4336

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8355 - loss: 0.4324

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8359 - loss: 0.4314

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.8364 - loss: 0.4304

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8368 - loss: 0.4292

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8373 - loss: 0.4279

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8379 - loss: 0.4266

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8383 - loss: 0.4273

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8388 - loss: 0.4261

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8390 - loss: 0.4278

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8394 - loss: 0.4268

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8399 - loss: 0.4254

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8400 - loss: 0.4268

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8401 - loss: 0.4279

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8405 - loss: 0.4276

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.8408 - loss: 0.4267

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8411 - loss: 0.4266

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8416 - loss: 0.4255

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8416 - loss: 0.4285

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8418 - loss: 0.4278

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8422 - loss: 0.4269

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8426 - loss: 0.4267

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8429 - loss: 0.4259

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8432 - loss: 0.4250

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8436 - loss: 0.4240

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8440 - loss: 0.4231

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8442 - loss: 0.4224

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8446 - loss: 0.4215

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8449 - loss: 0.4207

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8451 - loss: 0.4201

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8453 - loss: 0.4204

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8455 - loss: 0.4201

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8458 - loss: 0.4193

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8458 - loss: 0.4189

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8458 - loss: 0.4187

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8461 - loss: 0.4182

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8460 - loss: 0.4187

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8460 - loss: 0.4184

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8463 - loss: 0.4180

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8465 - loss: 0.4175

606/606 ━━━━━━━━━━━━━━━━━━━━ 30s 47ms/step - accuracy: 0.8466 - loss: 0.4173 - val_accuracy: 0.9408 - val_loss: 0.2847

Epoch 2/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 36s 60ms/step - accuracy: 0.8750 - loss: 0.2998

  3/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.8750 - loss: 0.2915

  5/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.8750 - loss: 0.3891

  7/606 ━━━━━━━━━━━━━━━━━━━━ 24s 40ms/step - accuracy: 0.8750 - loss: 0.3552

  9/606 ━━━━━━━━━━━━━━━━━━━━ 23s 39ms/step - accuracy: 0.8854 - loss: 0.3700

 11/606 ━━━━━━━━━━━━━━━━━━━━ 23s 39ms/step - accuracy: 0.9006 - loss: 0.3295

 13/606 ━━━━━━━━━━━━━━━━━━━━ 22s 39ms/step - accuracy: 0.8966 - loss: 0.3263

 15/606 ━━━━━━━━━━━━━━━━━━━━ 22s 39ms/step - accuracy: 0.9042 - loss: 0.3028

 17/606 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - accuracy: 0.9081 - loss: 0.2893

 19/606 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - accuracy: 0.9161 - loss: 0.2706

 21/606 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - accuracy: 0.9122 - loss: 0.2920

 23/606 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - accuracy: 0.9144 - loss: 0.2825

 25/606 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - accuracy: 0.9162 - loss: 0.2786

 27/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9190 - loss: 0.2691

 29/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9181 - loss: 0.2819

 31/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9214 - loss: 0.2707

 33/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9233 - loss: 0.2744

 35/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9268 - loss: 0.2758

 37/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9274 - loss: 0.2818

 39/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9279 - loss: 0.2990

 41/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9299 - loss: 0.3009

 43/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9324 - loss: 0.3006

 45/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9340 - loss: 0.3041

 47/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9348 - loss: 0.3069

 49/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9349 - loss: 0.3091

 51/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9357 - loss: 0.3019

 53/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9346 - loss: 0.3000

 55/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9312 - loss: 0.3029

 57/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9298 - loss: 0.3024

 59/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9296 - loss: 0.3008

 61/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9308 - loss: 0.2956

 63/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9306 - loss: 0.3005

 65/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9308 - loss: 0.2978

 67/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9291 - loss: 0.2977

 69/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9298 - loss: 0.2944

 71/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9291 - loss: 0.2930

 73/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9302 - loss: 0.2891

 75/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9296 - loss: 0.2933

 77/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9294 - loss: 0.2918

 79/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9304 - loss: 0.2878

 81/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9306 - loss: 0.2856

 83/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9311 - loss: 0.2839

 85/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9316 - loss: 0.2806

 87/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9314 - loss: 0.2841

 89/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9308 - loss: 0.2880

 91/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9306 - loss: 0.2866

 93/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9301 - loss: 0.2949

 95/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9309 - loss: 0.2911

 97/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9311 - loss: 0.2904

 99/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9315 - loss: 0.2919

101/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9319 - loss: 0.2888

103/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9320 - loss: 0.2891

105/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9321 - loss: 0.2919

107/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9325 - loss: 0.2888

109/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9326 - loss: 0.2905

111/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9319 - loss: 0.3059

113/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9320 - loss: 0.3040

115/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9321 - loss: 0.3013

117/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9319 - loss: 0.3013

119/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9304 - loss: 0.3031

121/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9300 - loss: 0.3019

123/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9273 - loss: 0.3054

125/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9260 - loss: 0.3072

127/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9230 - loss: 0.3095

129/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9205 - loss: 0.3150

131/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9196 - loss: 0.3160

133/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9185 - loss: 0.3168

135/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9174 - loss: 0.3175

137/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9149 - loss: 0.3196

139/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9130 - loss: 0.3248

141/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9107 - loss: 0.3264

143/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9102 - loss: 0.3264

145/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9088 - loss: 0.3277

147/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9080 - loss: 0.3280

149/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9073 - loss: 0.3278

151/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9073 - loss: 0.3273

153/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9073 - loss: 0.3264

155/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9067 - loss: 0.3292

157/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9061 - loss: 0.3285

159/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9057 - loss: 0.3284

161/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9053 - loss: 0.3310

163/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9061 - loss: 0.3291

165/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9057 - loss: 0.3307

167/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9055 - loss: 0.3312

169/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9061 - loss: 0.3293

171/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9061 - loss: 0.3293

173/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9064 - loss: 0.3278

175/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9064 - loss: 0.3301

177/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9064 - loss: 0.3293

179/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9064 - loss: 0.3311

181/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9062 - loss: 0.3323

183/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9062 - loss: 0.3336

185/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9066 - loss: 0.3320

187/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9068 - loss: 0.3307

189/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9069 - loss: 0.3295

191/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9071 - loss: 0.3310

193/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9075 - loss: 0.3316

195/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9080 - loss: 0.3300

197/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9078 - loss: 0.3314

199/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9083 - loss: 0.3293

201/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9081 - loss: 0.3287

203/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9084 - loss: 0.3314

205/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9079 - loss: 0.3315

207/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9084 - loss: 0.3296

209/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9091 - loss: 0.3297

211/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9088 - loss: 0.3334

213/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9092 - loss: 0.3320

215/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9094 - loss: 0.3347

217/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9099 - loss: 0.3353

219/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9097 - loss: 0.3348

221/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9098 - loss: 0.3375

223/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9102 - loss: 0.3376

225/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9107 - loss: 0.3356

227/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9105 - loss: 0.3387

229/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9106 - loss: 0.3391

231/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9108 - loss: 0.3378

233/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9113 - loss: 0.3357

235/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9114 - loss: 0.3351

237/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9115 - loss: 0.3340

239/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9113 - loss: 0.3336

241/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9112 - loss: 0.3337

243/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9110 - loss: 0.3334

245/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9114 - loss: 0.3323

247/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9117 - loss: 0.3311

249/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9114 - loss: 0.3311

251/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9117 - loss: 0.3296

253/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9114 - loss: 0.3292

255/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9114 - loss: 0.3286

257/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9115 - loss: 0.3293

259/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9112 - loss: 0.3305

261/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9114 - loss: 0.3312

263/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9115 - loss: 0.3324

265/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9117 - loss: 0.3314

267/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9116 - loss: 0.3307

269/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9118 - loss: 0.3299

271/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9119 - loss: 0.3291

273/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9119 - loss: 0.3287

275/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9119 - loss: 0.3296

277/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9120 - loss: 0.3288

279/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9116 - loss: 0.3288

281/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9111 - loss: 0.3287

283/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9106 - loss: 0.3288

285/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9105 - loss: 0.3288

287/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9105 - loss: 0.3310

289/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9100 - loss: 0.3327

291/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9097 - loss: 0.3323

293/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9097 - loss: 0.3319

295/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9100 - loss: 0.3309

297/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9101 - loss: 0.3298

299/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9103 - loss: 0.3291

301/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9103 - loss: 0.3284

303/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9102 - loss: 0.3293

305/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9101 - loss: 0.3289

307/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9104 - loss: 0.3292

309/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9110 - loss: 0.3275

311/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9108 - loss: 0.3350

313/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9109 - loss: 0.3369

315/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9112 - loss: 0.3363

317/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9114 - loss: 0.3366

319/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9116 - loss: 0.3351

321/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9112 - loss: 0.3378

323/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9115 - loss: 0.3363

325/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9110 - loss: 0.3367

327/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9111 - loss: 0.3360

329/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9106 - loss: 0.3379

331/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9107 - loss: 0.3376

333/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9098 - loss: 0.3389

335/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9098 - loss: 0.3386

337/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9097 - loss: 0.3383

339/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9091 - loss: 0.3387

341/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9088 - loss: 0.3386

343/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9084 - loss: 0.3387

345/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9081 - loss: 0.3390

347/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9081 - loss: 0.3391

349/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9080 - loss: 0.3385

351/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9077 - loss: 0.3385

353/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9076 - loss: 0.3381

355/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9076 - loss: 0.3377

357/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9077 - loss: 0.3370

359/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9076 - loss: 0.3365

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9080 - loss: 0.3357

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9082 - loss: 0.3373

365/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9081 - loss: 0.3369

367/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9083 - loss: 0.3362

369/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9078 - loss: 0.3378

371/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9079 - loss: 0.3371

373/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9080 - loss: 0.3364

375/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9081 - loss: 0.3357

377/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9078 - loss: 0.3373

379/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9079 - loss: 0.3371

381/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9081 - loss: 0.3362

383/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9084 - loss: 0.3352

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9086 - loss: 0.3348

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9086 - loss: 0.3348

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9087 - loss: 0.3340

391/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9086 - loss: 0.3338

393/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9087 - loss: 0.3342

395/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9086 - loss: 0.3338

397/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9085 - loss: 0.3345

399/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9087 - loss: 0.3347

401/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9086 - loss: 0.3365

403/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9090 - loss: 0.3353

405/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9092 - loss: 0.3345

407/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9092 - loss: 0.3339

409/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9095 - loss: 0.3342

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9097 - loss: 0.3334

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9096 - loss: 0.3328

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9099 - loss: 0.3317

417/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9099 - loss: 0.3312

419/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9098 - loss: 0.3329

421/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9100 - loss: 0.3319

423/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9101 - loss: 0.3331

425/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9105 - loss: 0.3318

427/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9106 - loss: 0.3332

429/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9108 - loss: 0.3334

431/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9108 - loss: 0.3345

433/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9111 - loss: 0.3335

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9113 - loss: 0.3335

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9113 - loss: 0.3338

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9116 - loss: 0.3337

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9117 - loss: 0.3349

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9118 - loss: 0.3372

445/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9119 - loss: 0.3373

447/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9120 - loss: 0.3372

449/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9121 - loss: 0.3381

451/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9121 - loss: 0.3396

453/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9124 - loss: 0.3385

455/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9124 - loss: 0.3382

457/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9125 - loss: 0.3375

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9122 - loss: 0.3383

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9121 - loss: 0.3381

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9124 - loss: 0.3381

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9122 - loss: 0.3390

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9124 - loss: 0.3381

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9123 - loss: 0.3394

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9122 - loss: 0.3393

473/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9123 - loss: 0.3385

475/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9125 - loss: 0.3378

477/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9125 - loss: 0.3372

479/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9126 - loss: 0.3375

481/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9125 - loss: 0.3374

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9124 - loss: 0.3373

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9125 - loss: 0.3368

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9125 - loss: 0.3363

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9125 - loss: 0.3357

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9124 - loss: 0.3353

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9124 - loss: 0.3352

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9124 - loss: 0.3346

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9123 - loss: 0.3344

499/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9124 - loss: 0.3339

501/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9127 - loss: 0.3333

503/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9126 - loss: 0.3337

505/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9128 - loss: 0.3331

507/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9129 - loss: 0.3339

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9130 - loss: 0.3333

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9131 - loss: 0.3329

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9134 - loss: 0.3320

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9134 - loss: 0.3315

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9136 - loss: 0.3308

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9139 - loss: 0.3298

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9138 - loss: 0.3304

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9140 - loss: 0.3300

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9142 - loss: 0.3301

527/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9140 - loss: 0.3301

529/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9140 - loss: 0.3295

531/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9141 - loss: 0.3306

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9142 - loss: 0.3302

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9144 - loss: 0.3297

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9145 - loss: 0.3291

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9147 - loss: 0.3283

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9149 - loss: 0.3276

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9151 - loss: 0.3281

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9151 - loss: 0.3278

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9153 - loss: 0.3269

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9154 - loss: 0.3272

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9156 - loss: 0.3263

553/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9157 - loss: 0.3256

555/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9156 - loss: 0.3264

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9157 - loss: 0.3266

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9158 - loss: 0.3260

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9159 - loss: 0.3274

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9159 - loss: 0.3279

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9159 - loss: 0.3282

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9158 - loss: 0.3280

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9159 - loss: 0.3276

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9160 - loss: 0.3270

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9162 - loss: 0.3265

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9162 - loss: 0.3259

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9163 - loss: 0.3254

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9162 - loss: 0.3252

581/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9159 - loss: 0.3252

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9162 - loss: 0.3245

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9163 - loss: 0.3242

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9163 - loss: 0.3238

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9164 - loss: 0.3242

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9165 - loss: 0.3237

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9166 - loss: 0.3231

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9166 - loss: 0.3227

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9168 - loss: 0.3221

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.3220

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9168 - loss: 0.3221

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9169 - loss: 0.3216

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9171 - loss: 0.3209

606/606 ━━━━━━━━━━━━━━━━━━━━ 25s 41ms/step - accuracy: 0.9172 - loss: 0.3206 - val_accuracy: 0.9433 - val_loss: 0.4048

Epoch 3/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.9688 - loss: 0.1384

  3/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9375 - loss: 0.1911

  5/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9438 - loss: 0.1612

  7/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9509 - loss: 0.1438

  9/606 ━━━━━━━━━━━━━━━━━━━━ 21s 35ms/step - accuracy: 0.9410 - loss: 0.1983

 11/606 ━━━━━━━━━━━━━━━━━━━━ 21s 35ms/step - accuracy: 0.9375 - loss: 0.2430

 13/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9327 - loss: 0.2414

 15/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9354 - loss: 0.2282

 17/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9338 - loss: 0.2254

 19/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9276 - loss: 0.2330

 21/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9301 - loss: 0.2263

 23/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9293 - loss: 0.2233

 25/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9300 - loss: 0.2203

 27/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9329 - loss: 0.2149

 29/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9353 - loss: 0.2082

 31/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9345 - loss: 0.2069

 33/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9328 - loss: 0.2056

 35/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9312 - loss: 0.2209

 37/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9299 - loss: 0.2284

 39/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9311 - loss: 0.2238

 41/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9314 - loss: 0.2409

 43/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9281 - loss: 0.2491

 45/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9278 - loss: 0.2468

 47/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9282 - loss: 0.2442

 49/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9286 - loss: 0.2403

 51/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9283 - loss: 0.2435

 53/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9292 - loss: 0.2402

 55/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9301 - loss: 0.2396

 57/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9287 - loss: 0.2415

 59/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9301 - loss: 0.2379

 61/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9298 - loss: 0.2354

 63/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9306 - loss: 0.2389

 65/606 ━━━━━━━━━━━━━━━━━━━━ 19s 36ms/step - accuracy: 0.9303 - loss: 0.2378

 67/606 ━━━━━━━━━━━━━━━━━━━━ 19s 36ms/step - accuracy: 0.9291 - loss: 0.2422

 69/606 ━━━━━━━━━━━━━━━━━━━━ 19s 36ms/step - accuracy: 0.9298 - loss: 0.2407

 71/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9278 - loss: 0.2435

 73/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9272 - loss: 0.2447

 75/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9267 - loss: 0.2458

 77/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9278 - loss: 0.2432

 79/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9276 - loss: 0.2441

 81/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9279 - loss: 0.2427

 83/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9277 - loss: 0.2410

 85/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9283 - loss: 0.2387

 87/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9282 - loss: 0.2371

 89/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9284 - loss: 0.2378

 91/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9289 - loss: 0.2358

 93/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9291 - loss: 0.2346

 95/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9299 - loss: 0.2323

 97/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9285 - loss: 0.2368

 99/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9290 - loss: 0.2345

101/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9285 - loss: 0.2345

103/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9293 - loss: 0.2323

105/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9292 - loss: 0.2320

107/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9299 - loss: 0.2295

109/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9289 - loss: 0.2301

111/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9288 - loss: 0.2310

113/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9281 - loss: 0.2326

115/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9272 - loss: 0.2348

117/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9282 - loss: 0.2321

119/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9280 - loss: 0.2319

121/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9282 - loss: 0.2307

123/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9286 - loss: 0.2305

125/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9290 - loss: 0.2302

127/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9296 - loss: 0.2286

129/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9297 - loss: 0.2279

131/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9303 - loss: 0.2265

133/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9300 - loss: 0.2313

135/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9301 - loss: 0.2305

137/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9297 - loss: 0.2322

139/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9294 - loss: 0.2326

141/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9302 - loss: 0.2307

143/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9299 - loss: 0.2312

145/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9297 - loss: 0.2300

147/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9296 - loss: 0.2296

149/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9297 - loss: 0.2294

151/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9303 - loss: 0.2278

153/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9308 - loss: 0.2264

155/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9306 - loss: 0.2273

157/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9305 - loss: 0.2266

159/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9306 - loss: 0.2258

161/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9313 - loss: 0.2242

163/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9314 - loss: 0.2236

165/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9312 - loss: 0.2230

167/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9306 - loss: 0.2241

169/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9308 - loss: 0.2231

171/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9307 - loss: 0.2236

173/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9303 - loss: 0.2245

175/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9304 - loss: 0.2239

177/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9296 - loss: 0.2261

179/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9295 - loss: 0.2261

181/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9297 - loss: 0.2252

183/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9300 - loss: 0.2243

185/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9306 - loss: 0.2226

187/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9311 - loss: 0.2211

189/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9315 - loss: 0.2212

191/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9313 - loss: 0.2228

193/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9309 - loss: 0.2228

195/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9303 - loss: 0.2234

197/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9300 - loss: 0.2232

199/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9300 - loss: 0.2229

201/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9299 - loss: 0.2225

203/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9304 - loss: 0.2212

205/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9303 - loss: 0.2224

207/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9307 - loss: 0.2213

209/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9305 - loss: 0.2215

211/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9304 - loss: 0.2211

213/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9306 - loss: 0.2203

215/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9308 - loss: 0.2195

217/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9304 - loss: 0.2196

219/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9302 - loss: 0.2198

221/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9307 - loss: 0.2184

223/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9304 - loss: 0.2193

225/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9299 - loss: 0.2205

227/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9301 - loss: 0.2200

229/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9304 - loss: 0.2193

231/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9303 - loss: 0.2200

233/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9307 - loss: 0.2192

235/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9306 - loss: 0.2194

237/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9308 - loss: 0.2190

239/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9306 - loss: 0.2192

241/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9308 - loss: 0.2187

243/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9308 - loss: 0.2183

245/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9309 - loss: 0.2177

247/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9307 - loss: 0.2175

249/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9307 - loss: 0.2174

251/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9308 - loss: 0.2170

253/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9311 - loss: 0.2162

255/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9311 - loss: 0.2156

257/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9306 - loss: 0.2178

259/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9304 - loss: 0.2175

261/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9306 - loss: 0.2172

263/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9306 - loss: 0.2167

265/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9305 - loss: 0.2165

267/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9308 - loss: 0.2158

269/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9303 - loss: 0.2166

271/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9305 - loss: 0.2161

273/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9306 - loss: 0.2157

275/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9311 - loss: 0.2149

277/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9307 - loss: 0.2157

279/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9311 - loss: 0.2147

281/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9309 - loss: 0.2148

283/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9311 - loss: 0.2143

285/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9307 - loss: 0.2149

287/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9311 - loss: 0.2141

289/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9311 - loss: 0.2136

291/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9307 - loss: 0.2140

293/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9307 - loss: 0.2153

295/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9307 - loss: 0.2154

297/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9309 - loss: 0.2152

299/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9310 - loss: 0.2155

301/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9309 - loss: 0.2157

303/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9309 - loss: 0.2155

305/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9305 - loss: 0.2165

307/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9307 - loss: 0.2158

309/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9306 - loss: 0.2156

311/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9306 - loss: 0.2154

313/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9305 - loss: 0.2154

315/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9308 - loss: 0.2147

317/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9309 - loss: 0.2141

319/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9309 - loss: 0.2138

321/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9311 - loss: 0.2133

323/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9314 - loss: 0.2126

325/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9316 - loss: 0.2122

327/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9317 - loss: 0.2119

329/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9318 - loss: 0.2115

331/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9319 - loss: 0.2122

333/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9321 - loss: 0.2118

335/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9323 - loss: 0.2122

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9325 - loss: 0.2119

339/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9323 - loss: 0.2122

341/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9324 - loss: 0.2120

343/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9323 - loss: 0.2121

345/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9324 - loss: 0.2118

347/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9325 - loss: 0.2115

349/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9326 - loss: 0.2112

351/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9329 - loss: 0.2105

353/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9328 - loss: 0.2108

355/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9326 - loss: 0.2111

357/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9328 - loss: 0.2104

359/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9329 - loss: 0.2098

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9331 - loss: 0.2091

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9331 - loss: 0.2087

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9333 - loss: 0.2082

367/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9334 - loss: 0.2079

369/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9334 - loss: 0.2085

371/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9334 - loss: 0.2083

373/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9334 - loss: 0.2081

375/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9333 - loss: 0.2084

377/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9333 - loss: 0.2082

379/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9334 - loss: 0.2078

381/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9336 - loss: 0.2074

383/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9334 - loss: 0.2080

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9335 - loss: 0.2075

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9337 - loss: 0.2069

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9339 - loss: 0.2065

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9340 - loss: 0.2061

393/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9342 - loss: 0.2066

395/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9341 - loss: 0.2067

397/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9341 - loss: 0.2077

399/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9343 - loss: 0.2075

401/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9343 - loss: 0.2071

403/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9346 - loss: 0.2067

405/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9347 - loss: 0.2061

407/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9347 - loss: 0.2061

409/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9347 - loss: 0.2057

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9349 - loss: 0.2050

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9350 - loss: 0.2048

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9349 - loss: 0.2045

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9349 - loss: 0.2045

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9348 - loss: 0.2052

421/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9349 - loss: 0.2053

423/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9350 - loss: 0.2049

425/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9351 - loss: 0.2045

427/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9352 - loss: 0.2052

429/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9351 - loss: 0.2052

431/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9353 - loss: 0.2048

433/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9353 - loss: 0.2045

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9353 - loss: 0.2042

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9353 - loss: 0.2046

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9355 - loss: 0.2040

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9356 - loss: 0.2038

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9357 - loss: 0.2034

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.9359 - loss: 0.2029

447/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9359 - loss: 0.2031

449/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9359 - loss: 0.2036

451/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9360 - loss: 0.2034

453/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9361 - loss: 0.2032

455/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9362 - loss: 0.2026

457/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9362 - loss: 0.2027

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9364 - loss: 0.2021

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9365 - loss: 0.2018

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9362 - loss: 0.2021

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9363 - loss: 0.2021

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9362 - loss: 0.2020

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9364 - loss: 0.2016

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - accuracy: 0.9364 - loss: 0.2014

473/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9364 - loss: 0.2012

475/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9364 - loss: 0.2008

477/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9366 - loss: 0.2003

479/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9369 - loss: 0.1996

481/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9369 - loss: 0.2000

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9369 - loss: 0.1999

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9369 - loss: 0.1998

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9369 - loss: 0.1996

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9369 - loss: 0.1996

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9372 - loss: 0.1990

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9371 - loss: 0.1992

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9370 - loss: 0.1995

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.9368 - loss: 0.1999

499/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9369 - loss: 0.1996

501/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9368 - loss: 0.1999

503/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9368 - loss: 0.2000

505/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9368 - loss: 0.2000

507/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9370 - loss: 0.1996

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9372 - loss: 0.1992

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9373 - loss: 0.1990

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9373 - loss: 0.1988

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9373 - loss: 0.1989

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9373 - loss: 0.1988

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9374 - loss: 0.1983

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9374 - loss: 0.1985

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9374 - loss: 0.1983

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9374 - loss: 0.1981

527/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9376 - loss: 0.1977

529/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9376 - loss: 0.1977

531/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9378 - loss: 0.1978

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9378 - loss: 0.1977

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9377 - loss: 0.1976

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9378 - loss: 0.1974

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9378 - loss: 0.1973

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9378 - loss: 0.1975

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9377 - loss: 0.1977

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9378 - loss: 0.1975

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9377 - loss: 0.1977

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9377 - loss: 0.1975

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - accuracy: 0.9378 - loss: 0.1971

553/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9380 - loss: 0.1967

555/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9379 - loss: 0.1965

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9379 - loss: 0.1965

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9380 - loss: 0.1962

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9381 - loss: 0.1960

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9382 - loss: 0.1955

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9382 - loss: 0.1954

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9383 - loss: 0.1953

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9384 - loss: 0.1949

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9383 - loss: 0.1949

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9385 - loss: 0.1945

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9385 - loss: 0.1943

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9385 - loss: 0.1941

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9386 - loss: 0.1938

581/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9387 - loss: 0.1936

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9387 - loss: 0.1935

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9387 - loss: 0.1932

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9388 - loss: 0.1929

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9388 - loss: 0.1929

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9388 - loss: 0.1930

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9388 - loss: 0.1928

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9390 - loss: 0.1924

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9391 - loss: 0.1920

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9392 - loss: 0.1917

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9393 - loss: 0.1917

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9394 - loss: 0.1913

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9396 - loss: 0.1909

606/606 ━━━━━━━━━━━━━━━━━━━━ 25s 41ms/step - accuracy: 0.9395 - loss: 0.1911 - val_accuracy: 0.9537 - val_loss: 0.1754

Epoch 4/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 1.0000 - loss: 0.0424

  3/606 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - accuracy: 0.9688 - loss: 0.1074

  5/606 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - accuracy: 0.9500 - loss: 0.1256

  7/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9509 - loss: 0.1254

  9/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9549 - loss: 0.1168

 11/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9574 - loss: 0.1145

 13/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9615 - loss: 0.1063

 15/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9542 - loss: 0.1252

 17/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9522 - loss: 0.1275

 19/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9572 - loss: 0.1185

 21/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9598 - loss: 0.1140

 23/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9565 - loss: 0.1237

 25/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9538 - loss: 0.1305

 27/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9560 - loss: 0.1322

 29/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9547 - loss: 0.1397

 31/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9536 - loss: 0.1508

 33/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9536 - loss: 0.1489

 35/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9482 - loss: 0.1547

 37/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9502 - loss: 0.1502

 39/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9511 - loss: 0.1513

 41/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9505 - loss: 0.1552

 43/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9506 - loss: 0.1551

 45/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9500 - loss: 0.1576

 47/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9521 - loss: 0.1531

 49/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9515 - loss: 0.1521

 51/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9522 - loss: 0.1495

 53/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9493 - loss: 0.1533

 55/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9494 - loss: 0.1522

 57/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9501 - loss: 0.1538

 59/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9486 - loss: 0.1553

 61/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9498 - loss: 0.1591

 63/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9494 - loss: 0.1579

 65/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9490 - loss: 0.1577

 67/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9473 - loss: 0.1622

 69/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9475 - loss: 0.1619

 71/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9450 - loss: 0.1642

 73/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9456 - loss: 0.1625

 75/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9458 - loss: 0.1628

 77/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9452 - loss: 0.1644

 79/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9442 - loss: 0.1653

 81/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9444 - loss: 0.1656

 83/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9454 - loss: 0.1635

 85/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9463 - loss: 0.1621

 87/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9476 - loss: 0.1599

 89/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9477 - loss: 0.1593

 91/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9485 - loss: 0.1570

 93/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9479 - loss: 0.1570

 95/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9477 - loss: 0.1572

 97/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9485 - loss: 0.1551

 99/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9479 - loss: 0.1561

101/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9486 - loss: 0.1544

103/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9478 - loss: 0.1568

105/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9473 - loss: 0.1575

107/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9474 - loss: 0.1567

109/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9470 - loss: 0.1570

111/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9459 - loss: 0.1639

113/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9469 - loss: 0.1615

115/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9470 - loss: 0.1614

117/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9468 - loss: 0.1617

119/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9459 - loss: 0.1641

121/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9460 - loss: 0.1633

123/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9451 - loss: 0.1645

125/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9442 - loss: 0.1669

127/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9446 - loss: 0.1663

129/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9448 - loss: 0.1675

131/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9447 - loss: 0.1692

133/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9453 - loss: 0.1681

135/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9456 - loss: 0.1675

137/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9453 - loss: 0.1693

139/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9454 - loss: 0.1687

141/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9450 - loss: 0.1695

143/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9454 - loss: 0.1685

145/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9448 - loss: 0.1689

147/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9452 - loss: 0.1683

149/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9453 - loss: 0.1689

151/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9458 - loss: 0.1674

153/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9455 - loss: 0.1669

155/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9450 - loss: 0.1694

157/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9453 - loss: 0.1688

159/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9452 - loss: 0.1697

161/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9455 - loss: 0.1687

163/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9454 - loss: 0.1690

165/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9455 - loss: 0.1685

167/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9454 - loss: 0.1683

169/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9453 - loss: 0.1690

171/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9443 - loss: 0.1703

173/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9442 - loss: 0.1706

175/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9443 - loss: 0.1706

177/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9440 - loss: 0.1708

179/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9443 - loss: 0.1706

181/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9444 - loss: 0.1718

183/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9445 - loss: 0.1712

185/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9448 - loss: 0.1715

187/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9450 - loss: 0.1709

189/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9451 - loss: 0.1704

191/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9454 - loss: 0.1703

193/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9443 - loss: 0.1717

195/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9444 - loss: 0.1710

197/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9437 - loss: 0.1719

199/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9435 - loss: 0.1726

201/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9434 - loss: 0.1737

203/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9438 - loss: 0.1728

205/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9439 - loss: 0.1730

207/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9437 - loss: 0.1730

209/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9438 - loss: 0.1724

211/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9440 - loss: 0.1728

213/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9434 - loss: 0.1742

215/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9435 - loss: 0.1739

217/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9433 - loss: 0.1742

219/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9435 - loss: 0.1739

221/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9434 - loss: 0.1751

223/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9432 - loss: 0.1752

225/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9438 - loss: 0.1743

227/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9436 - loss: 0.1746

229/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9438 - loss: 0.1743

231/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9436 - loss: 0.1740

233/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9437 - loss: 0.1742

235/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9440 - loss: 0.1737

237/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9436 - loss: 0.1737

239/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9440 - loss: 0.1727

241/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9439 - loss: 0.1730

243/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9438 - loss: 0.1729

245/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9439 - loss: 0.1723

247/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9440 - loss: 0.1727

249/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9442 - loss: 0.1723

251/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9440 - loss: 0.1728

253/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9440 - loss: 0.1727

255/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9444 - loss: 0.1719

257/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9442 - loss: 0.1719

259/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9446 - loss: 0.1711

261/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9447 - loss: 0.1713

263/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9444 - loss: 0.1722

265/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9445 - loss: 0.1722

267/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9443 - loss: 0.1720

269/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9441 - loss: 0.1721

271/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9440 - loss: 0.1724

273/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9439 - loss: 0.1721

275/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9436 - loss: 0.1725

277/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9439 - loss: 0.1719

279/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9440 - loss: 0.1728

281/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9443 - loss: 0.1721

283/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9441 - loss: 0.1726

285/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9442 - loss: 0.1720

287/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9440 - loss: 0.1722

289/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9437 - loss: 0.1731

291/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9436 - loss: 0.1736

293/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9433 - loss: 0.1744

295/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9427 - loss: 0.1753

297/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9431 - loss: 0.1743

299/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9430 - loss: 0.1744

301/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9431 - loss: 0.1740

303/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9430 - loss: 0.1740

305/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9431 - loss: 0.1735

307/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9433 - loss: 0.1740

309/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9434 - loss: 0.1738

311/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9430 - loss: 0.1744

313/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9433 - loss: 0.1739

315/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9436 - loss: 0.1733

317/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9436 - loss: 0.1731

319/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9438 - loss: 0.1727

321/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9437 - loss: 0.1725

323/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9437 - loss: 0.1726

325/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9437 - loss: 0.1727

327/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9437 - loss: 0.1725

329/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9437 - loss: 0.1725

331/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9437 - loss: 0.1730

333/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9440 - loss: 0.1724

335/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9438 - loss: 0.1734

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9439 - loss: 0.1733

339/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9437 - loss: 0.1736

341/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9436 - loss: 0.1735

343/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9432 - loss: 0.1740

345/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9433 - loss: 0.1736

347/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9433 - loss: 0.1735

349/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9432 - loss: 0.1736

351/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9432 - loss: 0.1742

353/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9432 - loss: 0.1741

355/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9431 - loss: 0.1741

357/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9431 - loss: 0.1741

359/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9432 - loss: 0.1737

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9435 - loss: 0.1730

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9437 - loss: 0.1724

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9432 - loss: 0.1744

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9434 - loss: 0.1740

369/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9429 - loss: 0.1753

371/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9429 - loss: 0.1752

373/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9429 - loss: 0.1749

375/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9430 - loss: 0.1748

377/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9429 - loss: 0.1749

379/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9429 - loss: 0.1750

381/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9431 - loss: 0.1747

383/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9430 - loss: 0.1749

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9429 - loss: 0.1749

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9429 - loss: 0.1746

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9429 - loss: 0.1746

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9431 - loss: 0.1742

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9432 - loss: 0.1739

395/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9434 - loss: 0.1733

397/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9435 - loss: 0.1736

399/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9435 - loss: 0.1737

401/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9433 - loss: 0.1741

403/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9435 - loss: 0.1735

405/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9437 - loss: 0.1730

407/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9436 - loss: 0.1730

409/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9435 - loss: 0.1735

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9434 - loss: 0.1737

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9433 - loss: 0.1735

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9434 - loss: 0.1732

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9436 - loss: 0.1730

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9435 - loss: 0.1730

421/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9436 - loss: 0.1727

423/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9437 - loss: 0.1736

425/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9437 - loss: 0.1733

427/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9438 - loss: 0.1731

429/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9438 - loss: 0.1728

431/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9438 - loss: 0.1725

433/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9440 - loss: 0.1721

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9440 - loss: 0.1719

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9440 - loss: 0.1720

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9443 - loss: 0.1715

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9444 - loss: 0.1711

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9442 - loss: 0.1717

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9441 - loss: 0.1724

447/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9443 - loss: 0.1720

449/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9444 - loss: 0.1717

451/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9444 - loss: 0.1718

453/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9444 - loss: 0.1722

455/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9445 - loss: 0.1719

457/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9445 - loss: 0.1718

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9445 - loss: 0.1717

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9445 - loss: 0.1716

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9444 - loss: 0.1722

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9445 - loss: 0.1720

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9444 - loss: 0.1722

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9443 - loss: 0.1721

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9445 - loss: 0.1717

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9446 - loss: 0.1715

475/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9443 - loss: 0.1718

477/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9445 - loss: 0.1715

479/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9445 - loss: 0.1718

481/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9445 - loss: 0.1714

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9447 - loss: 0.1710

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9447 - loss: 0.1708

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9446 - loss: 0.1707

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9446 - loss: 0.1707

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9445 - loss: 0.1709

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9445 - loss: 0.1706

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9445 - loss: 0.1704

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9444 - loss: 0.1705

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9443 - loss: 0.1705

501/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9443 - loss: 0.1707

503/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9442 - loss: 0.1707

505/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9442 - loss: 0.1710

507/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9443 - loss: 0.1709

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9444 - loss: 0.1709

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9443 - loss: 0.1710

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9444 - loss: 0.1709

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9444 - loss: 0.1710

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9443 - loss: 0.1708

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9443 - loss: 0.1706

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9444 - loss: 0.1705

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9443 - loss: 0.1705

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9444 - loss: 0.1702

527/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9446 - loss: 0.1702

529/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9446 - loss: 0.1699

531/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9447 - loss: 0.1703

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9445 - loss: 0.1704

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9445 - loss: 0.1705

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9444 - loss: 0.1705

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9445 - loss: 0.1703

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9444 - loss: 0.1703

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9445 - loss: 0.1704

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9444 - loss: 0.1703

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9445 - loss: 0.1702

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9444 - loss: 0.1702

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9443 - loss: 0.1704

553/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9442 - loss: 0.1706

555/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9443 - loss: 0.1704

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9443 - loss: 0.1701

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9444 - loss: 0.1699

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9444 - loss: 0.1699

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9444 - loss: 0.1696

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9444 - loss: 0.1695

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9444 - loss: 0.1697

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9445 - loss: 0.1694

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9446 - loss: 0.1691

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9446 - loss: 0.1689

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9447 - loss: 0.1687

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9447 - loss: 0.1686

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9449 - loss: 0.1681

581/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9450 - loss: 0.1678

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9450 - loss: 0.1678

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9450 - loss: 0.1676

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9451 - loss: 0.1675

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9452 - loss: 0.1673

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9453 - loss: 0.1672

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9454 - loss: 0.1670

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9454 - loss: 0.1669

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9454 - loss: 0.1669

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9454 - loss: 0.1668

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9454 - loss: 0.1668

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9454 - loss: 0.1667

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9452 - loss: 0.1668

606/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9453 - loss: 0.1666 - val_accuracy: 0.9438 - val_loss: 0.2290

Epoch 5/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.9375 - loss: 0.0983

  3/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9583 - loss: 0.0984

  5/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9563 - loss: 0.1246

  7/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9598 - loss: 0.1175

  9/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9653 - loss: 0.1018

 11/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9631 - loss: 0.1055

 13/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9639 - loss: 0.0982

 15/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9625 - loss: 0.0979

 17/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9632 - loss: 0.0973

 19/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9638 - loss: 0.1015

 21/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9643 - loss: 0.1017

 23/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9620 - loss: 0.1074

 25/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9625 - loss: 0.1054

 27/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9606 - loss: 0.1156

 29/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9601 - loss: 0.1159

 31/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9587 - loss: 0.1315

 33/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9583 - loss: 0.1349

 35/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9571 - loss: 0.1357

 37/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9569 - loss: 0.1335

 39/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9559 - loss: 0.1419

 41/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9558 - loss: 0.1457

 43/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9542 - loss: 0.1468

 45/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9542 - loss: 0.1502

 47/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9548 - loss: 0.1474

 49/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9528 - loss: 0.1547

 51/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9498 - loss: 0.1582

 53/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9499 - loss: 0.1564

 55/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9506 - loss: 0.1557

 57/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9485 - loss: 0.1580

 59/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9497 - loss: 0.1546

 61/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9513 - loss: 0.1511

 63/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9524 - loss: 0.1496

 65/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9519 - loss: 0.1504

 67/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9529 - loss: 0.1542

 69/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9538 - loss: 0.1515

 71/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9529 - loss: 0.1583

 73/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9516 - loss: 0.1591

 75/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9521 - loss: 0.1575

 77/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9525 - loss: 0.1574

 79/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9517 - loss: 0.1580

 81/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9502 - loss: 0.1601

 83/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9499 - loss: 0.1585

 85/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9500 - loss: 0.1590

 87/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9504 - loss: 0.1578

 89/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9508 - loss: 0.1564

 91/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9505 - loss: 0.1574

 93/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9509 - loss: 0.1566

 95/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9513 - loss: 0.1556

 97/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9510 - loss: 0.1561

 99/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9498 - loss: 0.1572

101/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9496 - loss: 0.1563

103/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9493 - loss: 0.1567

105/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9497 - loss: 0.1557

107/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9501 - loss: 0.1549

109/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9501 - loss: 0.1552

111/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9499 - loss: 0.1560

113/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9499 - loss: 0.1584

115/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9500 - loss: 0.1585

117/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9498 - loss: 0.1584

119/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9498 - loss: 0.1574

121/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9494 - loss: 0.1572

123/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9492 - loss: 0.1576

125/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9490 - loss: 0.1600

127/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9496 - loss: 0.1590

129/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9496 - loss: 0.1581

131/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9490 - loss: 0.1589

133/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9481 - loss: 0.1609

135/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9479 - loss: 0.1610

137/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9478 - loss: 0.1608

139/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9481 - loss: 0.1606

141/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9475 - loss: 0.1631

143/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9476 - loss: 0.1637

145/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9476 - loss: 0.1636

147/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9479 - loss: 0.1629

149/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9482 - loss: 0.1621

151/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9485 - loss: 0.1614

153/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9487 - loss: 0.1606

155/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9490 - loss: 0.1598

157/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9482 - loss: 0.1618

159/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9479 - loss: 0.1625

161/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9484 - loss: 0.1612

163/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9480 - loss: 0.1637

165/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9475 - loss: 0.1644

167/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9476 - loss: 0.1642

169/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9462 - loss: 0.1682

171/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9466 - loss: 0.1670

173/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9467 - loss: 0.1665

175/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9463 - loss: 0.1675

177/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9467 - loss: 0.1678

179/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9466 - loss: 0.1672

181/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9465 - loss: 0.1674

183/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9466 - loss: 0.1671

185/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9466 - loss: 0.1669

187/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9462 - loss: 0.1686

189/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9459 - loss: 0.1686

191/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9455 - loss: 0.1690

193/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9458 - loss: 0.1682

195/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9462 - loss: 0.1674

197/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9461 - loss: 0.1679

199/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9463 - loss: 0.1675

201/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9461 - loss: 0.1682

203/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9464 - loss: 0.1673

205/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9463 - loss: 0.1672

207/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9467 - loss: 0.1675

209/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9463 - loss: 0.1683

211/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9468 - loss: 0.1672

213/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9467 - loss: 0.1673

215/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9465 - loss: 0.1682

217/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9464 - loss: 0.1690

219/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9465 - loss: 0.1684

221/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9465 - loss: 0.1683

223/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9465 - loss: 0.1680

225/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9465 - loss: 0.1677

227/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9463 - loss: 0.1688

229/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9466 - loss: 0.1682

231/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9470 - loss: 0.1675

233/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9470 - loss: 0.1669

235/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9467 - loss: 0.1669

237/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9467 - loss: 0.1665

239/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9469 - loss: 0.1659

241/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9470 - loss: 0.1667

243/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9465 - loss: 0.1674

245/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9467 - loss: 0.1671

247/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9469 - loss: 0.1667

249/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9470 - loss: 0.1663

251/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9468 - loss: 0.1669

253/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9468 - loss: 0.1667

255/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9463 - loss: 0.1676

257/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9460 - loss: 0.1676

259/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9462 - loss: 0.1673

261/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9464 - loss: 0.1668

263/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9465 - loss: 0.1662

265/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9465 - loss: 0.1659

267/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9466 - loss: 0.1660

269/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9468 - loss: 0.1655

271/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9466 - loss: 0.1655

273/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9464 - loss: 0.1656

275/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9464 - loss: 0.1653

277/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9464 - loss: 0.1652

279/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9462 - loss: 0.1660

281/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9461 - loss: 0.1673

283/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9461 - loss: 0.1670

285/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9462 - loss: 0.1676

287/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9458 - loss: 0.1678

289/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9457 - loss: 0.1681

291/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9452 - loss: 0.1700

293/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9454 - loss: 0.1698

295/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9456 - loss: 0.1692

297/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9452 - loss: 0.1696

299/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9451 - loss: 0.1693

301/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9451 - loss: 0.1689

303/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9449 - loss: 0.1693

305/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9451 - loss: 0.1689

307/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9450 - loss: 0.1695

309/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9452 - loss: 0.1691

311/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9450 - loss: 0.1699

313/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9451 - loss: 0.1695

315/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9453 - loss: 0.1697

317/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9456 - loss: 0.1692

319/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9456 - loss: 0.1690

321/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9455 - loss: 0.1691

323/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9452 - loss: 0.1692

325/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9452 - loss: 0.1694

327/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9455 - loss: 0.1686

329/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9459 - loss: 0.1679

331/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9460 - loss: 0.1677

333/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9461 - loss: 0.1684

335/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9464 - loss: 0.1679

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9463 - loss: 0.1676

339/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9462 - loss: 0.1679

341/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9463 - loss: 0.1676

343/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9465 - loss: 0.1668

345/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9463 - loss: 0.1673

347/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9464 - loss: 0.1668

349/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9462 - loss: 0.1669

351/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9463 - loss: 0.1672

353/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9462 - loss: 0.1673

355/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9461 - loss: 0.1672

357/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9463 - loss: 0.1667

359/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9465 - loss: 0.1664

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9467 - loss: 0.1658

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9466 - loss: 0.1669

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9465 - loss: 0.1668

367/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9465 - loss: 0.1679

369/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9462 - loss: 0.1683

371/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9460 - loss: 0.1697

373/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9461 - loss: 0.1693

375/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9458 - loss: 0.1697

377/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9459 - loss: 0.1694

379/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9459 - loss: 0.1693

381/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9460 - loss: 0.1688

383/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9459 - loss: 0.1692

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9461 - loss: 0.1689

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9458 - loss: 0.1692

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9460 - loss: 0.1687

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9461 - loss: 0.1684

393/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9460 - loss: 0.1684

395/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9459 - loss: 0.1685

397/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9460 - loss: 0.1682

399/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9463 - loss: 0.1676

401/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9463 - loss: 0.1678

403/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9465 - loss: 0.1674

405/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9465 - loss: 0.1681

407/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9463 - loss: 0.1683

409/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9461 - loss: 0.1686

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9460 - loss: 0.1689

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9461 - loss: 0.1687

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9461 - loss: 0.1685

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9462 - loss: 0.1681

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9463 - loss: 0.1678

421/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9465 - loss: 0.1674

423/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9461 - loss: 0.1690

425/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9460 - loss: 0.1688

427/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9462 - loss: 0.1684

429/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9463 - loss: 0.1681

431/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9466 - loss: 0.1676

433/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9467 - loss: 0.1675

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9468 - loss: 0.1671

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9467 - loss: 0.1671

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9465 - loss: 0.1680

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9465 - loss: 0.1680

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9467 - loss: 0.1676

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9469 - loss: 0.1671

447/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9468 - loss: 0.1673

449/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9467 - loss: 0.1672

451/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9464 - loss: 0.1688

453/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9466 - loss: 0.1685

455/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9468 - loss: 0.1681

457/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9470 - loss: 0.1677

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9472 - loss: 0.1673

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9471 - loss: 0.1676

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9469 - loss: 0.1678

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9471 - loss: 0.1674

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9471 - loss: 0.1673

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9470 - loss: 0.1672

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9470 - loss: 0.1674

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9470 - loss: 0.1673

475/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9470 - loss: 0.1670

477/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9468 - loss: 0.1673

479/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9469 - loss: 0.1671

481/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9469 - loss: 0.1668

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9469 - loss: 0.1667

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9470 - loss: 0.1664

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9470 - loss: 0.1662

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9470 - loss: 0.1662

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9470 - loss: 0.1664

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9469 - loss: 0.1664

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9468 - loss: 0.1667

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9467 - loss: 0.1668

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9466 - loss: 0.1667

501/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9467 - loss: 0.1664

503/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9468 - loss: 0.1660

505/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9467 - loss: 0.1662

507/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9467 - loss: 0.1664

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9470 - loss: 0.1658

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9470 - loss: 0.1661

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9470 - loss: 0.1659

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9470 - loss: 0.1662

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9469 - loss: 0.1663

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9471 - loss: 0.1660

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9472 - loss: 0.1659

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9472 - loss: 0.1658

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9472 - loss: 0.1657

527/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9473 - loss: 0.1654

529/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9474 - loss: 0.1652

531/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9476 - loss: 0.1648

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9474 - loss: 0.1652

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9474 - loss: 0.1650

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9474 - loss: 0.1650

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9475 - loss: 0.1648

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9474 - loss: 0.1647

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9472 - loss: 0.1655

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9474 - loss: 0.1651

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9474 - loss: 0.1651

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9470 - loss: 0.1657

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9469 - loss: 0.1658

553/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9469 - loss: 0.1656

555/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9469 - loss: 0.1654

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9470 - loss: 0.1650

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9472 - loss: 0.1646

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9471 - loss: 0.1648

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9472 - loss: 0.1650

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9473 - loss: 0.1647

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9474 - loss: 0.1645

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9474 - loss: 0.1644

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9475 - loss: 0.1641

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9475 - loss: 0.1640

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9473 - loss: 0.1643

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9473 - loss: 0.1643

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9474 - loss: 0.1640

581/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9473 - loss: 0.1641

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9475 - loss: 0.1638

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9475 - loss: 0.1638

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9475 - loss: 0.1638

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9476 - loss: 0.1636

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9477 - loss: 0.1633

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9476 - loss: 0.1634

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9477 - loss: 0.1632

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9477 - loss: 0.1632

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9478 - loss: 0.1629

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9479 - loss: 0.1625

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9479 - loss: 0.1626

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9479 - loss: 0.1625

606/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9480 - loss: 0.1624 - val_accuracy: 0.9523 - val_loss: 0.1905

Epoch 6/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 1.0000 - loss: 0.0651

  3/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9896 - loss: 0.0697

  5/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9875 - loss: 0.0645

  7/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9866 - loss: 0.0661

  9/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9826 - loss: 0.0695

 11/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9801 - loss: 0.0718

 13/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9736 - loss: 0.0890

 15/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9708 - loss: 0.0924

 17/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9669 - loss: 0.0982

 19/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9622 - loss: 0.1256

 21/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9598 - loss: 0.1290

 23/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9606 - loss: 0.1295

 25/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9625 - loss: 0.1229

 27/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9641 - loss: 0.1203

 29/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9634 - loss: 0.1216

 31/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9617 - loss: 0.1348

 33/606 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.9621 - loss: 0.1357

 35/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9616 - loss: 0.1362

 37/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9603 - loss: 0.1385

 39/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9591 - loss: 0.1416

 41/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9566 - loss: 0.1486

 43/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9571 - loss: 0.1464

 45/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9556 - loss: 0.1525

 47/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9574 - loss: 0.1475

 49/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9566 - loss: 0.1502

 51/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9553 - loss: 0.1512

 53/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9552 - loss: 0.1491

 55/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9557 - loss: 0.1461

 57/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9567 - loss: 0.1435

 59/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9571 - loss: 0.1426

 61/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9565 - loss: 0.1443

 63/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9559 - loss: 0.1448

 65/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9563 - loss: 0.1471

 67/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9562 - loss: 0.1459

 69/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9565 - loss: 0.1501

 71/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9573 - loss: 0.1480

 73/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9572 - loss: 0.1471

 75/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9567 - loss: 0.1476

 77/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9562 - loss: 0.1492

 79/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9549 - loss: 0.1509

 81/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9545 - loss: 0.1499

 83/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9541 - loss: 0.1498

 85/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9533 - loss: 0.1516

 87/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9540 - loss: 0.1504

 89/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9537 - loss: 0.1532

 91/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9547 - loss: 0.1513

 93/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9550 - loss: 0.1507

 95/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9549 - loss: 0.1505

 97/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9552 - loss: 0.1511

 99/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9555 - loss: 0.1502

101/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9548 - loss: 0.1513

103/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9542 - loss: 0.1507

105/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9539 - loss: 0.1504

107/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9527 - loss: 0.1526

109/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9530 - loss: 0.1524

111/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9533 - loss: 0.1527

113/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9535 - loss: 0.1520

115/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9527 - loss: 0.1570

117/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9522 - loss: 0.1574

119/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9517 - loss: 0.1583

121/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9509 - loss: 0.1596

123/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9505 - loss: 0.1596

125/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9500 - loss: 0.1602

127/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9503 - loss: 0.1598

129/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9506 - loss: 0.1586

131/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9511 - loss: 0.1575

133/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9511 - loss: 0.1592

135/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9512 - loss: 0.1590

137/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9510 - loss: 0.1598

139/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9510 - loss: 0.1598

141/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9517 - loss: 0.1585

143/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9519 - loss: 0.1602

145/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9517 - loss: 0.1607

147/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9520 - loss: 0.1615

149/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9520 - loss: 0.1608

151/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9522 - loss: 0.1602

153/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9524 - loss: 0.1601

155/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9522 - loss: 0.1602

157/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9516 - loss: 0.1611

159/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9511 - loss: 0.1621

161/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9509 - loss: 0.1621

163/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9515 - loss: 0.1612

165/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9517 - loss: 0.1608

167/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9519 - loss: 0.1603

169/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9517 - loss: 0.1602

171/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9518 - loss: 0.1597

173/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9512 - loss: 0.1604

175/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9513 - loss: 0.1601

177/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9516 - loss: 0.1592

179/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9513 - loss: 0.1611

181/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9511 - loss: 0.1612

183/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9512 - loss: 0.1606

185/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9512 - loss: 0.1611

187/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9512 - loss: 0.1605

189/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9514 - loss: 0.1613

191/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9506 - loss: 0.1643

193/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9501 - loss: 0.1646

195/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9502 - loss: 0.1643

197/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9505 - loss: 0.1633

199/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9501 - loss: 0.1635

201/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9501 - loss: 0.1630

203/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9501 - loss: 0.1625

205/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9500 - loss: 0.1623

207/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9499 - loss: 0.1624

209/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9504 - loss: 0.1613

211/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9502 - loss: 0.1613

213/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9507 - loss: 0.1604

215/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9504 - loss: 0.1610

217/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9500 - loss: 0.1617

219/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9493 - loss: 0.1645

221/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9492 - loss: 0.1653

223/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9494 - loss: 0.1648

225/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9494 - loss: 0.1651

227/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9495 - loss: 0.1652

229/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9496 - loss: 0.1649

231/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9494 - loss: 0.1655

233/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9489 - loss: 0.1667

235/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9488 - loss: 0.1670

237/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9486 - loss: 0.1673

239/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9486 - loss: 0.1672

241/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9484 - loss: 0.1672

243/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9486 - loss: 0.1666

245/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9489 - loss: 0.1659

247/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9490 - loss: 0.1652

249/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9490 - loss: 0.1649

251/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9492 - loss: 0.1643

253/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9492 - loss: 0.1641

255/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9490 - loss: 0.1652

257/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9489 - loss: 0.1647

259/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9491 - loss: 0.1653

261/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9490 - loss: 0.1655

263/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9490 - loss: 0.1652

265/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9492 - loss: 0.1655

267/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9490 - loss: 0.1659

269/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9490 - loss: 0.1655

271/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9489 - loss: 0.1656

273/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9487 - loss: 0.1663

275/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9482 - loss: 0.1667

277/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9482 - loss: 0.1664

279/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9479 - loss: 0.1667

281/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9474 - loss: 0.1682

283/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9475 - loss: 0.1678

285/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9477 - loss: 0.1677

287/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9477 - loss: 0.1675

289/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9474 - loss: 0.1689

291/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9473 - loss: 0.1702

293/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9471 - loss: 0.1704

295/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9474 - loss: 0.1701

297/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9473 - loss: 0.1699

299/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9475 - loss: 0.1692

301/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9474 - loss: 0.1692

303/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9473 - loss: 0.1691

305/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9471 - loss: 0.1696

307/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9475 - loss: 0.1690

309/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9476 - loss: 0.1686

311/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9480 - loss: 0.1678

313/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9479 - loss: 0.1679

315/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9481 - loss: 0.1674

317/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9482 - loss: 0.1672

319/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9481 - loss: 0.1670

321/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9481 - loss: 0.1667

323/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9480 - loss: 0.1665

325/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9484 - loss: 0.1659

327/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9485 - loss: 0.1655

329/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9486 - loss: 0.1653

331/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9486 - loss: 0.1666

333/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9486 - loss: 0.1683

335/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9486 - loss: 0.1680

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9487 - loss: 0.1677

339/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9489 - loss: 0.1672

341/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9489 - loss: 0.1671

343/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9485 - loss: 0.1677

345/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9485 - loss: 0.1676

347/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9483 - loss: 0.1678

349/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9482 - loss: 0.1678

351/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9482 - loss: 0.1682

353/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9483 - loss: 0.1677

355/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9483 - loss: 0.1674

357/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9482 - loss: 0.1675

359/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9481 - loss: 0.1677

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9483 - loss: 0.1673

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9485 - loss: 0.1668

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9483 - loss: 0.1671

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9478 - loss: 0.1679

369/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9476 - loss: 0.1689

371/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9476 - loss: 0.1699

373/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9479 - loss: 0.1695

375/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9482 - loss: 0.1687

377/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9480 - loss: 0.1687

379/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9479 - loss: 0.1687

381/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9479 - loss: 0.1684

383/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9479 - loss: 0.1682

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9479 - loss: 0.1687

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9479 - loss: 0.1685

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9478 - loss: 0.1687

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9480 - loss: 0.1681

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9481 - loss: 0.1677

395/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9479 - loss: 0.1681

397/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9481 - loss: 0.1676

399/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9482 - loss: 0.1673

401/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9482 - loss: 0.1672

403/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9482 - loss: 0.1672

405/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9483 - loss: 0.1670

407/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9485 - loss: 0.1665

409/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9486 - loss: 0.1663

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9487 - loss: 0.1667

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9486 - loss: 0.1665

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9485 - loss: 0.1666

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9484 - loss: 0.1665

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9485 - loss: 0.1669

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9483 - loss: 0.1668

423/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9484 - loss: 0.1666

425/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9482 - loss: 0.1667

427/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9483 - loss: 0.1663

429/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9483 - loss: 0.1660

431/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9484 - loss: 0.1655

433/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9485 - loss: 0.1656

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9485 - loss: 0.1654

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9487 - loss: 0.1651

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9487 - loss: 0.1649

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9486 - loss: 0.1652

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9488 - loss: 0.1650

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9488 - loss: 0.1652

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9489 - loss: 0.1650

449/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9487 - loss: 0.1653

451/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9488 - loss: 0.1651

453/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9487 - loss: 0.1653

455/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9486 - loss: 0.1661

457/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9488 - loss: 0.1657

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9484 - loss: 0.1666

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9485 - loss: 0.1665

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9486 - loss: 0.1662

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9486 - loss: 0.1661

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9485 - loss: 0.1661

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9484 - loss: 0.1662

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9484 - loss: 0.1660

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9486 - loss: 0.1656

475/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9486 - loss: 0.1655

477/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9487 - loss: 0.1652

479/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9487 - loss: 0.1651

481/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9487 - loss: 0.1650

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9488 - loss: 0.1647

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9488 - loss: 0.1647

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9489 - loss: 0.1644

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9487 - loss: 0.1647

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9485 - loss: 0.1652

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9485 - loss: 0.1653

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9482 - loss: 0.1657

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9482 - loss: 0.1657

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9483 - loss: 0.1655

501/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9485 - loss: 0.1651

503/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9483 - loss: 0.1654

505/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9484 - loss: 0.1651

507/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9483 - loss: 0.1650

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9483 - loss: 0.1655

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9481 - loss: 0.1660

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9481 - loss: 0.1659

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9483 - loss: 0.1655

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9480 - loss: 0.1658

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9482 - loss: 0.1654

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9482 - loss: 0.1655

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9482 - loss: 0.1655

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9484 - loss: 0.1650

527/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9484 - loss: 0.1650

529/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9484 - loss: 0.1649

531/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9483 - loss: 0.1649

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9483 - loss: 0.1653

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9483 - loss: 0.1651

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9483 - loss: 0.1650

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9482 - loss: 0.1650

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9483 - loss: 0.1647

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9484 - loss: 0.1643

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9485 - loss: 0.1640

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9485 - loss: 0.1641

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9484 - loss: 0.1644

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9483 - loss: 0.1645

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9483 - loss: 0.1644

555/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9482 - loss: 0.1645

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9481 - loss: 0.1644

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9481 - loss: 0.1642

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9481 - loss: 0.1642

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9481 - loss: 0.1641

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9482 - loss: 0.1636

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9482 - loss: 0.1636

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9482 - loss: 0.1637

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9482 - loss: 0.1635

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9483 - loss: 0.1634

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9484 - loss: 0.1631

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9484 - loss: 0.1631

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9484 - loss: 0.1631

581/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9484 - loss: 0.1633

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9485 - loss: 0.1629

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9486 - loss: 0.1627

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9487 - loss: 0.1622

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9487 - loss: 0.1621

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9487 - loss: 0.1622

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9488 - loss: 0.1617

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9489 - loss: 0.1616

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9490 - loss: 0.1615

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9490 - loss: 0.1612

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9489 - loss: 0.1614

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9490 - loss: 0.1611

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9489 - loss: 0.1610

606/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9488 - loss: 0.1612 - val_accuracy: 0.9506 - val_loss: 0.2055

Epoch 7/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.9688 - loss: 0.0930

  3/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9479 - loss: 0.1133

  5/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9625 - loss: 0.0919

  7/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9643 - loss: 0.1017

  9/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9583 - loss: 0.1095

 11/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9631 - loss: 0.0994

 13/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9688 - loss: 0.0900

 15/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9688 - loss: 0.0860

 17/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9688 - loss: 0.0860

 19/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9704 - loss: 0.0824

 21/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9702 - loss: 0.0816

 23/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9633 - loss: 0.1091

 25/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9600 - loss: 0.1179

 27/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9618 - loss: 0.1160

 29/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9634 - loss: 0.1127

 31/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9617 - loss: 0.1172

 33/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9583 - loss: 0.1345

 35/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9589 - loss: 0.1360

 37/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9603 - loss: 0.1342

 39/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9591 - loss: 0.1356

 41/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9588 - loss: 0.1351

 43/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9586 - loss: 0.1355

 45/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9590 - loss: 0.1321

 47/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9581 - loss: 0.1334

 49/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9585 - loss: 0.1331

 51/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9565 - loss: 0.1382

 53/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9558 - loss: 0.1395

 55/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9551 - loss: 0.1404

 57/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9545 - loss: 0.1438

 59/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9555 - loss: 0.1413

 61/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9549 - loss: 0.1441

 63/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9554 - loss: 0.1438

 65/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9543 - loss: 0.1433

 67/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9548 - loss: 0.1423

 69/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9538 - loss: 0.1446

 71/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9551 - loss: 0.1418

 73/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9546 - loss: 0.1449

 75/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9550 - loss: 0.1452

 77/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9550 - loss: 0.1450

 79/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9549 - loss: 0.1453

 81/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9549 - loss: 0.1474

 83/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9548 - loss: 0.1476

 85/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9537 - loss: 0.1491

 87/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9540 - loss: 0.1476

 89/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9544 - loss: 0.1461

 91/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9543 - loss: 0.1460

 93/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9536 - loss: 0.1461

 95/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9536 - loss: 0.1460

 97/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9530 - loss: 0.1472

 99/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9527 - loss: 0.1474

101/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9533 - loss: 0.1471

103/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9533 - loss: 0.1475

105/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9533 - loss: 0.1469

107/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9536 - loss: 0.1466

109/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9538 - loss: 0.1457

111/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9538 - loss: 0.1486

113/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9541 - loss: 0.1480

115/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9530 - loss: 0.1504

117/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9538 - loss: 0.1484

119/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9538 - loss: 0.1491

121/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9535 - loss: 0.1495

123/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9535 - loss: 0.1491

125/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9535 - loss: 0.1485

127/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9537 - loss: 0.1476

129/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9540 - loss: 0.1470

131/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9537 - loss: 0.1485

133/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9537 - loss: 0.1488

135/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9539 - loss: 0.1485

137/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9532 - loss: 0.1529

139/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9523 - loss: 0.1550

141/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9523 - loss: 0.1548

143/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9519 - loss: 0.1556

145/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9517 - loss: 0.1556

147/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9515 - loss: 0.1555

149/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9513 - loss: 0.1555

151/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9516 - loss: 0.1548

153/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9514 - loss: 0.1553

155/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9514 - loss: 0.1549

157/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9512 - loss: 0.1564

159/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9511 - loss: 0.1571

161/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9507 - loss: 0.1576

163/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9507 - loss: 0.1573

165/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9509 - loss: 0.1564

167/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9506 - loss: 0.1565

169/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9499 - loss: 0.1588

171/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9497 - loss: 0.1597

173/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9494 - loss: 0.1600

175/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9496 - loss: 0.1592

177/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9497 - loss: 0.1586

179/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9497 - loss: 0.1610

181/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9492 - loss: 0.1624

183/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9493 - loss: 0.1616

185/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9493 - loss: 0.1611

187/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9495 - loss: 0.1608

189/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9496 - loss: 0.1602

191/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9498 - loss: 0.1594

193/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9495 - loss: 0.1593

195/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9494 - loss: 0.1597

197/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9499 - loss: 0.1585

199/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9494 - loss: 0.1589

201/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9493 - loss: 0.1589

203/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9490 - loss: 0.1602

205/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9491 - loss: 0.1597

207/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9493 - loss: 0.1591

209/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9496 - loss: 0.1583

211/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9499 - loss: 0.1575

213/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9500 - loss: 0.1592

215/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9490 - loss: 0.1608

217/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9493 - loss: 0.1599

219/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9498 - loss: 0.1588

221/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9495 - loss: 0.1591

223/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9496 - loss: 0.1588

225/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9492 - loss: 0.1599

227/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9493 - loss: 0.1600

229/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9491 - loss: 0.1605

231/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9491 - loss: 0.1606

233/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9493 - loss: 0.1600

235/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9495 - loss: 0.1595

237/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9498 - loss: 0.1589

239/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9495 - loss: 0.1591

241/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9489 - loss: 0.1598

243/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9491 - loss: 0.1592

245/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9494 - loss: 0.1586

247/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9493 - loss: 0.1586

249/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9493 - loss: 0.1583

251/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9493 - loss: 0.1580

253/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9487 - loss: 0.1584

255/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9487 - loss: 0.1585

257/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9489 - loss: 0.1580

259/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9490 - loss: 0.1578

261/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9492 - loss: 0.1572

263/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9490 - loss: 0.1582

265/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9491 - loss: 0.1579

267/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9484 - loss: 0.1600

269/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9480 - loss: 0.1602

271/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9481 - loss: 0.1596

273/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9483 - loss: 0.1594

275/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9484 - loss: 0.1590

277/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9482 - loss: 0.1596

279/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9481 - loss: 0.1603

281/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9480 - loss: 0.1602

283/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9479 - loss: 0.1607

285/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9478 - loss: 0.1614

287/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9476 - loss: 0.1619

289/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9478 - loss: 0.1616

291/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9479 - loss: 0.1618

293/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9481 - loss: 0.1616

295/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9480 - loss: 0.1619

297/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9478 - loss: 0.1622

299/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9480 - loss: 0.1615

301/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9481 - loss: 0.1611

303/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9483 - loss: 0.1606

305/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9484 - loss: 0.1602

307/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9483 - loss: 0.1603

309/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9485 - loss: 0.1603

311/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9487 - loss: 0.1597

313/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9486 - loss: 0.1608

315/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9487 - loss: 0.1602

317/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9486 - loss: 0.1604

319/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9484 - loss: 0.1604

321/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9484 - loss: 0.1603

323/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9483 - loss: 0.1604

325/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9486 - loss: 0.1599

327/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9487 - loss: 0.1594

329/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9489 - loss: 0.1588

331/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9488 - loss: 0.1604

333/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9488 - loss: 0.1602

335/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9488 - loss: 0.1600

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9485 - loss: 0.1614

339/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9485 - loss: 0.1610

341/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9485 - loss: 0.1610

343/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9486 - loss: 0.1605

345/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9486 - loss: 0.1602

347/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9486 - loss: 0.1600

349/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9489 - loss: 0.1594

351/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9487 - loss: 0.1594

353/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9487 - loss: 0.1594

355/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9487 - loss: 0.1593

357/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9487 - loss: 0.1590

359/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9486 - loss: 0.1598

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9488 - loss: 0.1594

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9489 - loss: 0.1593

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9486 - loss: 0.1595

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9486 - loss: 0.1600

369/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9487 - loss: 0.1609

371/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9485 - loss: 0.1611

373/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9484 - loss: 0.1614

375/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9486 - loss: 0.1609

377/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9484 - loss: 0.1610

379/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9486 - loss: 0.1605

381/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9485 - loss: 0.1605

383/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9486 - loss: 0.1602

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9485 - loss: 0.1606

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9486 - loss: 0.1603

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9487 - loss: 0.1601

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9486 - loss: 0.1601

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9486 - loss: 0.1603

395/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9485 - loss: 0.1604

397/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9487 - loss: 0.1600

399/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9485 - loss: 0.1613

401/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9487 - loss: 0.1608

403/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9486 - loss: 0.1612

405/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9487 - loss: 0.1609

407/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9486 - loss: 0.1610

409/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9484 - loss: 0.1613

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9486 - loss: 0.1609

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9483 - loss: 0.1611

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9480 - loss: 0.1622

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9481 - loss: 0.1619

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9482 - loss: 0.1616

421/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9481 - loss: 0.1615

423/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9483 - loss: 0.1610

425/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9482 - loss: 0.1609

427/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9483 - loss: 0.1606

429/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9482 - loss: 0.1607

431/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9482 - loss: 0.1605

433/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9482 - loss: 0.1604

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9483 - loss: 0.1600

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9484 - loss: 0.1597

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9485 - loss: 0.1596

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9484 - loss: 0.1595

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9485 - loss: 0.1594

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9485 - loss: 0.1594

447/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9485 - loss: 0.1595

449/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9486 - loss: 0.1601

451/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9484 - loss: 0.1606

453/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9485 - loss: 0.1604

455/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9486 - loss: 0.1599

457/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9487 - loss: 0.1596

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9487 - loss: 0.1595

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9488 - loss: 0.1595

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9486 - loss: 0.1597

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9486 - loss: 0.1598

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9485 - loss: 0.1595

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9484 - loss: 0.1597

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9484 - loss: 0.1596

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9481 - loss: 0.1601

475/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9482 - loss: 0.1599

477/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9483 - loss: 0.1598

479/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9483 - loss: 0.1598

481/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9484 - loss: 0.1594

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9484 - loss: 0.1593

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9486 - loss: 0.1590

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9487 - loss: 0.1587

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9486 - loss: 0.1588

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9484 - loss: 0.1589

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9485 - loss: 0.1586

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9484 - loss: 0.1584

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9484 - loss: 0.1584

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9483 - loss: 0.1587

501/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9484 - loss: 0.1585

503/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9484 - loss: 0.1583

505/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9485 - loss: 0.1585

507/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9485 - loss: 0.1587

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9487 - loss: 0.1583

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9488 - loss: 0.1580

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9488 - loss: 0.1579

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9487 - loss: 0.1582

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9486 - loss: 0.1585

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9486 - loss: 0.1584

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9487 - loss: 0.1584

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9487 - loss: 0.1584

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9488 - loss: 0.1582

527/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9486 - loss: 0.1584

529/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9487 - loss: 0.1584

531/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9485 - loss: 0.1585

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9485 - loss: 0.1583

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9487 - loss: 0.1579

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9486 - loss: 0.1578

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9487 - loss: 0.1576

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9489 - loss: 0.1573

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9488 - loss: 0.1576

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9487 - loss: 0.1585

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9486 - loss: 0.1584

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9486 - loss: 0.1586

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9485 - loss: 0.1587

553/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9485 - loss: 0.1585

555/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9485 - loss: 0.1583

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9487 - loss: 0.1579

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9486 - loss: 0.1580

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9487 - loss: 0.1578

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9485 - loss: 0.1582

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9485 - loss: 0.1581

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9486 - loss: 0.1579

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9487 - loss: 0.1577

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9487 - loss: 0.1576

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9489 - loss: 0.1572

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9489 - loss: 0.1571

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9490 - loss: 0.1571

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9489 - loss: 0.1571

581/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9490 - loss: 0.1569

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9490 - loss: 0.1568

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9488 - loss: 0.1571

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9488 - loss: 0.1570

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9489 - loss: 0.1568

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9489 - loss: 0.1567

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9490 - loss: 0.1566

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9488 - loss: 0.1567

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9490 - loss: 0.1564

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9491 - loss: 0.1561

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9491 - loss: 0.1561

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9491 - loss: 0.1560

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9492 - loss: 0.1557

606/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9491 - loss: 0.1557 - val_accuracy: 0.9627 - val_loss: 0.1387

Epoch 8/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 1.0000 - loss: 0.0434

  3/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9792 - loss: 0.0618

  5/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9750 - loss: 0.0751

  7/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9688 - loss: 0.0848

  9/606 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - accuracy: 0.9722 - loss: 0.0759

 11/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9744 - loss: 0.0732

 13/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9760 - loss: 0.0715

 15/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9729 - loss: 0.0752

 17/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9706 - loss: 0.0785

 19/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9671 - loss: 0.0872

 21/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9658 - loss: 0.0923

 23/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9633 - loss: 0.1018

 25/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9613 - loss: 0.1179

 27/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9595 - loss: 0.1235

 29/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9558 - loss: 0.1331

 31/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9577 - loss: 0.1298

 33/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9574 - loss: 0.1305

 35/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9554 - loss: 0.1334

 37/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9535 - loss: 0.1376

 39/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9527 - loss: 0.1382

 41/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9527 - loss: 0.1391

 43/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9528 - loss: 0.1388

 45/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9535 - loss: 0.1377

 47/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9541 - loss: 0.1346

 49/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9541 - loss: 0.1344

 51/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9522 - loss: 0.1369

 53/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9528 - loss: 0.1389

 55/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9528 - loss: 0.1381

 57/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9529 - loss: 0.1368

 59/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9529 - loss: 0.1404

 61/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9534 - loss: 0.1386

 63/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9534 - loss: 0.1378

 65/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9529 - loss: 0.1404

 67/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9524 - loss: 0.1407

 69/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9529 - loss: 0.1430

 71/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9538 - loss: 0.1412

 73/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9551 - loss: 0.1390

 75/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9538 - loss: 0.1438

 77/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9537 - loss: 0.1429

 79/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9533 - loss: 0.1435

 81/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9525 - loss: 0.1445

 83/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9526 - loss: 0.1443

 85/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9522 - loss: 0.1440

 87/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9508 - loss: 0.1471

 89/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9508 - loss: 0.1469

 91/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9519 - loss: 0.1453

 93/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9519 - loss: 0.1455

 95/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9526 - loss: 0.1440

 97/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9536 - loss: 0.1416

 99/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9539 - loss: 0.1405

101/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9527 - loss: 0.1424

103/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9533 - loss: 0.1417

105/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9536 - loss: 0.1415

107/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9530 - loss: 0.1425

109/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9527 - loss: 0.1467

111/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9527 - loss: 0.1470

113/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9530 - loss: 0.1465

115/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9527 - loss: 0.1490

117/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9530 - loss: 0.1482

119/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9530 - loss: 0.1489

121/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9517 - loss: 0.1516

123/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9515 - loss: 0.1512

125/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9520 - loss: 0.1500

127/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9520 - loss: 0.1490

129/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9518 - loss: 0.1502

131/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9523 - loss: 0.1498

133/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9521 - loss: 0.1516

135/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9512 - loss: 0.1536

137/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9512 - loss: 0.1530

139/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9512 - loss: 0.1528

141/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9510 - loss: 0.1524

143/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9510 - loss: 0.1522

145/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9513 - loss: 0.1524

147/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9517 - loss: 0.1515

149/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9520 - loss: 0.1508

151/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9526 - loss: 0.1494

153/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9524 - loss: 0.1494

155/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9528 - loss: 0.1483

157/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9520 - loss: 0.1500

159/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9517 - loss: 0.1508

161/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9517 - loss: 0.1505

163/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9519 - loss: 0.1498

165/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9513 - loss: 0.1521

167/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9515 - loss: 0.1517

169/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9514 - loss: 0.1525

171/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9508 - loss: 0.1533

173/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9505 - loss: 0.1544

175/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9505 - loss: 0.1541

177/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9500 - loss: 0.1549

179/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9497 - loss: 0.1561

181/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9499 - loss: 0.1555

183/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9500 - loss: 0.1551

185/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9497 - loss: 0.1552

187/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9500 - loss: 0.1541

189/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9499 - loss: 0.1540

191/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9496 - loss: 0.1558

193/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9496 - loss: 0.1562

195/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9497 - loss: 0.1556

197/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9496 - loss: 0.1554

199/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9496 - loss: 0.1552

201/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9496 - loss: 0.1548

203/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9500 - loss: 0.1538

205/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9497 - loss: 0.1536

207/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9496 - loss: 0.1536

209/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9499 - loss: 0.1530

211/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9498 - loss: 0.1538

213/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9498 - loss: 0.1536

215/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9499 - loss: 0.1536

217/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9496 - loss: 0.1539

219/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9498 - loss: 0.1533

221/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9498 - loss: 0.1547

223/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9500 - loss: 0.1546

225/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9503 - loss: 0.1537

227/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9504 - loss: 0.1533

229/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9501 - loss: 0.1543

231/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9499 - loss: 0.1548

233/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9498 - loss: 0.1548

235/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9497 - loss: 0.1549

237/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9494 - loss: 0.1556

239/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9494 - loss: 0.1553

241/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9496 - loss: 0.1546

243/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9500 - loss: 0.1538

245/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9495 - loss: 0.1548

247/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9494 - loss: 0.1547

249/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9497 - loss: 0.1540

251/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9492 - loss: 0.1548

253/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9494 - loss: 0.1543

255/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9496 - loss: 0.1537

257/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9498 - loss: 0.1533

259/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9494 - loss: 0.1538

261/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9495 - loss: 0.1533

263/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9495 - loss: 0.1533

265/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9499 - loss: 0.1524

267/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9500 - loss: 0.1518

269/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9498 - loss: 0.1529

271/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9501 - loss: 0.1521

273/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9501 - loss: 0.1524

275/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9499 - loss: 0.1539

277/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9500 - loss: 0.1539

279/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9503 - loss: 0.1535

281/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9500 - loss: 0.1543

283/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9499 - loss: 0.1544

285/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9499 - loss: 0.1551

287/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9495 - loss: 0.1557

289/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9492 - loss: 0.1565

291/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9492 - loss: 0.1565

293/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9492 - loss: 0.1565

295/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9492 - loss: 0.1565

297/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9494 - loss: 0.1562

299/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9490 - loss: 0.1567

301/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9489 - loss: 0.1567

303/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9491 - loss: 0.1563

305/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9491 - loss: 0.1562

307/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9494 - loss: 0.1554

309/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9493 - loss: 0.1554

311/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9494 - loss: 0.1560

313/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9496 - loss: 0.1555

315/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9498 - loss: 0.1549

317/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9499 - loss: 0.1547

319/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9500 - loss: 0.1545

321/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9501 - loss: 0.1547

323/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9502 - loss: 0.1543

325/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9505 - loss: 0.1536

327/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9506 - loss: 0.1533

329/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9505 - loss: 0.1533

331/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9505 - loss: 0.1533

333/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9505 - loss: 0.1537

335/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9507 - loss: 0.1533

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9509 - loss: 0.1531

339/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9507 - loss: 0.1535

341/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9503 - loss: 0.1550

343/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9503 - loss: 0.1550

345/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9502 - loss: 0.1550

347/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9504 - loss: 0.1545

349/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9503 - loss: 0.1557

351/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9506 - loss: 0.1553

353/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9503 - loss: 0.1555

355/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9504 - loss: 0.1553

357/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9504 - loss: 0.1554

359/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9505 - loss: 0.1556

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9507 - loss: 0.1551

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9508 - loss: 0.1546

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9509 - loss: 0.1544

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9508 - loss: 0.1554

369/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9507 - loss: 0.1553

371/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9506 - loss: 0.1556

373/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9506 - loss: 0.1556

375/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9506 - loss: 0.1553

377/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9503 - loss: 0.1554

379/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9501 - loss: 0.1556

381/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9500 - loss: 0.1560

383/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9502 - loss: 0.1556

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9502 - loss: 0.1556

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9501 - loss: 0.1556

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9500 - loss: 0.1559

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9500 - loss: 0.1558

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9501 - loss: 0.1553

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9502 - loss: 0.1551

397/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9503 - loss: 0.1551

399/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9500 - loss: 0.1553

401/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9500 - loss: 0.1552

403/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9501 - loss: 0.1549

405/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9501 - loss: 0.1549

407/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9502 - loss: 0.1548

409/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9501 - loss: 0.1553

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9501 - loss: 0.1552

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9502 - loss: 0.1552

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9502 - loss: 0.1551

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9502 - loss: 0.1549

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9503 - loss: 0.1548

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9503 - loss: 0.1544

423/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9504 - loss: 0.1546

425/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9504 - loss: 0.1543

427/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9505 - loss: 0.1540

429/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9505 - loss: 0.1537

431/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9506 - loss: 0.1534

433/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9507 - loss: 0.1532

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9507 - loss: 0.1530

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9506 - loss: 0.1531

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9506 - loss: 0.1529

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9507 - loss: 0.1528

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9505 - loss: 0.1536

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9505 - loss: 0.1534

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9507 - loss: 0.1529

449/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9505 - loss: 0.1541

451/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9506 - loss: 0.1540

453/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9507 - loss: 0.1539

455/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9507 - loss: 0.1537

457/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9508 - loss: 0.1532

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9508 - loss: 0.1530

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9508 - loss: 0.1533

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9507 - loss: 0.1536

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9507 - loss: 0.1540

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9508 - loss: 0.1538

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9507 - loss: 0.1537

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9508 - loss: 0.1534

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9507 - loss: 0.1534

475/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9507 - loss: 0.1538

477/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9507 - loss: 0.1536

479/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9507 - loss: 0.1536

481/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9508 - loss: 0.1533

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9508 - loss: 0.1532

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9508 - loss: 0.1532

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9509 - loss: 0.1529

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9509 - loss: 0.1527

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9509 - loss: 0.1527

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9507 - loss: 0.1530

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9504 - loss: 0.1533

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9505 - loss: 0.1533

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9505 - loss: 0.1530

501/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9505 - loss: 0.1529

503/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9503 - loss: 0.1534

505/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9504 - loss: 0.1532

507/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9506 - loss: 0.1528

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9508 - loss: 0.1525

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9508 - loss: 0.1523

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9509 - loss: 0.1522

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9509 - loss: 0.1523

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9510 - loss: 0.1521

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9509 - loss: 0.1522

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9509 - loss: 0.1523

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9509 - loss: 0.1521

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9510 - loss: 0.1518

527/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9509 - loss: 0.1518

529/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9507 - loss: 0.1520

531/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9506 - loss: 0.1525

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9506 - loss: 0.1526

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9506 - loss: 0.1525

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9506 - loss: 0.1525

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9505 - loss: 0.1526

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9506 - loss: 0.1527

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9504 - loss: 0.1533

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9503 - loss: 0.1532

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9504 - loss: 0.1530

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9504 - loss: 0.1527

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9503 - loss: 0.1527

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9503 - loss: 0.1525

555/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9503 - loss: 0.1527

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9504 - loss: 0.1526

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9504 - loss: 0.1525

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9505 - loss: 0.1521

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9505 - loss: 0.1522

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9505 - loss: 0.1521

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9504 - loss: 0.1523

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9505 - loss: 0.1521

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9504 - loss: 0.1521

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9505 - loss: 0.1520

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9507 - loss: 0.1516

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9506 - loss: 0.1515

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9507 - loss: 0.1513

581/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9507 - loss: 0.1512

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9507 - loss: 0.1512

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9507 - loss: 0.1512

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9508 - loss: 0.1509

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9508 - loss: 0.1507

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9508 - loss: 0.1506

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9509 - loss: 0.1503

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9509 - loss: 0.1501

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9510 - loss: 0.1498

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9510 - loss: 0.1499

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9511 - loss: 0.1496

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9511 - loss: 0.1496

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9511 - loss: 0.1495

606/606 ━━━━━━━━━━━━━━━━━━━━ 26s 42ms/step - accuracy: 0.9511 - loss: 0.1494 - val_accuracy: 0.9530 - val_loss: 0.1775

Epoch 9/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.9688 - loss: 0.0804

  3/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9792 - loss: 0.0613

  5/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9563 - loss: 0.0946

  7/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9688 - loss: 0.0776

  9/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9688 - loss: 0.0774

 11/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9659 - loss: 0.0876

 13/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9663 - loss: 0.0919

 15/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9667 - loss: 0.0893

 17/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9651 - loss: 0.0959

 19/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9622 - loss: 0.0986

 21/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9613 - loss: 0.1039

 23/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9606 - loss: 0.1085

 25/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9600 - loss: 0.1224

 27/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9606 - loss: 0.1185

 29/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9623 - loss: 0.1177

 31/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9617 - loss: 0.1207

 33/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9612 - loss: 0.1203

 35/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9607 - loss: 0.1240

 37/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9603 - loss: 0.1228

 39/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9607 - loss: 0.1213

 41/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9573 - loss: 0.1331

 43/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9578 - loss: 0.1311

 45/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9590 - loss: 0.1276

 47/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9581 - loss: 0.1340

 49/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9573 - loss: 0.1359

 51/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9577 - loss: 0.1336

 53/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9558 - loss: 0.1350

 55/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9540 - loss: 0.1410

 57/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9534 - loss: 0.1400

 59/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9539 - loss: 0.1388

 61/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9549 - loss: 0.1371

 63/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9563 - loss: 0.1347

 65/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9543 - loss: 0.1411

 67/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9548 - loss: 0.1415

 69/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9552 - loss: 0.1405

 71/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9555 - loss: 0.1401

 73/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9563 - loss: 0.1383

 75/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9563 - loss: 0.1402

 77/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9562 - loss: 0.1434

 79/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9553 - loss: 0.1449

 81/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9560 - loss: 0.1431

 83/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9559 - loss: 0.1425

 85/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9548 - loss: 0.1436

 87/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9551 - loss: 0.1433

 89/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9547 - loss: 0.1461

 91/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9543 - loss: 0.1465

 93/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9546 - loss: 0.1451

 95/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9539 - loss: 0.1457

 97/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9543 - loss: 0.1449

 99/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9552 - loss: 0.1429

101/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9558 - loss: 0.1417

103/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9557 - loss: 0.1415

105/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9563 - loss: 0.1414

107/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9562 - loss: 0.1415

109/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9561 - loss: 0.1414

111/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9558 - loss: 0.1444

113/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9549 - loss: 0.1457

115/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9552 - loss: 0.1447

117/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9551 - loss: 0.1476

119/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9546 - loss: 0.1486

121/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9551 - loss: 0.1481

123/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9545 - loss: 0.1480

125/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9540 - loss: 0.1483

127/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9532 - loss: 0.1494

129/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9530 - loss: 0.1502

131/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9532 - loss: 0.1493

133/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9525 - loss: 0.1499

135/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9521 - loss: 0.1542

137/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9519 - loss: 0.1541

139/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9514 - loss: 0.1555

141/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9517 - loss: 0.1549

143/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9510 - loss: 0.1555

145/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9509 - loss: 0.1556

147/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9515 - loss: 0.1543

149/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9509 - loss: 0.1560

151/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9512 - loss: 0.1552

153/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9516 - loss: 0.1538

155/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9518 - loss: 0.1533

157/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9518 - loss: 0.1532

159/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9520 - loss: 0.1536

161/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9519 - loss: 0.1535

163/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9521 - loss: 0.1525

165/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9521 - loss: 0.1527

167/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9515 - loss: 0.1538

169/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9519 - loss: 0.1529

171/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9516 - loss: 0.1531

173/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9520 - loss: 0.1520

175/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9520 - loss: 0.1547

177/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9516 - loss: 0.1558

179/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9515 - loss: 0.1564

181/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9515 - loss: 0.1562

183/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9515 - loss: 0.1559

185/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9512 - loss: 0.1560

187/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9507 - loss: 0.1568

189/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9511 - loss: 0.1568

191/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9506 - loss: 0.1577

193/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9503 - loss: 0.1579

195/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9502 - loss: 0.1576

197/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9500 - loss: 0.1576

199/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9502 - loss: 0.1571

201/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9499 - loss: 0.1572

203/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9503 - loss: 0.1565

205/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9502 - loss: 0.1563

207/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9506 - loss: 0.1553

209/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9505 - loss: 0.1560

211/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9507 - loss: 0.1557

213/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9506 - loss: 0.1557

215/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9506 - loss: 0.1557

217/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9503 - loss: 0.1576

219/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9506 - loss: 0.1570

221/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9505 - loss: 0.1570

223/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9507 - loss: 0.1569

225/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9500 - loss: 0.1575

227/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9502 - loss: 0.1574

229/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9499 - loss: 0.1580

231/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9498 - loss: 0.1582

233/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9498 - loss: 0.1586

235/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9497 - loss: 0.1586

237/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9494 - loss: 0.1585

239/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9495 - loss: 0.1581

241/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9496 - loss: 0.1579

243/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9496 - loss: 0.1574

245/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9494 - loss: 0.1578

247/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9496 - loss: 0.1572

249/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9498 - loss: 0.1566

251/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9498 - loss: 0.1567

253/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9501 - loss: 0.1561

255/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9501 - loss: 0.1558

257/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9503 - loss: 0.1553

259/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9503 - loss: 0.1551

261/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9501 - loss: 0.1550

263/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9501 - loss: 0.1550

265/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9500 - loss: 0.1555

267/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9501 - loss: 0.1553

269/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9503 - loss: 0.1548

271/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9502 - loss: 0.1546

273/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9504 - loss: 0.1542

275/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9502 - loss: 0.1547

277/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9499 - loss: 0.1556

279/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9498 - loss: 0.1556

281/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9498 - loss: 0.1557

283/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9496 - loss: 0.1558

285/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9499 - loss: 0.1556

287/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9499 - loss: 0.1559

289/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9498 - loss: 0.1560

291/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9497 - loss: 0.1562

293/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9494 - loss: 0.1569

295/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9497 - loss: 0.1565

297/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9498 - loss: 0.1559

299/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9498 - loss: 0.1555

301/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9496 - loss: 0.1558

303/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9495 - loss: 0.1560

305/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9494 - loss: 0.1558

307/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9495 - loss: 0.1560

309/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9496 - loss: 0.1555

311/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9500 - loss: 0.1548

313/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9503 - loss: 0.1540

315/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9503 - loss: 0.1538

317/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9500 - loss: 0.1548

319/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9501 - loss: 0.1543

321/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9500 - loss: 0.1543

323/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9499 - loss: 0.1543

325/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9500 - loss: 0.1539

327/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9501 - loss: 0.1536

329/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9501 - loss: 0.1534

331/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9501 - loss: 0.1535

333/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9502 - loss: 0.1532

335/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9502 - loss: 0.1529

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9501 - loss: 0.1532

339/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9500 - loss: 0.1547

341/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9500 - loss: 0.1547

343/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9501 - loss: 0.1542

345/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9500 - loss: 0.1551

347/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9499 - loss: 0.1553

349/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9500 - loss: 0.1550

351/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9501 - loss: 0.1550

353/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9502 - loss: 0.1554

355/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9503 - loss: 0.1551

357/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9501 - loss: 0.1552

359/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9503 - loss: 0.1547

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9502 - loss: 0.1544

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9503 - loss: 0.1541

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9503 - loss: 0.1541

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9500 - loss: 0.1545

369/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9499 - loss: 0.1545

371/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9501 - loss: 0.1554

373/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9499 - loss: 0.1558

375/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9502 - loss: 0.1552

377/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9502 - loss: 0.1550

379/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9500 - loss: 0.1550

381/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9500 - loss: 0.1551

383/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9499 - loss: 0.1550

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9501 - loss: 0.1544

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9503 - loss: 0.1541

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9502 - loss: 0.1541

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9500 - loss: 0.1541

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9501 - loss: 0.1537

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9502 - loss: 0.1537

397/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9504 - loss: 0.1532

399/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9507 - loss: 0.1526

401/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9507 - loss: 0.1524

403/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9506 - loss: 0.1528

405/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9507 - loss: 0.1528

407/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9505 - loss: 0.1537

409/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9506 - loss: 0.1534

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9505 - loss: 0.1534

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9505 - loss: 0.1532

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9503 - loss: 0.1541

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9504 - loss: 0.1540

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9502 - loss: 0.1543

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9503 - loss: 0.1540

423/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9506 - loss: 0.1536

425/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9507 - loss: 0.1535

427/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9507 - loss: 0.1532

429/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9508 - loss: 0.1530

431/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9508 - loss: 0.1528

433/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9506 - loss: 0.1529

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9506 - loss: 0.1529

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9505 - loss: 0.1530

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9506 - loss: 0.1528

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9507 - loss: 0.1526

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9508 - loss: 0.1526

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9509 - loss: 0.1523

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9509 - loss: 0.1523

449/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9508 - loss: 0.1523

451/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9509 - loss: 0.1522

453/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9510 - loss: 0.1525

455/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9510 - loss: 0.1524

457/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9510 - loss: 0.1525

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9509 - loss: 0.1528

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9510 - loss: 0.1526

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9510 - loss: 0.1525

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9510 - loss: 0.1523

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9510 - loss: 0.1523

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9512 - loss: 0.1521

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9512 - loss: 0.1520

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9512 - loss: 0.1520

475/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9511 - loss: 0.1523

477/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9511 - loss: 0.1520

479/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9510 - loss: 0.1521

481/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9509 - loss: 0.1523

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9508 - loss: 0.1523

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9508 - loss: 0.1521

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9509 - loss: 0.1518

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9509 - loss: 0.1518

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9509 - loss: 0.1516

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9510 - loss: 0.1519

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9509 - loss: 0.1520

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9509 - loss: 0.1522

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9508 - loss: 0.1523

501/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9510 - loss: 0.1520

503/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9509 - loss: 0.1522

505/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9509 - loss: 0.1520

507/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9511 - loss: 0.1516

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9512 - loss: 0.1513

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9512 - loss: 0.1513

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9511 - loss: 0.1515

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9512 - loss: 0.1513

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9513 - loss: 0.1511

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9511 - loss: 0.1513

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9512 - loss: 0.1511

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9512 - loss: 0.1510

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9514 - loss: 0.1506

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9515 - loss: 0.1503

529/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9516 - loss: 0.1500

531/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9516 - loss: 0.1504

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9517 - loss: 0.1501

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9518 - loss: 0.1500

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9519 - loss: 0.1497

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9516 - loss: 0.1501

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9517 - loss: 0.1501

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9517 - loss: 0.1498

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9518 - loss: 0.1496

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9519 - loss: 0.1493

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9518 - loss: 0.1495

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9520 - loss: 0.1492

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9520 - loss: 0.1490

555/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9520 - loss: 0.1489

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9520 - loss: 0.1491

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9521 - loss: 0.1488

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9521 - loss: 0.1490

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9522 - loss: 0.1488

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9520 - loss: 0.1489

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9521 - loss: 0.1487

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9522 - loss: 0.1484

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9520 - loss: 0.1488

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9521 - loss: 0.1484

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9522 - loss: 0.1481

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9522 - loss: 0.1481

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9523 - loss: 0.1479

581/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9523 - loss: 0.1476

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9522 - loss: 0.1482

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9521 - loss: 0.1480

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9521 - loss: 0.1479

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9521 - loss: 0.1479

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9522 - loss: 0.1477

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9522 - loss: 0.1476

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9522 - loss: 0.1474

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9522 - loss: 0.1473

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9523 - loss: 0.1470

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9524 - loss: 0.1467

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9524 - loss: 0.1467

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9525 - loss: 0.1465

606/606 ━━━━━━━━━━━━━━━━━━━━ 26s 42ms/step - accuracy: 0.9526 - loss: 0.1464 - val_accuracy: 0.9613 - val_loss: 0.1521

Epoch 10/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.9688 - loss: 0.0408

  3/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9792 - loss: 0.0398

  5/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9625 - loss: 0.0604

  7/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9732 - loss: 0.0541

  9/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9722 - loss: 0.0730

 11/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9744 - loss: 0.0706

 13/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9784 - loss: 0.0641

 15/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9708 - loss: 0.0907

 17/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9669 - loss: 0.1042

 19/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9655 - loss: 0.1088

 21/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9673 - loss: 0.1163

 23/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9647 - loss: 0.1299

 25/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9663 - loss: 0.1236

 27/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9630 - loss: 0.1255

 29/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9623 - loss: 0.1263

 31/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9607 - loss: 0.1310

 33/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9602 - loss: 0.1297

 35/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9616 - loss: 0.1261

 37/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9637 - loss: 0.1223

 39/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9623 - loss: 0.1259

 41/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9619 - loss: 0.1296

 43/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9622 - loss: 0.1271

 45/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9625 - loss: 0.1262

 47/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9621 - loss: 0.1281

 49/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9605 - loss: 0.1310

 51/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9583 - loss: 0.1322

 53/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9570 - loss: 0.1356

 55/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9585 - loss: 0.1321

 57/606 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.9583 - loss: 0.1313

 59/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9576 - loss: 0.1306

 61/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9575 - loss: 0.1311

 63/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9573 - loss: 0.1312

 65/606 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - accuracy: 0.9572 - loss: 0.1411

 67/606 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - accuracy: 0.9576 - loss: 0.1394

 69/606 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - accuracy: 0.9579 - loss: 0.1375

 71/606 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - accuracy: 0.9582 - loss: 0.1357

 73/606 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - accuracy: 0.9580 - loss: 0.1358

 75/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9563 - loss: 0.1386

 77/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9566 - loss: 0.1372

 79/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9573 - loss: 0.1354

 81/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9576 - loss: 0.1356

 83/606 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - accuracy: 0.9567 - loss: 0.1381

 85/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9570 - loss: 0.1369

 87/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9562 - loss: 0.1399

 89/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9558 - loss: 0.1399

 91/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9560 - loss: 0.1400

 93/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9563 - loss: 0.1395

 95/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9569 - loss: 0.1380

 97/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9562 - loss: 0.1386

 99/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9558 - loss: 0.1396

101/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9558 - loss: 0.1394

103/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9560 - loss: 0.1386

105/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9563 - loss: 0.1378

107/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9559 - loss: 0.1381

109/606 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.9558 - loss: 0.1381

111/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9552 - loss: 0.1405

113/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9546 - loss: 0.1442

115/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9546 - loss: 0.1463

117/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9538 - loss: 0.1478

119/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9533 - loss: 0.1483

121/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9533 - loss: 0.1476

123/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9525 - loss: 0.1490

125/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9528 - loss: 0.1483

127/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9520 - loss: 0.1503

129/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9528 - loss: 0.1490

131/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9532 - loss: 0.1479

133/606 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - accuracy: 0.9532 - loss: 0.1491

135/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9532 - loss: 0.1491

137/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9537 - loss: 0.1483

139/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9535 - loss: 0.1503

141/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9535 - loss: 0.1511

143/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9537 - loss: 0.1504

145/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9534 - loss: 0.1504

147/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9539 - loss: 0.1495

149/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9534 - loss: 0.1494

151/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9532 - loss: 0.1496

153/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9536 - loss: 0.1483

155/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9534 - loss: 0.1481

157/606 ━━━━━━━━━━━━━━━━━━━━ 17s 38ms/step - accuracy: 0.9532 - loss: 0.1490

159/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9532 - loss: 0.1493

161/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9534 - loss: 0.1485

163/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9534 - loss: 0.1487

165/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9534 - loss: 0.1479

167/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9536 - loss: 0.1475

169/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9534 - loss: 0.1476

171/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9534 - loss: 0.1482

173/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9534 - loss: 0.1482

175/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9536 - loss: 0.1491

177/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9536 - loss: 0.1493

179/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9536 - loss: 0.1507

181/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9532 - loss: 0.1507

183/606 ━━━━━━━━━━━━━━━━━━━━ 16s 38ms/step - accuracy: 0.9527 - loss: 0.1513

185/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9530 - loss: 0.1505

187/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9529 - loss: 0.1518

189/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9532 - loss: 0.1508

191/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9534 - loss: 0.1507

193/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9534 - loss: 0.1504

195/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9532 - loss: 0.1503

197/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9532 - loss: 0.1503

199/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9534 - loss: 0.1499

201/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9534 - loss: 0.1497

203/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9534 - loss: 0.1493

205/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9534 - loss: 0.1489

207/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9538 - loss: 0.1478

209/606 ━━━━━━━━━━━━━━━━━━━━ 15s 38ms/step - accuracy: 0.9535 - loss: 0.1483

211/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9535 - loss: 0.1477

213/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9536 - loss: 0.1483

215/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9535 - loss: 0.1482

217/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9535 - loss: 0.1487

219/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9538 - loss: 0.1479

221/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9531 - loss: 0.1500

223/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9528 - loss: 0.1505

225/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9529 - loss: 0.1501

227/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9525 - loss: 0.1511

229/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9528 - loss: 0.1504

231/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9528 - loss: 0.1504

233/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9531 - loss: 0.1499

235/606 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - accuracy: 0.9531 - loss: 0.1498

237/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9532 - loss: 0.1493

239/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9535 - loss: 0.1486

241/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9531 - loss: 0.1487

243/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9532 - loss: 0.1484

245/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9534 - loss: 0.1477

247/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9536 - loss: 0.1475

249/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9533 - loss: 0.1474

251/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9534 - loss: 0.1476

253/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9533 - loss: 0.1474

255/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9534 - loss: 0.1470

257/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9534 - loss: 0.1470

259/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9531 - loss: 0.1470

261/606 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - accuracy: 0.9527 - loss: 0.1480

263/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9528 - loss: 0.1481

265/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9524 - loss: 0.1484

267/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9519 - loss: 0.1489

269/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9520 - loss: 0.1489

271/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9520 - loss: 0.1487

273/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9520 - loss: 0.1486

275/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9520 - loss: 0.1491

277/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9521 - loss: 0.1490

279/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9519 - loss: 0.1493

281/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9520 - loss: 0.1497

283/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9521 - loss: 0.1493

285/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9520 - loss: 0.1494

287/606 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.9522 - loss: 0.1489

289/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9516 - loss: 0.1506

291/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9518 - loss: 0.1501

293/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9516 - loss: 0.1503

295/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9518 - loss: 0.1499

297/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9517 - loss: 0.1498

299/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9518 - loss: 0.1494

301/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9520 - loss: 0.1489

303/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9522 - loss: 0.1483

305/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9519 - loss: 0.1497

307/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9519 - loss: 0.1496

309/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9518 - loss: 0.1497

311/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9518 - loss: 0.1494

313/606 ━━━━━━━━━━━━━━━━━━━━ 11s 38ms/step - accuracy: 0.9520 - loss: 0.1491

315/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9520 - loss: 0.1497

317/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9521 - loss: 0.1493

319/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9522 - loss: 0.1490

321/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9521 - loss: 0.1490

323/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9524 - loss: 0.1485

325/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9526 - loss: 0.1479

327/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9528 - loss: 0.1475

329/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9529 - loss: 0.1474

331/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9529 - loss: 0.1471

333/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9531 - loss: 0.1465

335/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9532 - loss: 0.1474

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9531 - loss: 0.1476

339/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9529 - loss: 0.1480

341/606 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9529 - loss: 0.1478

343/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9528 - loss: 0.1489

345/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9527 - loss: 0.1492

347/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9526 - loss: 0.1494

349/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9527 - loss: 0.1491

351/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9528 - loss: 0.1487

353/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9529 - loss: 0.1484

355/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9529 - loss: 0.1482

357/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9532 - loss: 0.1477

359/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9533 - loss: 0.1474

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9534 - loss: 0.1471

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9534 - loss: 0.1471

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9535 - loss: 0.1480

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 38ms/step - accuracy: 0.9532 - loss: 0.1488

369/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9529 - loss: 0.1493

371/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9530 - loss: 0.1490

373/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9529 - loss: 0.1491

375/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9528 - loss: 0.1491

377/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9529 - loss: 0.1487

379/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9528 - loss: 0.1489

381/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9528 - loss: 0.1486

383/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9527 - loss: 0.1492

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9528 - loss: 0.1489

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9528 - loss: 0.1486

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9531 - loss: 0.1481

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9530 - loss: 0.1482

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - accuracy: 0.9528 - loss: 0.1485

395/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9529 - loss: 0.1481

397/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9530 - loss: 0.1480

399/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9530 - loss: 0.1479

401/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9529 - loss: 0.1486

403/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9530 - loss: 0.1483

405/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9529 - loss: 0.1486

407/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9529 - loss: 0.1485

409/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9527 - loss: 0.1485

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9526 - loss: 0.1486

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9527 - loss: 0.1483

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9528 - loss: 0.1480

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9529 - loss: 0.1478

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9528 - loss: 0.1476

421/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9529 - loss: 0.1473

423/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9528 - loss: 0.1473

425/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9528 - loss: 0.1471

427/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9527 - loss: 0.1470

429/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9527 - loss: 0.1469

431/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9528 - loss: 0.1480

433/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9527 - loss: 0.1479

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9527 - loss: 0.1480

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9526 - loss: 0.1482

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9527 - loss: 0.1478

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9528 - loss: 0.1476

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9528 - loss: 0.1475

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9527 - loss: 0.1480

447/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9525 - loss: 0.1478

449/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9525 - loss: 0.1477

451/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9526 - loss: 0.1480

453/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9526 - loss: 0.1481

455/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9527 - loss: 0.1480

457/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9527 - loss: 0.1479

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9528 - loss: 0.1477

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9527 - loss: 0.1477

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9526 - loss: 0.1477

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9526 - loss: 0.1477

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9526 - loss: 0.1476

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9528 - loss: 0.1473

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9527 - loss: 0.1473

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9528 - loss: 0.1470

475/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9528 - loss: 0.1469

477/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9527 - loss: 0.1473

479/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9528 - loss: 0.1471

481/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9530 - loss: 0.1468

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9528 - loss: 0.1469

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9527 - loss: 0.1469

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9528 - loss: 0.1466

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9528 - loss: 0.1463

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9527 - loss: 0.1464

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9526 - loss: 0.1463

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9526 - loss: 0.1463

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9525 - loss: 0.1472

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9525 - loss: 0.1470

501/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9526 - loss: 0.1467

503/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9527 - loss: 0.1463

505/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9528 - loss: 0.1461

507/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9528 - loss: 0.1462

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9528 - loss: 0.1461

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9527 - loss: 0.1461

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9527 - loss: 0.1462

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9526 - loss: 0.1463

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9527 - loss: 0.1460

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9526 - loss: 0.1463

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9527 - loss: 0.1459

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9528 - loss: 0.1456

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9529 - loss: 0.1453

527/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9528 - loss: 0.1456

529/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9529 - loss: 0.1455

531/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9530 - loss: 0.1451

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9530 - loss: 0.1450

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9529 - loss: 0.1454

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9527 - loss: 0.1457

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9528 - loss: 0.1454

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9530 - loss: 0.1450

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9530 - loss: 0.1454

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9530 - loss: 0.1452

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9530 - loss: 0.1451

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9529 - loss: 0.1455

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.9530 - loss: 0.1454

553/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9529 - loss: 0.1456

555/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9528 - loss: 0.1456

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9528 - loss: 0.1454

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9529 - loss: 0.1452

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9528 - loss: 0.1453

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9527 - loss: 0.1455

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9528 - loss: 0.1452

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9528 - loss: 0.1450

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9528 - loss: 0.1450

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9528 - loss: 0.1449

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9528 - loss: 0.1448

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9529 - loss: 0.1445

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9530 - loss: 0.1442

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9531 - loss: 0.1440

581/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9533 - loss: 0.1437

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9534 - loss: 0.1435

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9534 - loss: 0.1434

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9534 - loss: 0.1435

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9533 - loss: 0.1434

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9534 - loss: 0.1430

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9534 - loss: 0.1431

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9535 - loss: 0.1430

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9535 - loss: 0.1428

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9536 - loss: 0.1427

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9536 - loss: 0.1424

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9536 - loss: 0.1423

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9537 - loss: 0.1420

606/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9538 - loss: 0.1419 - val_accuracy: 0.9596 - val_loss: 0.1563

Epoch 11/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.9375 - loss: 0.1144

  3/606 ━━━━━━━━━━━━━━━━━━━━ 23s 38ms/step - accuracy: 0.9583 - loss: 0.1029

  5/606 ━━━━━━━━━━━━━━━━━━━━ 23s 38ms/step - accuracy: 0.9750 - loss: 0.0714

  7/606 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - accuracy: 0.9688 - loss: 0.0859

  9/606 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - accuracy: 0.9688 - loss: 0.0789

 11/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9659 - loss: 0.0882

 13/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9663 - loss: 0.0845

 15/606 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - accuracy: 0.9625 - loss: 0.0938

 17/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9559 - loss: 0.1225

 19/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9605 - loss: 0.1127

 21/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9613 - loss: 0.1107

 23/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9592 - loss: 0.1108

 25/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9613 - loss: 0.1077

 27/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9630 - loss: 0.1064

 29/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9623 - loss: 0.1121

 31/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9597 - loss: 0.1228

 33/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9602 - loss: 0.1213

 35/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9598 - loss: 0.1205

 37/606 ━━━━━━━━━━━━━━━━━━━━ 21s 37ms/step - accuracy: 0.9611 - loss: 0.1180

 39/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9607 - loss: 0.1187

 41/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9604 - loss: 0.1232

 43/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9608 - loss: 0.1222

 45/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9604 - loss: 0.1203

 47/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9601 - loss: 0.1202

 49/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9585 - loss: 0.1245

 51/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9577 - loss: 0.1284

 53/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9570 - loss: 0.1278

 55/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9574 - loss: 0.1256

 57/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9567 - loss: 0.1267

 59/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9576 - loss: 0.1257

 61/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9585 - loss: 0.1234

 63/606 ━━━━━━━━━━━━━━━━━━━━ 20s 37ms/step - accuracy: 0.9588 - loss: 0.1224

 65/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9587 - loss: 0.1233

 67/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9585 - loss: 0.1255

 69/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9588 - loss: 0.1253

 71/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9591 - loss: 0.1238

 73/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9585 - loss: 0.1243

 75/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9579 - loss: 0.1255

 77/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9582 - loss: 0.1257

 79/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9589 - loss: 0.1242

 81/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9576 - loss: 0.1263

 83/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9575 - loss: 0.1307

 85/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9585 - loss: 0.1283

 87/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9580 - loss: 0.1286

 89/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9582 - loss: 0.1282

 91/606 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.9584 - loss: 0.1269

 93/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9573 - loss: 0.1290

 95/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9569 - loss: 0.1298

 97/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9578 - loss: 0.1285

 99/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9574 - loss: 0.1278

101/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9579 - loss: 0.1270

103/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9578 - loss: 0.1281

105/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9577 - loss: 0.1284

107/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9579 - loss: 0.1286

109/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9573 - loss: 0.1294

111/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9569 - loss: 0.1299

113/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9560 - loss: 0.1355

115/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9560 - loss: 0.1362

117/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9559 - loss: 0.1366

119/606 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - accuracy: 0.9554 - loss: 0.1382

121/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9558 - loss: 0.1383

123/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9560 - loss: 0.1384

125/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9563 - loss: 0.1373

127/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9560 - loss: 0.1378

129/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9554 - loss: 0.1409

131/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9559 - loss: 0.1396

133/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9561 - loss: 0.1422

135/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9558 - loss: 0.1431

137/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9564 - loss: 0.1417

139/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9559 - loss: 0.1417

141/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9559 - loss: 0.1413

143/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9561 - loss: 0.1408

145/606 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - accuracy: 0.9565 - loss: 0.1401

147/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9562 - loss: 0.1401

149/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9566 - loss: 0.1391

151/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9563 - loss: 0.1400

153/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9567 - loss: 0.1388

155/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9569 - loss: 0.1384

157/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9564 - loss: 0.1382

159/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9564 - loss: 0.1385

161/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9559 - loss: 0.1391

163/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9563 - loss: 0.1380

165/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9559 - loss: 0.1400

167/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9551 - loss: 0.1409

169/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9547 - loss: 0.1419

171/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9545 - loss: 0.1424

173/606 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.9545 - loss: 0.1422

175/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9546 - loss: 0.1421

177/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9546 - loss: 0.1425

179/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9548 - loss: 0.1425

181/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9539 - loss: 0.1453

183/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9539 - loss: 0.1449

185/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9541 - loss: 0.1443

187/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9535 - loss: 0.1447

189/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9537 - loss: 0.1438

191/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9537 - loss: 0.1436

193/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9539 - loss: 0.1431

195/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9538 - loss: 0.1432

197/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9543 - loss: 0.1422

199/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9545 - loss: 0.1415

201/606 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9543 - loss: 0.1415

203/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9547 - loss: 0.1406

205/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9550 - loss: 0.1407

207/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9550 - loss: 0.1409

209/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9554 - loss: 0.1399

211/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9551 - loss: 0.1416

213/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9554 - loss: 0.1411

215/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9557 - loss: 0.1416

217/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9559 - loss: 0.1413

219/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9556 - loss: 0.1417

221/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9557 - loss: 0.1413

223/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9557 - loss: 0.1413

225/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9554 - loss: 0.1416

227/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9554 - loss: 0.1415

229/606 ━━━━━━━━━━━━━━━━━━━━ 14s 37ms/step - accuracy: 0.9551 - loss: 0.1426

231/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9551 - loss: 0.1423

233/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9545 - loss: 0.1432

235/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9548 - loss: 0.1426

237/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9548 - loss: 0.1423

239/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9548 - loss: 0.1421

241/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9549 - loss: 0.1418

243/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9547 - loss: 0.1419

245/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9545 - loss: 0.1425

247/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9543 - loss: 0.1424

249/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9542 - loss: 0.1422

251/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9541 - loss: 0.1421

253/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9543 - loss: 0.1415

255/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9544 - loss: 0.1413

257/606 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - accuracy: 0.9540 - loss: 0.1417

259/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9543 - loss: 0.1412

261/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9541 - loss: 0.1420

263/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9541 - loss: 0.1416

265/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9541 - loss: 0.1411

267/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9542 - loss: 0.1407

269/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9542 - loss: 0.1406

271/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9543 - loss: 0.1405

273/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9544 - loss: 0.1403

275/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9543 - loss: 0.1410

277/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9544 - loss: 0.1411

279/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9543 - loss: 0.1413

281/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9542 - loss: 0.1412

283/606 ━━━━━━━━━━━━━━━━━━━━ 12s 37ms/step - accuracy: 0.9541 - loss: 0.1414

285/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9541 - loss: 0.1416

287/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9541 - loss: 0.1420

289/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9540 - loss: 0.1427

291/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9539 - loss: 0.1429

293/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9539 - loss: 0.1429

295/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9535 - loss: 0.1436

297/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9534 - loss: 0.1438

299/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9534 - loss: 0.1434

301/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9533 - loss: 0.1434

303/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9535 - loss: 0.1429

305/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9537 - loss: 0.1428

307/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9538 - loss: 0.1426

309/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9539 - loss: 0.1430

311/606 ━━━━━━━━━━━━━━━━━━━━ 11s 37ms/step - accuracy: 0.9541 - loss: 0.1428

313/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9543 - loss: 0.1424

315/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9544 - loss: 0.1422

317/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9543 - loss: 0.1425

319/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9544 - loss: 0.1420

321/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9542 - loss: 0.1421

323/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9542 - loss: 0.1419

325/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9542 - loss: 0.1421

327/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9542 - loss: 0.1420

329/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9544 - loss: 0.1415

331/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9545 - loss: 0.1422

333/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9545 - loss: 0.1421

335/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9543 - loss: 0.1426

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 37ms/step - accuracy: 0.9543 - loss: 0.1425

339/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9543 - loss: 0.1423

341/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9541 - loss: 0.1428

343/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9543 - loss: 0.1422

345/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9542 - loss: 0.1423

347/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9543 - loss: 0.1420

349/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9543 - loss: 0.1418

351/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9543 - loss: 0.1419

353/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9542 - loss: 0.1417

355/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9543 - loss: 0.1426

357/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9543 - loss: 0.1431

359/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9544 - loss: 0.1429

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9545 - loss: 0.1426

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9545 - loss: 0.1426

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 37ms/step - accuracy: 0.9546 - loss: 0.1422

367/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9546 - loss: 0.1422

369/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9544 - loss: 0.1425

371/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9544 - loss: 0.1423

373/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9543 - loss: 0.1425

375/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9543 - loss: 0.1425

377/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9542 - loss: 0.1434

379/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9543 - loss: 0.1433

381/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9543 - loss: 0.1432

383/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9541 - loss: 0.1434

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9541 - loss: 0.1433

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9540 - loss: 0.1435

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9540 - loss: 0.1434

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - accuracy: 0.9543 - loss: 0.1429

393/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9542 - loss: 0.1428

395/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9544 - loss: 0.1423

397/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9542 - loss: 0.1426

399/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9540 - loss: 0.1430

401/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9539 - loss: 0.1431

403/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9539 - loss: 0.1429

405/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9541 - loss: 0.1427

407/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9539 - loss: 0.1433

409/606 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.9538 - loss: 0.1436

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9537 - loss: 0.1437

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9538 - loss: 0.1434

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9538 - loss: 0.1435

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9539 - loss: 0.1438

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.9541 - loss: 0.1434

421/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9540 - loss: 0.1434

423/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9539 - loss: 0.1433

425/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9540 - loss: 0.1430

427/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9538 - loss: 0.1431

429/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9538 - loss: 0.1429

431/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9537 - loss: 0.1430

433/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9537 - loss: 0.1430

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9540 - loss: 0.1426

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9538 - loss: 0.1427

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9539 - loss: 0.1429

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9538 - loss: 0.1428

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9539 - loss: 0.1427

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9539 - loss: 0.1425

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9539 - loss: 0.1426

449/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9540 - loss: 0.1426

451/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9539 - loss: 0.1426

453/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9538 - loss: 0.1432

455/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9540 - loss: 0.1427

457/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9540 - loss: 0.1424

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9542 - loss: 0.1420

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9542 - loss: 0.1418

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9541 - loss: 0.1421

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9542 - loss: 0.1419

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9542 - loss: 0.1417

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9543 - loss: 0.1415

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9544 - loss: 0.1412

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9544 - loss: 0.1411

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - accuracy: 0.9543 - loss: 0.1412

477/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9541 - loss: 0.1419

479/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9542 - loss: 0.1417

481/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9543 - loss: 0.1414

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9542 - loss: 0.1415

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9541 - loss: 0.1416

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9542 - loss: 0.1413

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9541 - loss: 0.1414

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9540 - loss: 0.1413

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9540 - loss: 0.1413

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9540 - loss: 0.1412

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9539 - loss: 0.1415

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9538 - loss: 0.1414

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.9538 - loss: 0.1412

503/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9540 - loss: 0.1408

505/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9541 - loss: 0.1405

507/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9540 - loss: 0.1408

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9541 - loss: 0.1405

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - accuracy: 0.9542 - loss: 0.1401

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.9539 - loss: 0.1410

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.9540 - loss: 0.1409

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.9541 - loss: 0.1407

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.9541 - loss: 0.1409

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.9540 - loss: 0.1408

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.9542 - loss: 0.1405

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.9542 - loss: 0.1404

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.9543 - loss: 0.1403

529/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9543 - loss: 0.1401

531/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9544 - loss: 0.1399

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9543 - loss: 0.1398

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9544 - loss: 0.1396

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9544 - loss: 0.1399

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9545 - loss: 0.1399

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9546 - loss: 0.1397

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9546 - loss: 0.1396

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9546 - loss: 0.1399

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9548 - loss: 0.1396

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9547 - loss: 0.1395

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9544 - loss: 0.1402

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9544 - loss: 0.1402

555/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9543 - loss: 0.1403

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9543 - loss: 0.1401

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9544 - loss: 0.1397

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9545 - loss: 0.1395

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9545 - loss: 0.1393

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9546 - loss: 0.1391

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9548 - loss: 0.1389

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9546 - loss: 0.1392

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9546 - loss: 0.1391

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9546 - loss: 0.1392

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9547 - loss: 0.1388

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9548 - loss: 0.1387

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9549 - loss: 0.1383

581/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9549 - loss: 0.1383

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9551 - loss: 0.1379

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9551 - loss: 0.1379

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9551 - loss: 0.1377

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9551 - loss: 0.1377

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9552 - loss: 0.1376

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9550 - loss: 0.1377

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9550 - loss: 0.1375

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9551 - loss: 0.1374

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9551 - loss: 0.1374

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9550 - loss: 0.1374

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9551 - loss: 0.1371

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9553 - loss: 0.1368

606/606 ━━━━━━━━━━━━━━━━━━━━ 27s 44ms/step - accuracy: 0.9553 - loss: 0.1370 - val_accuracy: 0.9630 - val_loss: 0.1461

Epoch 12/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 36s 61ms/step - accuracy: 1.0000 - loss: 0.0724

  3/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9792 - loss: 0.0786

  5/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9750 - loss: 0.0784

  7/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9732 - loss: 0.0892

  9/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9722 - loss: 0.0872

 11/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9716 - loss: 0.0879

 13/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9663 - loss: 0.0950

 15/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9646 - loss: 0.0986

 17/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9614 - loss: 0.1158

 19/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9638 - loss: 0.1104

 21/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9643 - loss: 0.1065

 23/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9606 - loss: 0.1181

 25/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9625 - loss: 0.1145

 27/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9630 - loss: 0.1154

 29/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9623 - loss: 0.1146

 31/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9617 - loss: 0.1161

 33/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9612 - loss: 0.1169

 35/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9598 - loss: 0.1230

 37/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9611 - loss: 0.1215

 39/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9607 - loss: 0.1209

 41/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9619 - loss: 0.1197

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9615 - loss: 0.1185

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9618 - loss: 0.1190

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9594 - loss: 0.1225

 49/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9592 - loss: 0.1218

 51/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9589 - loss: 0.1214

 53/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9587 - loss: 0.1194

 55/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9591 - loss: 0.1178

 57/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9605 - loss: 0.1149

 59/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9597 - loss: 0.1151

 61/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9600 - loss: 0.1145

 63/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9608 - loss: 0.1129

 65/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9611 - loss: 0.1122

 67/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9613 - loss: 0.1117

 69/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9606 - loss: 0.1122

 71/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9608 - loss: 0.1148

 73/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9615 - loss: 0.1135

 75/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9613 - loss: 0.1158

 77/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9602 - loss: 0.1205

 79/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9600 - loss: 0.1225

 81/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9587 - loss: 0.1243

 83/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9578 - loss: 0.1263

 85/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9574 - loss: 0.1263

 87/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9576 - loss: 0.1263

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9575 - loss: 0.1268

 91/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9574 - loss: 0.1259

 93/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9573 - loss: 0.1256

 95/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9569 - loss: 0.1267

 97/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9568 - loss: 0.1265

 99/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9577 - loss: 0.1248

101/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9573 - loss: 0.1256

103/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9572 - loss: 0.1257

105/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9568 - loss: 0.1263

107/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9571 - loss: 0.1250

109/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9573 - loss: 0.1238

111/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9578 - loss: 0.1228

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9571 - loss: 0.1253

115/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9568 - loss: 0.1283

117/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9567 - loss: 0.1298

119/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9564 - loss: 0.1321

121/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9564 - loss: 0.1315

123/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9563 - loss: 0.1312

125/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9567 - loss: 0.1300

127/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9567 - loss: 0.1295

129/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9571 - loss: 0.1286

131/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9559 - loss: 0.1307

133/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9554 - loss: 0.1312

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9546 - loss: 0.1348

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9553 - loss: 0.1336

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9553 - loss: 0.1332

141/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9550 - loss: 0.1335

143/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9552 - loss: 0.1328

145/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9550 - loss: 0.1328

147/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9547 - loss: 0.1331

149/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9551 - loss: 0.1318

151/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9549 - loss: 0.1320

153/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9551 - loss: 0.1314

155/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9548 - loss: 0.1314

157/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9550 - loss: 0.1308

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9554 - loss: 0.1308

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9554 - loss: 0.1310

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9551 - loss: 0.1311

165/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9551 - loss: 0.1313

167/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9545 - loss: 0.1341

169/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9541 - loss: 0.1347

171/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9543 - loss: 0.1339

173/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9545 - loss: 0.1339

175/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9541 - loss: 0.1345

177/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9541 - loss: 0.1348

179/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9543 - loss: 0.1346

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9542 - loss: 0.1346

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9542 - loss: 0.1343

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9544 - loss: 0.1339

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9540 - loss: 0.1344

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9540 - loss: 0.1341

191/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9540 - loss: 0.1349

193/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9540 - loss: 0.1343

195/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9542 - loss: 0.1340

197/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9542 - loss: 0.1336

199/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9541 - loss: 0.1333

201/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9541 - loss: 0.1340

203/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9544 - loss: 0.1334

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9544 - loss: 0.1330

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9544 - loss: 0.1333

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9548 - loss: 0.1324

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9548 - loss: 0.1322

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9550 - loss: 0.1324

215/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9549 - loss: 0.1324

217/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9549 - loss: 0.1326

219/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9546 - loss: 0.1338

221/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9546 - loss: 0.1340

223/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9549 - loss: 0.1332

225/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9549 - loss: 0.1336

227/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9547 - loss: 0.1342

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9543 - loss: 0.1351

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9545 - loss: 0.1344

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9540 - loss: 0.1354

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9541 - loss: 0.1350

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9542 - loss: 0.1348

239/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9538 - loss: 0.1351

241/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9537 - loss: 0.1356

243/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9538 - loss: 0.1352

245/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9538 - loss: 0.1348

247/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9538 - loss: 0.1348

249/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9538 - loss: 0.1349

251/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9539 - loss: 0.1346

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9539 - loss: 0.1347

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9542 - loss: 0.1344

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9543 - loss: 0.1339

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9543 - loss: 0.1341

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9544 - loss: 0.1337

263/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9543 - loss: 0.1337

265/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9540 - loss: 0.1348

267/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9541 - loss: 0.1345

269/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9534 - loss: 0.1353

271/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9538 - loss: 0.1348

273/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9535 - loss: 0.1351

275/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9535 - loss: 0.1348

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9534 - loss: 0.1352

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9533 - loss: 0.1360

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9533 - loss: 0.1360

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9533 - loss: 0.1359

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9531 - loss: 0.1362

287/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9533 - loss: 0.1358

289/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9530 - loss: 0.1371

291/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9531 - loss: 0.1368

293/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9532 - loss: 0.1364

295/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9532 - loss: 0.1362

297/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9534 - loss: 0.1361

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9532 - loss: 0.1363

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9535 - loss: 0.1357

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9536 - loss: 0.1359

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9536 - loss: 0.1365

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9533 - loss: 0.1368

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9534 - loss: 0.1369

311/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9534 - loss: 0.1367

313/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9533 - loss: 0.1367

315/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9532 - loss: 0.1367

317/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9533 - loss: 0.1365

319/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9534 - loss: 0.1360

321/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9532 - loss: 0.1362

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9533 - loss: 0.1361

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9532 - loss: 0.1362

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9534 - loss: 0.1358

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9536 - loss: 0.1354

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9535 - loss: 0.1367

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9535 - loss: 0.1367

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9535 - loss: 0.1365

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9535 - loss: 0.1364

339/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9537 - loss: 0.1358

341/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9535 - loss: 0.1363

343/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9533 - loss: 0.1366

345/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9533 - loss: 0.1363

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9531 - loss: 0.1366

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9532 - loss: 0.1363

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9533 - loss: 0.1361

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9533 - loss: 0.1366

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9533 - loss: 0.1363

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9534 - loss: 0.1359

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9535 - loss: 0.1363

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9537 - loss: 0.1358

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9537 - loss: 0.1359

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9537 - loss: 0.1358

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9534 - loss: 0.1364

369/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9531 - loss: 0.1378

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9529 - loss: 0.1382

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9531 - loss: 0.1380

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9533 - loss: 0.1375

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9533 - loss: 0.1375

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9535 - loss: 0.1372

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9536 - loss: 0.1375

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9537 - loss: 0.1375

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9537 - loss: 0.1374

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9536 - loss: 0.1375

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9536 - loss: 0.1372

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9536 - loss: 0.1375

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9536 - loss: 0.1376

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9537 - loss: 0.1374

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9537 - loss: 0.1372

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9537 - loss: 0.1370

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9538 - loss: 0.1368

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9537 - loss: 0.1370

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9536 - loss: 0.1371

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9536 - loss: 0.1373

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9538 - loss: 0.1369

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9539 - loss: 0.1366

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9538 - loss: 0.1365

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9538 - loss: 0.1365

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9536 - loss: 0.1368

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9537 - loss: 0.1366

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9536 - loss: 0.1375

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9537 - loss: 0.1372

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9538 - loss: 0.1369

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9540 - loss: 0.1365

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9540 - loss: 0.1367

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9541 - loss: 0.1364

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9542 - loss: 0.1364

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9541 - loss: 0.1364

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9541 - loss: 0.1365

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9543 - loss: 0.1360

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9542 - loss: 0.1359

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9540 - loss: 0.1361

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9541 - loss: 0.1358

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9542 - loss: 0.1355

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9541 - loss: 0.1358

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9542 - loss: 0.1356

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9541 - loss: 0.1363

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9541 - loss: 0.1362

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9541 - loss: 0.1361

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9543 - loss: 0.1356

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9542 - loss: 0.1360

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9542 - loss: 0.1361

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9542 - loss: 0.1360

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9543 - loss: 0.1357

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9542 - loss: 0.1359

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9543 - loss: 0.1357

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9543 - loss: 0.1355

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9544 - loss: 0.1352

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9543 - loss: 0.1353

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9544 - loss: 0.1353

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9545 - loss: 0.1351

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9545 - loss: 0.1352

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9545 - loss: 0.1350

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9546 - loss: 0.1348

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9543 - loss: 0.1351

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9542 - loss: 0.1351

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9542 - loss: 0.1351

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9542 - loss: 0.1350

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9540 - loss: 0.1355

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9540 - loss: 0.1353

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9540 - loss: 0.1354

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9541 - loss: 0.1356

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9540 - loss: 0.1357

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9541 - loss: 0.1355

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9539 - loss: 0.1357

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9539 - loss: 0.1357

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9541 - loss: 0.1353

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9542 - loss: 0.1350

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9543 - loss: 0.1350

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9543 - loss: 0.1349

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9544 - loss: 0.1347

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9544 - loss: 0.1347

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9545 - loss: 0.1347

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9544 - loss: 0.1348

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9545 - loss: 0.1346

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9546 - loss: 0.1348

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9546 - loss: 0.1347

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9547 - loss: 0.1345

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9546 - loss: 0.1345

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9545 - loss: 0.1346

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9545 - loss: 0.1344

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9545 - loss: 0.1344

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9545 - loss: 0.1342

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9546 - loss: 0.1342

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9546 - loss: 0.1342

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9546 - loss: 0.1343

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9546 - loss: 0.1344

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9546 - loss: 0.1344

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9546 - loss: 0.1342

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9544 - loss: 0.1345

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9546 - loss: 0.1342

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9545 - loss: 0.1343

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9545 - loss: 0.1342

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9546 - loss: 0.1343

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9546 - loss: 0.1342

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9547 - loss: 0.1343

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9547 - loss: 0.1341

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9549 - loss: 0.1338

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9549 - loss: 0.1336

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9549 - loss: 0.1336

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9550 - loss: 0.1335

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9550 - loss: 0.1336

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9550 - loss: 0.1335

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9550 - loss: 0.1333

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9551 - loss: 0.1331

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9551 - loss: 0.1333

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9552 - loss: 0.1330

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9551 - loss: 0.1330

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9552 - loss: 0.1326

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9554 - loss: 0.1323

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9554 - loss: 0.1323

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9554 - loss: 0.1323

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9554 - loss: 0.1323

606/606 ━━━━━━━━━━━━━━━━━━━━ 27s 45ms/step - accuracy: 0.9554 - loss: 0.1323 - val_accuracy: 0.9530 - val_loss: 0.1838

Epoch 13/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.9375 - loss: 0.0952

  3/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9688 - loss: 0.0689

  5/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9563 - loss: 0.0865

  7/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9643 - loss: 0.0747

  9/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9688 - loss: 0.0719

 11/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9659 - loss: 0.0919

 13/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9591 - loss: 0.1041

 15/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9542 - loss: 0.1117

 17/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9577 - loss: 0.1040

 19/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9589 - loss: 0.1190

 21/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9613 - loss: 0.1121

 23/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9633 - loss: 0.1080

 25/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9625 - loss: 0.1168

 27/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9618 - loss: 0.1164

 29/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9634 - loss: 0.1122

 31/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9647 - loss: 0.1122

 33/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9640 - loss: 0.1153

 35/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9643 - loss: 0.1143

 37/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9637 - loss: 0.1144

 39/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9631 - loss: 0.1190

 41/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9611 - loss: 0.1217

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9600 - loss: 0.1213

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9611 - loss: 0.1200

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9621 - loss: 0.1168

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9624 - loss: 0.1156

 51/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9626 - loss: 0.1156

 53/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9617 - loss: 0.1161

 55/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9602 - loss: 0.1183

 57/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9600 - loss: 0.1174

 59/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9603 - loss: 0.1188

 61/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9606 - loss: 0.1189

 63/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9608 - loss: 0.1181

 65/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9611 - loss: 0.1173

 67/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9608 - loss: 0.1162

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9592 - loss: 0.1228

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9591 - loss: 0.1220

 73/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9585 - loss: 0.1230

 75/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9592 - loss: 0.1215

 77/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9570 - loss: 0.1248

 79/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9565 - loss: 0.1252

 81/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9564 - loss: 0.1247

 83/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9571 - loss: 0.1234

 85/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9570 - loss: 0.1238

 87/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9565 - loss: 0.1239

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9572 - loss: 0.1232

 91/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9571 - loss: 0.1236

 93/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9573 - loss: 0.1227

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9579 - loss: 0.1219

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9578 - loss: 0.1214

 99/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9574 - loss: 0.1220

101/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9576 - loss: 0.1222

103/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9578 - loss: 0.1220

105/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9580 - loss: 0.1216

107/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9577 - loss: 0.1212

109/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9581 - loss: 0.1199

111/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9583 - loss: 0.1221

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9577 - loss: 0.1253

115/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9582 - loss: 0.1244

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9578 - loss: 0.1258

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9580 - loss: 0.1250

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9571 - loss: 0.1275

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9576 - loss: 0.1266

125/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9580 - loss: 0.1260

127/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9574 - loss: 0.1267

129/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9574 - loss: 0.1277

131/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9575 - loss: 0.1290

133/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9563 - loss: 0.1309

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9563 - loss: 0.1319

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9564 - loss: 0.1313

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9568 - loss: 0.1303

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9568 - loss: 0.1300

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9567 - loss: 0.1297

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9573 - loss: 0.1283

147/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9575 - loss: 0.1279

149/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9581 - loss: 0.1268

151/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9574 - loss: 0.1272

153/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9571 - loss: 0.1286

155/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9577 - loss: 0.1273

157/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9580 - loss: 0.1270

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9574 - loss: 0.1283

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9571 - loss: 0.1285

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9574 - loss: 0.1281

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9576 - loss: 0.1277

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9575 - loss: 0.1273

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9575 - loss: 0.1274

171/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9574 - loss: 0.1275

173/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9574 - loss: 0.1277

175/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9573 - loss: 0.1290

177/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9573 - loss: 0.1292

179/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9576 - loss: 0.1287

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9574 - loss: 0.1288

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9573 - loss: 0.1285

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9573 - loss: 0.1283

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9572 - loss: 0.1298

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9567 - loss: 0.1304

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9566 - loss: 0.1302

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9569 - loss: 0.1294

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9571 - loss: 0.1290

197/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9569 - loss: 0.1289

199/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9571 - loss: 0.1282

201/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9571 - loss: 0.1284

203/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9569 - loss: 0.1286

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9567 - loss: 0.1297

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9570 - loss: 0.1290

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9571 - loss: 0.1286

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9569 - loss: 0.1291

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9570 - loss: 0.1302

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9564 - loss: 0.1313

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9565 - loss: 0.1313

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9559 - loss: 0.1328

221/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9557 - loss: 0.1332

223/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9561 - loss: 0.1324

225/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9561 - loss: 0.1326

227/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9561 - loss: 0.1329

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9562 - loss: 0.1328

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9564 - loss: 0.1321

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9565 - loss: 0.1316

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9565 - loss: 0.1314

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9566 - loss: 0.1310

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9562 - loss: 0.1314

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9559 - loss: 0.1322

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9558 - loss: 0.1322

245/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9559 - loss: 0.1321

247/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9557 - loss: 0.1321

249/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9557 - loss: 0.1321

251/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9554 - loss: 0.1323

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9555 - loss: 0.1322

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9558 - loss: 0.1316

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9559 - loss: 0.1313

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9561 - loss: 0.1307

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9561 - loss: 0.1308

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9559 - loss: 0.1311

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9560 - loss: 0.1309

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9560 - loss: 0.1311

269/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9555 - loss: 0.1313

271/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9555 - loss: 0.1308

273/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9556 - loss: 0.1305

275/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9557 - loss: 0.1308

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9557 - loss: 0.1308

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9556 - loss: 0.1308

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9554 - loss: 0.1316

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9556 - loss: 0.1310

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9556 - loss: 0.1309

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9554 - loss: 0.1312

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9550 - loss: 0.1318

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9550 - loss: 0.1319

293/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9552 - loss: 0.1313

295/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9552 - loss: 0.1313

297/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9554 - loss: 0.1310

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9555 - loss: 0.1306

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9551 - loss: 0.1314

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9552 - loss: 0.1312

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9553 - loss: 0.1310

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9553 - loss: 0.1313

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9555 - loss: 0.1309

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9558 - loss: 0.1303

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9558 - loss: 0.1307

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9560 - loss: 0.1304

317/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9560 - loss: 0.1301

319/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9561 - loss: 0.1300

321/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9560 - loss: 0.1302

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9562 - loss: 0.1298

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9561 - loss: 0.1306

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9561 - loss: 0.1305

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9563 - loss: 0.1303

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9562 - loss: 0.1308

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9564 - loss: 0.1314

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9565 - loss: 0.1309

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9564 - loss: 0.1309

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9564 - loss: 0.1309

341/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9562 - loss: 0.1312

343/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9561 - loss: 0.1315

345/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9560 - loss: 0.1316

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9558 - loss: 0.1322

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9559 - loss: 0.1318

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9558 - loss: 0.1319

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9558 - loss: 0.1317

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9558 - loss: 0.1314

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9558 - loss: 0.1316

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9560 - loss: 0.1311

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9562 - loss: 0.1311

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9564 - loss: 0.1305

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9561 - loss: 0.1313

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9561 - loss: 0.1314

369/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9561 - loss: 0.1313

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9563 - loss: 0.1311

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9564 - loss: 0.1308

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9563 - loss: 0.1319

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9562 - loss: 0.1323

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9563 - loss: 0.1324

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9560 - loss: 0.1328

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9561 - loss: 0.1326

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9559 - loss: 0.1326

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9557 - loss: 0.1331

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9557 - loss: 0.1330

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9556 - loss: 0.1331

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9558 - loss: 0.1328

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9558 - loss: 0.1329

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9558 - loss: 0.1326

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9558 - loss: 0.1329

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9560 - loss: 0.1327

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9560 - loss: 0.1326

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9563 - loss: 0.1322

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9562 - loss: 0.1323

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9562 - loss: 0.1321

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9563 - loss: 0.1321

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9561 - loss: 0.1323

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9560 - loss: 0.1325

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9557 - loss: 0.1327

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9558 - loss: 0.1324

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9556 - loss: 0.1326

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9557 - loss: 0.1323

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9555 - loss: 0.1332

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9554 - loss: 0.1331

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9556 - loss: 0.1329

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9556 - loss: 0.1327

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9558 - loss: 0.1323

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9557 - loss: 0.1323

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9559 - loss: 0.1319

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9560 - loss: 0.1317

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9560 - loss: 0.1314

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9560 - loss: 0.1314

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9560 - loss: 0.1311

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9562 - loss: 0.1308

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9562 - loss: 0.1307

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9562 - loss: 0.1307

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9561 - loss: 0.1311

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9560 - loss: 0.1315

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9560 - loss: 0.1314

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9559 - loss: 0.1319

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9559 - loss: 0.1319

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9560 - loss: 0.1317

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9558 - loss: 0.1320

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9560 - loss: 0.1317

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9560 - loss: 0.1316

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9559 - loss: 0.1314

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9559 - loss: 0.1315

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9559 - loss: 0.1315

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9559 - loss: 0.1313

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9560 - loss: 0.1312

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9561 - loss: 0.1308

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9560 - loss: 0.1310

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9561 - loss: 0.1311

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9562 - loss: 0.1308

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9562 - loss: 0.1306

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9562 - loss: 0.1305

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9562 - loss: 0.1305

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9563 - loss: 0.1304

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9562 - loss: 0.1304

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9560 - loss: 0.1308

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9560 - loss: 0.1308

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9560 - loss: 0.1307

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9560 - loss: 0.1307

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9561 - loss: 0.1304

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9563 - loss: 0.1300

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9562 - loss: 0.1304

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9562 - loss: 0.1302

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9563 - loss: 0.1300

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9562 - loss: 0.1308

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9562 - loss: 0.1306

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9563 - loss: 0.1305

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9564 - loss: 0.1303

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9564 - loss: 0.1302

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9564 - loss: 0.1300

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9565 - loss: 0.1298

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9562 - loss: 0.1302

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9563 - loss: 0.1302

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9563 - loss: 0.1301

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9563 - loss: 0.1299

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9563 - loss: 0.1298

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9564 - loss: 0.1297

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9565 - loss: 0.1294

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9565 - loss: 0.1296

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9564 - loss: 0.1302

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9565 - loss: 0.1299

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9566 - loss: 0.1298

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9567 - loss: 0.1296

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9566 - loss: 0.1297

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9567 - loss: 0.1294

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9566 - loss: 0.1298

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9563 - loss: 0.1305

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9564 - loss: 0.1303

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9564 - loss: 0.1301

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9565 - loss: 0.1300

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9565 - loss: 0.1301

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9565 - loss: 0.1300

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9567 - loss: 0.1298

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9567 - loss: 0.1296

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9568 - loss: 0.1295

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9569 - loss: 0.1293

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9570 - loss: 0.1291

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9570 - loss: 0.1290

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9570 - loss: 0.1292

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9570 - loss: 0.1292

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9570 - loss: 0.1291

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9571 - loss: 0.1288

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9573 - loss: 0.1284

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9574 - loss: 0.1282

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9574 - loss: 0.1282

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9574 - loss: 0.1280

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9574 - loss: 0.1279

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9575 - loss: 0.1277

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9574 - loss: 0.1279

606/606 ━━━━━━━━━━━━━━━━━━━━ 28s 45ms/step - accuracy: 0.9575 - loss: 0.1278 - val_accuracy: 0.9581 - val_loss: 0.1733

Epoch 14/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 37s 62ms/step - accuracy: 1.0000 - loss: 0.0493

  3/606 ━━━━━━━━━━━━━━━━━━━━ 24s 40ms/step - accuracy: 0.9792 - loss: 0.0804

  5/606 ━━━━━━━━━━━━━━━━━━━━ 24s 40ms/step - accuracy: 0.9812 - loss: 0.0727

  7/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9732 - loss: 0.0736

  9/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9653 - loss: 0.0805

 11/606 ━━━━━━━━━━━━━━━━━━━━ 23s 39ms/step - accuracy: 0.9631 - loss: 0.0867

 13/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9615 - loss: 0.0872

 15/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9646 - loss: 0.0816

 17/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9669 - loss: 0.0841

 19/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9638 - loss: 0.0944

 21/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9643 - loss: 0.0918

 23/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9620 - loss: 0.0962

 25/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9625 - loss: 0.0959

 27/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9618 - loss: 0.1042

 29/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9591 - loss: 0.1134

 31/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9597 - loss: 0.1129

 33/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9621 - loss: 0.1088

 35/606 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - accuracy: 0.9634 - loss: 0.1054

 37/606 ━━━━━━━━━━━━━━━━━━━━ 23s 41ms/step - accuracy: 0.9628 - loss: 0.1126

 39/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9631 - loss: 0.1098

 41/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9619 - loss: 0.1113

 43/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9600 - loss: 0.1144

 45/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9590 - loss: 0.1168

 47/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9594 - loss: 0.1162

 49/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9585 - loss: 0.1157

 51/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9589 - loss: 0.1144

 53/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9599 - loss: 0.1135

 55/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9614 - loss: 0.1111

 57/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9627 - loss: 0.1096

 59/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9640 - loss: 0.1076

 61/606 ━━━━━━━━━━━━━━━━━━━━ 22s 40ms/step - accuracy: 0.9631 - loss: 0.1092

 63/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9628 - loss: 0.1113

 65/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9630 - loss: 0.1114

 67/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9627 - loss: 0.1125

 69/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9633 - loss: 0.1117

 71/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9635 - loss: 0.1128

 73/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9628 - loss: 0.1133

 75/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9629 - loss: 0.1118

 77/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9619 - loss: 0.1125

 79/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9620 - loss: 0.1119

 81/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9614 - loss: 0.1126

 83/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9608 - loss: 0.1136

 85/606 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - accuracy: 0.9599 - loss: 0.1163

 87/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9598 - loss: 0.1169

 89/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9600 - loss: 0.1157

 91/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9595 - loss: 0.1164

 93/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9600 - loss: 0.1157

 95/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9595 - loss: 0.1162

 97/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9597 - loss: 0.1157

 99/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9596 - loss: 0.1172

101/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9576 - loss: 0.1196

103/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9575 - loss: 0.1200

105/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9571 - loss: 0.1203

107/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9574 - loss: 0.1194

109/606 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.9579 - loss: 0.1191

111/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9569 - loss: 0.1250

113/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9574 - loss: 0.1237

115/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9573 - loss: 0.1241

117/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9581 - loss: 0.1227

119/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9582 - loss: 0.1239

121/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9582 - loss: 0.1238

123/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9586 - loss: 0.1227

125/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9590 - loss: 0.1223

127/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9596 - loss: 0.1209

129/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9595 - loss: 0.1206

131/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9597 - loss: 0.1213

133/606 ━━━━━━━━━━━━━━━━━━━━ 19s 40ms/step - accuracy: 0.9594 - loss: 0.1222

135/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9593 - loss: 0.1243

137/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9589 - loss: 0.1246

139/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9593 - loss: 0.1241

141/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9594 - loss: 0.1235

143/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9596 - loss: 0.1229

145/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9595 - loss: 0.1235

147/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9594 - loss: 0.1236

149/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9589 - loss: 0.1249

151/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9590 - loss: 0.1243

153/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9596 - loss: 0.1233

155/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9597 - loss: 0.1225

157/606 ━━━━━━━━━━━━━━━━━━━━ 18s 40ms/step - accuracy: 0.9600 - loss: 0.1229

159/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9597 - loss: 0.1225

161/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9600 - loss: 0.1219

163/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9594 - loss: 0.1239

165/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9587 - loss: 0.1250

167/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9585 - loss: 0.1256

169/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9588 - loss: 0.1261

171/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9587 - loss: 0.1266

173/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9586 - loss: 0.1265

175/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9588 - loss: 0.1260

177/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9589 - loss: 0.1257

179/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9588 - loss: 0.1254

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9584 - loss: 0.1264

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.9580 - loss: 0.1266

185/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9578 - loss: 0.1268

187/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9579 - loss: 0.1266

189/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9582 - loss: 0.1267

191/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9583 - loss: 0.1264

193/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9581 - loss: 0.1265

195/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9580 - loss: 0.1268

197/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9584 - loss: 0.1258

199/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9581 - loss: 0.1263

201/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9585 - loss: 0.1256

203/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9587 - loss: 0.1250

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9588 - loss: 0.1249

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - accuracy: 0.9591 - loss: 0.1242

209/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9592 - loss: 0.1247

211/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9591 - loss: 0.1253

213/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9592 - loss: 0.1251

215/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9590 - loss: 0.1251

217/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9588 - loss: 0.1252

219/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9588 - loss: 0.1250

221/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9589 - loss: 0.1260

223/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9589 - loss: 0.1261

225/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9590 - loss: 0.1260

227/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9591 - loss: 0.1255

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9589 - loss: 0.1258

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9587 - loss: 0.1259

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - accuracy: 0.9582 - loss: 0.1268

235/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9578 - loss: 0.1270

237/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9578 - loss: 0.1268

239/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9576 - loss: 0.1270

241/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9576 - loss: 0.1267

243/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9577 - loss: 0.1265

245/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9575 - loss: 0.1266

247/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9576 - loss: 0.1263

249/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9578 - loss: 0.1258

251/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9578 - loss: 0.1257

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9575 - loss: 0.1264

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9574 - loss: 0.1266

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - accuracy: 0.9577 - loss: 0.1261

259/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9575 - loss: 0.1266

261/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9575 - loss: 0.1266

263/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9576 - loss: 0.1263

265/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9575 - loss: 0.1268

267/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9579 - loss: 0.1261

269/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9581 - loss: 0.1257

271/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9583 - loss: 0.1254

273/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9580 - loss: 0.1257

275/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9578 - loss: 0.1257

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9575 - loss: 0.1261

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9572 - loss: 0.1272

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9573 - loss: 0.1271

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 40ms/step - accuracy: 0.9570 - loss: 0.1274

285/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9572 - loss: 0.1271

287/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9571 - loss: 0.1276

289/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9574 - loss: 0.1270

291/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9573 - loss: 0.1272

293/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9571 - loss: 0.1280

295/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9569 - loss: 0.1281

297/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9572 - loss: 0.1276

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9575 - loss: 0.1269

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9575 - loss: 0.1269

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9574 - loss: 0.1272

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9572 - loss: 0.1272

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.9569 - loss: 0.1273

309/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9569 - loss: 0.1279

311/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9570 - loss: 0.1277

313/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9572 - loss: 0.1274

315/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9570 - loss: 0.1278

317/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9571 - loss: 0.1276

319/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9571 - loss: 0.1274

321/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9570 - loss: 0.1274

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9568 - loss: 0.1277

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9568 - loss: 0.1279

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9569 - loss: 0.1274

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9568 - loss: 0.1279

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9569 - loss: 0.1282

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - accuracy: 0.9569 - loss: 0.1282

335/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9570 - loss: 0.1281

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9573 - loss: 0.1275

339/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9570 - loss: 0.1278

341/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9569 - loss: 0.1281

343/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9569 - loss: 0.1282

345/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9571 - loss: 0.1279

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9571 - loss: 0.1275

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9573 - loss: 0.1272

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9574 - loss: 0.1273

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9574 - loss: 0.1272

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9573 - loss: 0.1272

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9575 - loss: 0.1267

359/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9577 - loss: 0.1262

361/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9578 - loss: 0.1258

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9578 - loss: 0.1258

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9578 - loss: 0.1257

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9577 - loss: 0.1264

369/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9577 - loss: 0.1265

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9577 - loss: 0.1272

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9577 - loss: 0.1271

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9578 - loss: 0.1270

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9576 - loss: 0.1272

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9579 - loss: 0.1267

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 40ms/step - accuracy: 0.9577 - loss: 0.1271

383/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9577 - loss: 0.1269

385/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9575 - loss: 0.1269

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9577 - loss: 0.1267

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9575 - loss: 0.1267

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9573 - loss: 0.1272

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9575 - loss: 0.1267

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9575 - loss: 0.1271

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9576 - loss: 0.1270

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9576 - loss: 0.1267

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9575 - loss: 0.1269

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9574 - loss: 0.1270

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9574 - loss: 0.1269

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.9573 - loss: 0.1269

409/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9573 - loss: 0.1268

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9573 - loss: 0.1268

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9573 - loss: 0.1268

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9572 - loss: 0.1267

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9571 - loss: 0.1267

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9572 - loss: 0.1266

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9574 - loss: 0.1262

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9575 - loss: 0.1259

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9576 - loss: 0.1258

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9577 - loss: 0.1256

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9578 - loss: 0.1268

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 40ms/step - accuracy: 0.9579 - loss: 0.1264

433/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9581 - loss: 0.1260

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9581 - loss: 0.1259

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9580 - loss: 0.1260

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9581 - loss: 0.1256

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9580 - loss: 0.1257

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9576 - loss: 0.1262

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9577 - loss: 0.1261

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9578 - loss: 0.1258

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9579 - loss: 0.1256

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9581 - loss: 0.1252

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9581 - loss: 0.1250

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9582 - loss: 0.1248

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9582 - loss: 0.1249

459/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9582 - loss: 0.1249

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9581 - loss: 0.1251

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9581 - loss: 0.1253

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9581 - loss: 0.1254

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9582 - loss: 0.1253

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9580 - loss: 0.1255

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9579 - loss: 0.1256

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9578 - loss: 0.1256

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9579 - loss: 0.1253

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9579 - loss: 0.1254

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9579 - loss: 0.1254

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.9580 - loss: 0.1252

483/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9581 - loss: 0.1248

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9583 - loss: 0.1244

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9583 - loss: 0.1246

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9582 - loss: 0.1247

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9582 - loss: 0.1246

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9582 - loss: 0.1246

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9582 - loss: 0.1244

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9582 - loss: 0.1242

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9582 - loss: 0.1242

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9581 - loss: 0.1249

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9582 - loss: 0.1247

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9582 - loss: 0.1246

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9581 - loss: 0.1247

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9582 - loss: 0.1247

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9584 - loss: 0.1243

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9584 - loss: 0.1243

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9584 - loss: 0.1243

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9584 - loss: 0.1241

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9583 - loss: 0.1243

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9584 - loss: 0.1241

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9584 - loss: 0.1243

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9585 - loss: 0.1241

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9586 - loss: 0.1239

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9586 - loss: 0.1239

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.9586 - loss: 0.1238

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9586 - loss: 0.1241

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9586 - loss: 0.1240

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9587 - loss: 0.1238

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9587 - loss: 0.1237

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9588 - loss: 0.1238

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9589 - loss: 0.1235

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9590 - loss: 0.1233

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9590 - loss: 0.1234

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9590 - loss: 0.1232

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9592 - loss: 0.1229

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9591 - loss: 0.1228

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.9591 - loss: 0.1232

557/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9590 - loss: 0.1233

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9590 - loss: 0.1232

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9591 - loss: 0.1230

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9589 - loss: 0.1233

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9588 - loss: 0.1234

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9588 - loss: 0.1233

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9589 - loss: 0.1232

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9590 - loss: 0.1231

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9590 - loss: 0.1229

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9590 - loss: 0.1230

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9591 - loss: 0.1227

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9592 - loss: 0.1225

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9591 - loss: 0.1226

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9592 - loss: 0.1226

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9592 - loss: 0.1223

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9593 - loss: 0.1222

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9591 - loss: 0.1225

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9591 - loss: 0.1225

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9592 - loss: 0.1222

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9592 - loss: 0.1221

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9593 - loss: 0.1219

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9593 - loss: 0.1218

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9593 - loss: 0.1218

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9594 - loss: 0.1215

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9595 - loss: 0.1213

606/606 ━━━━━━━━━━━━━━━━━━━━ 28s 45ms/step - accuracy: 0.9595 - loss: 0.1212 - val_accuracy: 0.9579 - val_loss: 0.1679

Epoch 15/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 1.0000 - loss: 0.0268

  3/606 ━━━━━━━━━━━━━━━━━━━━ 27s 45ms/step - accuracy: 0.9688 - loss: 0.0765

  5/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9750 - loss: 0.0842

  7/606 ━━━━━━━━━━━━━━━━━━━━ 26s 43ms/step - accuracy: 0.9732 - loss: 0.0810

  9/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9722 - loss: 0.0742

 11/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9659 - loss: 0.0955

 13/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9663 - loss: 0.0890

 15/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9688 - loss: 0.0845

 17/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9651 - loss: 0.0897

 19/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9671 - loss: 0.0902

 21/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9688 - loss: 0.0858

 23/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9688 - loss: 0.0862

 25/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9675 - loss: 0.0878

 27/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9688 - loss: 0.0859

 29/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9698 - loss: 0.0834

 31/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9698 - loss: 0.0962

 33/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9716 - loss: 0.0920

 35/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9714 - loss: 0.0925

 37/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9721 - loss: 0.0909

 39/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9720 - loss: 0.0929

 41/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9688 - loss: 0.0970

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9695 - loss: 0.0940

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9694 - loss: 0.0984

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9681 - loss: 0.1014

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9675 - loss: 0.1027

 51/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9669 - loss: 0.1023

 53/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9664 - loss: 0.1036

 55/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9659 - loss: 0.1052

 57/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9649 - loss: 0.1040

 59/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9645 - loss: 0.1037

 61/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9641 - loss: 0.1029

 63/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9643 - loss: 0.1033

 65/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9649 - loss: 0.1019

 67/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9646 - loss: 0.1034

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9647 - loss: 0.1028

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9635 - loss: 0.1052

 73/606 ━━━━━━━━━━━━━━━━━━━━ 22s 41ms/step - accuracy: 0.9645 - loss: 0.1035

 75/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9633 - loss: 0.1095

 77/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9635 - loss: 0.1125

 79/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9624 - loss: 0.1138

 81/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9618 - loss: 0.1149

 83/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9612 - loss: 0.1152

 85/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9607 - loss: 0.1157

 87/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9612 - loss: 0.1150

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9600 - loss: 0.1183

 91/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9595 - loss: 0.1186

 93/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9587 - loss: 0.1198

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.9595 - loss: 0.1183

 97/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9601 - loss: 0.1172

 99/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9599 - loss: 0.1172

101/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9598 - loss: 0.1175

103/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9596 - loss: 0.1180

105/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9592 - loss: 0.1184

107/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9588 - loss: 0.1188

109/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9584 - loss: 0.1236

111/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9581 - loss: 0.1258

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9566 - loss: 0.1317

115/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9565 - loss: 0.1316

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9562 - loss: 0.1325

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.9559 - loss: 0.1334

121/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9566 - loss: 0.1316

123/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9568 - loss: 0.1314

125/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9563 - loss: 0.1319

127/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9562 - loss: 0.1318

129/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9562 - loss: 0.1314

131/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9563 - loss: 0.1308

133/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9558 - loss: 0.1327

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9558 - loss: 0.1323

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9562 - loss: 0.1314

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9562 - loss: 0.1308

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9563 - loss: 0.1301

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 41ms/step - accuracy: 0.9563 - loss: 0.1302

145/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9560 - loss: 0.1301

147/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9562 - loss: 0.1310

149/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9557 - loss: 0.1317

151/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9561 - loss: 0.1310

153/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9563 - loss: 0.1307

155/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9565 - loss: 0.1301

157/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9564 - loss: 0.1297

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9560 - loss: 0.1303

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9556 - loss: 0.1307

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9551 - loss: 0.1316

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9549 - loss: 0.1318

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 41ms/step - accuracy: 0.9551 - loss: 0.1318

169/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9551 - loss: 0.1315

171/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9549 - loss: 0.1326

173/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9547 - loss: 0.1326

175/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9548 - loss: 0.1321

177/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9548 - loss: 0.1321

179/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9548 - loss: 0.1325

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9549 - loss: 0.1328

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9549 - loss: 0.1332

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9549 - loss: 0.1331

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9552 - loss: 0.1321

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9554 - loss: 0.1314

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 41ms/step - accuracy: 0.9555 - loss: 0.1309

193/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9556 - loss: 0.1309

195/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9559 - loss: 0.1302

197/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9559 - loss: 0.1298

199/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9562 - loss: 0.1289

201/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9562 - loss: 0.1290

203/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9564 - loss: 0.1283

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9564 - loss: 0.1285

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9565 - loss: 0.1280

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9565 - loss: 0.1278

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9560 - loss: 0.1284

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9558 - loss: 0.1286

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9560 - loss: 0.1283

217/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9561 - loss: 0.1297

219/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9562 - loss: 0.1297

221/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9560 - loss: 0.1297

223/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9560 - loss: 0.1294

225/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9558 - loss: 0.1297

227/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9557 - loss: 0.1299

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9558 - loss: 0.1295

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9559 - loss: 0.1292

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9559 - loss: 0.1293

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9557 - loss: 0.1298

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9557 - loss: 0.1295

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9555 - loss: 0.1298

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9551 - loss: 0.1305

243/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9552 - loss: 0.1302

245/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9555 - loss: 0.1298

247/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9556 - loss: 0.1295

249/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9556 - loss: 0.1292

251/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9554 - loss: 0.1294

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9553 - loss: 0.1293

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9555 - loss: 0.1288

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9555 - loss: 0.1286

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9554 - loss: 0.1285

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9557 - loss: 0.1279

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9554 - loss: 0.1284

265/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9555 - loss: 0.1280

267/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9556 - loss: 0.1279

269/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9554 - loss: 0.1277

271/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9556 - loss: 0.1272

273/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9554 - loss: 0.1283

275/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9556 - loss: 0.1278

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9554 - loss: 0.1281

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9553 - loss: 0.1283

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9555 - loss: 0.1278

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9554 - loss: 0.1277

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9553 - loss: 0.1279

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9549 - loss: 0.1284

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9548 - loss: 0.1283

291/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9548 - loss: 0.1284

293/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9548 - loss: 0.1284

295/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9547 - loss: 0.1287

297/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9548 - loss: 0.1288

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9546 - loss: 0.1290

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9545 - loss: 0.1291

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9548 - loss: 0.1286

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9549 - loss: 0.1284

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9551 - loss: 0.1279

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9553 - loss: 0.1276

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9554 - loss: 0.1276

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9557 - loss: 0.1271

315/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9559 - loss: 0.1265

317/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9560 - loss: 0.1261

319/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9561 - loss: 0.1258

321/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9562 - loss: 0.1257

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9564 - loss: 0.1257

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9563 - loss: 0.1260

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9563 - loss: 0.1262

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9563 - loss: 0.1261

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9562 - loss: 0.1262

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9563 - loss: 0.1259

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9563 - loss: 0.1259

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9564 - loss: 0.1260

339/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9563 - loss: 0.1258

341/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9564 - loss: 0.1256

343/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9565 - loss: 0.1253

345/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9563 - loss: 0.1260

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9563 - loss: 0.1260

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9566 - loss: 0.1254

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9562 - loss: 0.1258

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9562 - loss: 0.1260

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9564 - loss: 0.1258

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9564 - loss: 0.1259

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9567 - loss: 0.1254

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9568 - loss: 0.1252

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9569 - loss: 0.1249

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9568 - loss: 0.1253

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9568 - loss: 0.1254

369/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9568 - loss: 0.1255

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9569 - loss: 0.1254

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9569 - loss: 0.1253

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9569 - loss: 0.1251

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9568 - loss: 0.1252

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9569 - loss: 0.1249

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9570 - loss: 0.1247

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9571 - loss: 0.1244

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9570 - loss: 0.1242

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9569 - loss: 0.1247

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9570 - loss: 0.1243

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9569 - loss: 0.1248

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9571 - loss: 0.1247

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9573 - loss: 0.1242

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9573 - loss: 0.1244

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9572 - loss: 0.1245

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9574 - loss: 0.1242

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9575 - loss: 0.1239

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9573 - loss: 0.1248

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9574 - loss: 0.1244

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9572 - loss: 0.1246

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9571 - loss: 0.1249

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9572 - loss: 0.1247

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9572 - loss: 0.1247

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9570 - loss: 0.1248

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9571 - loss: 0.1246

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9572 - loss: 0.1251

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9571 - loss: 0.1252

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9573 - loss: 0.1248

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9573 - loss: 0.1247

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9573 - loss: 0.1245

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9575 - loss: 0.1240

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9575 - loss: 0.1239

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9575 - loss: 0.1237

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9574 - loss: 0.1241

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9575 - loss: 0.1238

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9576 - loss: 0.1236

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9576 - loss: 0.1238

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9577 - loss: 0.1236

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9578 - loss: 0.1232

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9578 - loss: 0.1229

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9579 - loss: 0.1228

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9578 - loss: 0.1232

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9578 - loss: 0.1230

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9578 - loss: 0.1230

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9579 - loss: 0.1228

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9578 - loss: 0.1227

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9576 - loss: 0.1235

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9575 - loss: 0.1234

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9575 - loss: 0.1234

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9577 - loss: 0.1232

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9578 - loss: 0.1230

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9578 - loss: 0.1231

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9577 - loss: 0.1230

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9577 - loss: 0.1228

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9577 - loss: 0.1230

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9578 - loss: 0.1227

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9579 - loss: 0.1224

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9580 - loss: 0.1221

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9580 - loss: 0.1220

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9580 - loss: 0.1220

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9581 - loss: 0.1217

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9582 - loss: 0.1215

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9580 - loss: 0.1219

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9582 - loss: 0.1216

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9582 - loss: 0.1219

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9581 - loss: 0.1224

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9581 - loss: 0.1223

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9580 - loss: 0.1223

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9580 - loss: 0.1223

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9580 - loss: 0.1222

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9579 - loss: 0.1223

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9578 - loss: 0.1224

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9578 - loss: 0.1225

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9579 - loss: 0.1223

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9577 - loss: 0.1228

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9578 - loss: 0.1226

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9579 - loss: 0.1226

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9579 - loss: 0.1225

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9579 - loss: 0.1225

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9579 - loss: 0.1229

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9579 - loss: 0.1228

533/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9578 - loss: 0.1227

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9577 - loss: 0.1230

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9578 - loss: 0.1228

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9577 - loss: 0.1229

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9578 - loss: 0.1227

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9579 - loss: 0.1224

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9577 - loss: 0.1226

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9577 - loss: 0.1234

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9578 - loss: 0.1232

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9579 - loss: 0.1230

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9578 - loss: 0.1232

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9579 - loss: 0.1230

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9580 - loss: 0.1228

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9581 - loss: 0.1225

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9581 - loss: 0.1225

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9580 - loss: 0.1227

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9581 - loss: 0.1224

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9582 - loss: 0.1221

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9582 - loss: 0.1221

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9582 - loss: 0.1220

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9581 - loss: 0.1224

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9582 - loss: 0.1220

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9583 - loss: 0.1218

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9583 - loss: 0.1218

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9582 - loss: 0.1223

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9584 - loss: 0.1221

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9584 - loss: 0.1219

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9584 - loss: 0.1219

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9584 - loss: 0.1218

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9585 - loss: 0.1215

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9585 - loss: 0.1214

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9586 - loss: 0.1212

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9586 - loss: 0.1210

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9587 - loss: 0.1208

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9588 - loss: 0.1207

602/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9588 - loss: 0.1205

604/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9589 - loss: 0.1205

606/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9589 - loss: 0.1204

606/606 ━━━━━━━━━━━━━━━━━━━━ 28s 46ms/step - accuracy: 0.9589 - loss: 0.1204 - val_accuracy: 0.9632 - val_loss: 0.1600

Epoch 16/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 42s 70ms/step - accuracy: 0.9688 - loss: 0.0447

  3/606 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.9792 - loss: 0.0486

  5/606 ━━━━━━━━━━━━━━━━━━━━ 28s 48ms/step - accuracy: 0.9812 - loss: 0.0515

  7/606 ━━━━━━━━━━━━━━━━━━━━ 27s 46ms/step - accuracy: 0.9821 - loss: 0.0503

  9/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9861 - loss: 0.0435

 11/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9716 - loss: 0.0663

 13/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9688 - loss: 0.0719

 15/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9646 - loss: 0.0806

 17/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9688 - loss: 0.0739

 19/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9671 - loss: 0.0926

 21/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9658 - loss: 0.0985

 23/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9633 - loss: 0.1032

 25/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9638 - loss: 0.1069

 27/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9618 - loss: 0.1104

 29/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9644 - loss: 0.1053

 31/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9647 - loss: 0.1080

 33/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9650 - loss: 0.1066

 35/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9661 - loss: 0.1055

 37/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9662 - loss: 0.1056

 39/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9663 - loss: 0.1042

 41/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9657 - loss: 0.1067

 43/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9658 - loss: 0.1050

 45/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9660 - loss: 0.1050

 47/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9668 - loss: 0.1035

 49/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9681 - loss: 0.1011

 51/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9669 - loss: 0.1023

 53/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9670 - loss: 0.1018

 55/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9659 - loss: 0.1047

 57/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9666 - loss: 0.1038

 59/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9666 - loss: 0.1045

 61/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9667 - loss: 0.1037

 63/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9673 - loss: 0.1027

 65/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9654 - loss: 0.1070

 67/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9660 - loss: 0.1053

 69/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9665 - loss: 0.1043

 71/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9657 - loss: 0.1081

 73/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9662 - loss: 0.1080

 75/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9663 - loss: 0.1085

 77/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9663 - loss: 0.1078

 79/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9664 - loss: 0.1072

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9668 - loss: 0.1054

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9657 - loss: 0.1107

 85/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9658 - loss: 0.1098

 87/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9648 - loss: 0.1110

 89/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9642 - loss: 0.1116

 91/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9650 - loss: 0.1096

 93/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9644 - loss: 0.1108

 95/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9641 - loss: 0.1097

 97/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9646 - loss: 0.1083

 99/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9653 - loss: 0.1069

101/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9647 - loss: 0.1079

103/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9651 - loss: 0.1069

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9643 - loss: 0.1100

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9647 - loss: 0.1092

109/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9642 - loss: 0.1109

111/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9640 - loss: 0.1158

113/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9646 - loss: 0.1143

115/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9641 - loss: 0.1151

117/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9639 - loss: 0.1151

119/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9640 - loss: 0.1164

121/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9641 - loss: 0.1165

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9639 - loss: 0.1162

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9638 - loss: 0.1158

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9641 - loss: 0.1153

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9639 - loss: 0.1169

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9635 - loss: 0.1181

133/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9631 - loss: 0.1195

135/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9632 - loss: 0.1197

137/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9637 - loss: 0.1187

139/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9636 - loss: 0.1186

141/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9637 - loss: 0.1182

143/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9635 - loss: 0.1180

145/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9640 - loss: 0.1170

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9636 - loss: 0.1168

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9637 - loss: 0.1160

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9636 - loss: 0.1162

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9641 - loss: 0.1152

155/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9641 - loss: 0.1146

157/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9638 - loss: 0.1153

159/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9636 - loss: 0.1156

161/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9633 - loss: 0.1160

163/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9636 - loss: 0.1155

165/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9634 - loss: 0.1154

167/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9628 - loss: 0.1176

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9625 - loss: 0.1179

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9618 - loss: 0.1187

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9610 - loss: 0.1204

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9609 - loss: 0.1205

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9606 - loss: 0.1204

179/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9609 - loss: 0.1198

181/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9606 - loss: 0.1195

183/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9611 - loss: 0.1185

185/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9615 - loss: 0.1178

187/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9616 - loss: 0.1179

189/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9615 - loss: 0.1178

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9616 - loss: 0.1186

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9619 - loss: 0.1177

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9617 - loss: 0.1179

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9618 - loss: 0.1175

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9615 - loss: 0.1176

201/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9619 - loss: 0.1168

203/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9623 - loss: 0.1160

205/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9623 - loss: 0.1162

207/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9624 - loss: 0.1163

209/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9623 - loss: 0.1163

211/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9625 - loss: 0.1157

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9624 - loss: 0.1156

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9624 - loss: 0.1156

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9623 - loss: 0.1167

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9622 - loss: 0.1170

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9620 - loss: 0.1174

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9622 - loss: 0.1168

225/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9617 - loss: 0.1180

227/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9617 - loss: 0.1175

229/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9617 - loss: 0.1175

231/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9614 - loss: 0.1182

233/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9612 - loss: 0.1185

235/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9614 - loss: 0.1183

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9612 - loss: 0.1191

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9612 - loss: 0.1188

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9608 - loss: 0.1196

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9609 - loss: 0.1194

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9607 - loss: 0.1194

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9608 - loss: 0.1193

249/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9607 - loss: 0.1193

251/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9608 - loss: 0.1193

253/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9606 - loss: 0.1193

255/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9607 - loss: 0.1189

257/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9610 - loss: 0.1182

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9611 - loss: 0.1177

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9611 - loss: 0.1186

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9611 - loss: 0.1182

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9612 - loss: 0.1178

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9615 - loss: 0.1174

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9611 - loss: 0.1176

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9609 - loss: 0.1177

273/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9612 - loss: 0.1171

275/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9611 - loss: 0.1172

277/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9612 - loss: 0.1170

279/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9610 - loss: 0.1175

281/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9611 - loss: 0.1175

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9610 - loss: 0.1177

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9607 - loss: 0.1181

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9607 - loss: 0.1184

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9605 - loss: 0.1185

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9604 - loss: 0.1188

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9604 - loss: 0.1186

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9606 - loss: 0.1188

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9606 - loss: 0.1188

299/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9604 - loss: 0.1190

301/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9602 - loss: 0.1193

303/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9602 - loss: 0.1195

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9602 - loss: 0.1193

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9604 - loss: 0.1188

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9604 - loss: 0.1188

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9605 - loss: 0.1186

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9604 - loss: 0.1189

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9605 - loss: 0.1185

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9605 - loss: 0.1185

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9605 - loss: 0.1184

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9604 - loss: 0.1183

323/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9603 - loss: 0.1183

325/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9604 - loss: 0.1181

327/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9604 - loss: 0.1179

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9606 - loss: 0.1176

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9607 - loss: 0.1172

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9610 - loss: 0.1167

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9609 - loss: 0.1167

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9609 - loss: 0.1166

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9610 - loss: 0.1163

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9606 - loss: 0.1179

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9606 - loss: 0.1177

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9605 - loss: 0.1178

347/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9604 - loss: 0.1180

349/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9604 - loss: 0.1178

351/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9603 - loss: 0.1184

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9604 - loss: 0.1187

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9604 - loss: 0.1186

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9605 - loss: 0.1184

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9606 - loss: 0.1181

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9604 - loss: 0.1183

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9606 - loss: 0.1179

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9605 - loss: 0.1185

366/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9606 - loss: 0.1182

368/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9605 - loss: 0.1187

370/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9605 - loss: 0.1187

372/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9606 - loss: 0.1183

374/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9603 - loss: 0.1187

376/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9604 - loss: 0.1184

378/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9606 - loss: 0.1181

380/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9605 - loss: 0.1180

382/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9606 - loss: 0.1179

384/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9604 - loss: 0.1181

386/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9603 - loss: 0.1183

388/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9605 - loss: 0.1181

390/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9606 - loss: 0.1177

392/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9605 - loss: 0.1178

394/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9607 - loss: 0.1173

396/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9606 - loss: 0.1175

398/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9606 - loss: 0.1174

400/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9604 - loss: 0.1180

402/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9605 - loss: 0.1176

404/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9606 - loss: 0.1174

406/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9607 - loss: 0.1176

408/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9606 - loss: 0.1182

410/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9607 - loss: 0.1180

412/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9603 - loss: 0.1183

414/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9601 - loss: 0.1186

416/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9600 - loss: 0.1186

418/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9596 - loss: 0.1195

420/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9598 - loss: 0.1192

422/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9599 - loss: 0.1191

424/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9600 - loss: 0.1188

426/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9600 - loss: 0.1187

428/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9602 - loss: 0.1183

430/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9603 - loss: 0.1181

432/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9603 - loss: 0.1182

434/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9603 - loss: 0.1182

436/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9605 - loss: 0.1178

438/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9605 - loss: 0.1175

440/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9606 - loss: 0.1174

442/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9604 - loss: 0.1178

444/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9604 - loss: 0.1177

446/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9603 - loss: 0.1179

448/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9602 - loss: 0.1182

450/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9602 - loss: 0.1180

452/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9602 - loss: 0.1181

454/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9603 - loss: 0.1179

456/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9604 - loss: 0.1176

458/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9604 - loss: 0.1174

460/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9606 - loss: 0.1170

462/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9602 - loss: 0.1178

464/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9602 - loss: 0.1177

466/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9602 - loss: 0.1177

468/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9602 - loss: 0.1180

470/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9602 - loss: 0.1181

472/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9603 - loss: 0.1181

474/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9603 - loss: 0.1180

476/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9603 - loss: 0.1178

478/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9603 - loss: 0.1176

480/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9604 - loss: 0.1173

482/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9605 - loss: 0.1171

484/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9605 - loss: 0.1172

486/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9604 - loss: 0.1173

488/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9603 - loss: 0.1174

490/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9603 - loss: 0.1172

492/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9604 - loss: 0.1169

494/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9603 - loss: 0.1169

496/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9603 - loss: 0.1171

498/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9602 - loss: 0.1171

500/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9602 - loss: 0.1171

502/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9603 - loss: 0.1168

504/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9603 - loss: 0.1169

506/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9604 - loss: 0.1166

508/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9605 - loss: 0.1164

510/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9605 - loss: 0.1164

512/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9603 - loss: 0.1170

514/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9602 - loss: 0.1171

516/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9604 - loss: 0.1168

518/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9604 - loss: 0.1167

520/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9605 - loss: 0.1166

522/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9605 - loss: 0.1166

524/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9605 - loss: 0.1165

526/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9607 - loss: 0.1161

528/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9606 - loss: 0.1164

530/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9607 - loss: 0.1167

532/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9608 - loss: 0.1163

534/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9609 - loss: 0.1162

536/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9608 - loss: 0.1165

538/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9607 - loss: 0.1166

540/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9606 - loss: 0.1167

542/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9607 - loss: 0.1167

544/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9607 - loss: 0.1168

546/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9607 - loss: 0.1167

548/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9607 - loss: 0.1166

550/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9608 - loss: 0.1164

552/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9608 - loss: 0.1162

554/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9608 - loss: 0.1162

556/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9608 - loss: 0.1160

558/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9609 - loss: 0.1160

560/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9608 - loss: 0.1164

562/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9608 - loss: 0.1162

564/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9608 - loss: 0.1161

566/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9606 - loss: 0.1165

568/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9607 - loss: 0.1163

570/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9608 - loss: 0.1161

572/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9609 - loss: 0.1160

574/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9610 - loss: 0.1158

576/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9611 - loss: 0.1154

578/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9612 - loss: 0.1152

580/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9611 - loss: 0.1152

582/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9610 - loss: 0.1154

584/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9610 - loss: 0.1156

586/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9610 - loss: 0.1155

588/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9612 - loss: 0.1153

590/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9612 - loss: 0.1152

592/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9611 - loss: 0.1151

594/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9612 - loss: 0.1149

596/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9613 - loss: 0.1148

598/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9613 - loss: 0.1148

600/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9614 - loss: 0.1147

602/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9615 - loss: 0.1145

604/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9616 - loss: 0.1142

606/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9616 - loss: 0.1141

606/606 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.9616 - loss: 0.1141 - val_accuracy: 0.9567 - val_loss: 0.1477

Epoch 17/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 38s 64ms/step - accuracy: 1.0000 - loss: 0.0091

  3/606 ━━━━━━━━━━━━━━━━━━━━ 27s 45ms/step - accuracy: 0.9896 - loss: 0.0392

  5/606 ━━━━━━━━━━━━━━━━━━━━ 27s 45ms/step - accuracy: 0.9812 - loss: 0.0479

  7/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9777 - loss: 0.0687

  9/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9826 - loss: 0.0565

 11/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9830 - loss: 0.0523

 13/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9760 - loss: 0.0653

 15/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9708 - loss: 0.0720

 17/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9724 - loss: 0.0701

 19/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9688 - loss: 0.0738

 21/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9702 - loss: 0.0831

 23/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9674 - loss: 0.0940

 25/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9675 - loss: 0.0926

 27/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9688 - loss: 0.0895

 29/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9709 - loss: 0.0848

 31/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9718 - loss: 0.0848

 33/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9725 - loss: 0.0851

 35/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9723 - loss: 0.0845

 37/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9704 - loss: 0.0860

 39/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9712 - loss: 0.0878

 41/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9710 - loss: 0.0888

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9695 - loss: 0.0906

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9708 - loss: 0.0875

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9701 - loss: 0.0883

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9668 - loss: 0.0934

 51/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9669 - loss: 0.0952

 53/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9664 - loss: 0.0974

 55/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9676 - loss: 0.0952

 57/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9688 - loss: 0.0928

 59/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9682 - loss: 0.0950

 61/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9693 - loss: 0.0933

 63/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9697 - loss: 0.0924

 65/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9697 - loss: 0.0931

 67/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9701 - loss: 0.0926

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9688 - loss: 0.0945

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9692 - loss: 0.0946

 73/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9700 - loss: 0.0935

 75/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9708 - loss: 0.0919

 77/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9700 - loss: 0.0973

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9695 - loss: 0.0975

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9703 - loss: 0.0959

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9699 - loss: 0.0968

 85/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9695 - loss: 0.0970

 87/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9695 - loss: 0.0975

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9695 - loss: 0.0987

 91/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9691 - loss: 0.0991

 93/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9691 - loss: 0.0982

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9688 - loss: 0.0980

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9681 - loss: 0.1001

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9684 - loss: 0.0993

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9684 - loss: 0.0995

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9688 - loss: 0.0986

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9688 - loss: 0.0987

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9685 - loss: 0.0996

109/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9685 - loss: 0.1002

111/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9679 - loss: 0.1052

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9671 - loss: 0.1076

115/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9668 - loss: 0.1086

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9663 - loss: 0.1099

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9664 - loss: 0.1098

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9667 - loss: 0.1085

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9665 - loss: 0.1081

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9665 - loss: 0.1081

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9668 - loss: 0.1098

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9671 - loss: 0.1090

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9671 - loss: 0.1085

133/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9671 - loss: 0.1088

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9667 - loss: 0.1098

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9665 - loss: 0.1102

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9665 - loss: 0.1099

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9659 - loss: 0.1108

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9661 - loss: 0.1099

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9666 - loss: 0.1090

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9666 - loss: 0.1094

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9669 - loss: 0.1091

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9673 - loss: 0.1082

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9669 - loss: 0.1086

155/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9667 - loss: 0.1087

157/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9666 - loss: 0.1093

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9666 - loss: 0.1091

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9666 - loss: 0.1088

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9663 - loss: 0.1102

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9663 - loss: 0.1101

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9663 - loss: 0.1099

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9658 - loss: 0.1108

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9658 - loss: 0.1104

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9653 - loss: 0.1115

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9650 - loss: 0.1126

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9650 - loss: 0.1127

179/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9651 - loss: 0.1122

181/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9651 - loss: 0.1118

183/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9648 - loss: 0.1126

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9645 - loss: 0.1133

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9644 - loss: 0.1134

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9646 - loss: 0.1127

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9643 - loss: 0.1126

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9644 - loss: 0.1123

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9646 - loss: 0.1119

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9643 - loss: 0.1130

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9647 - loss: 0.1123

201/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9650 - loss: 0.1116

203/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9649 - loss: 0.1118

205/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9649 - loss: 0.1114

207/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9651 - loss: 0.1114

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9649 - loss: 0.1123

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9650 - loss: 0.1117

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9649 - loss: 0.1121

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9648 - loss: 0.1134

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9647 - loss: 0.1138

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9650 - loss: 0.1132

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9651 - loss: 0.1131

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9651 - loss: 0.1130

225/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9650 - loss: 0.1132

227/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9650 - loss: 0.1132

229/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9649 - loss: 0.1132

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9647 - loss: 0.1133

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9647 - loss: 0.1131

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9646 - loss: 0.1132

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9644 - loss: 0.1133

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9639 - loss: 0.1141

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9638 - loss: 0.1139

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9637 - loss: 0.1138

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9635 - loss: 0.1141

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9634 - loss: 0.1139

249/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9635 - loss: 0.1140

251/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9634 - loss: 0.1143

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9633 - loss: 0.1140

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9630 - loss: 0.1143

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9628 - loss: 0.1144

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9630 - loss: 0.1140

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9629 - loss: 0.1137

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9627 - loss: 0.1142

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9626 - loss: 0.1142

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9624 - loss: 0.1145

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9622 - loss: 0.1146

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9623 - loss: 0.1144

273/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9623 - loss: 0.1144

275/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9623 - loss: 0.1143

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9624 - loss: 0.1143

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9624 - loss: 0.1144

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9625 - loss: 0.1141

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9620 - loss: 0.1153

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9621 - loss: 0.1152

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9620 - loss: 0.1151

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9619 - loss: 0.1153

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9619 - loss: 0.1151

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9619 - loss: 0.1149

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9620 - loss: 0.1148

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9620 - loss: 0.1146

299/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9622 - loss: 0.1141

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9621 - loss: 0.1141

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9621 - loss: 0.1138

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9621 - loss: 0.1138

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9623 - loss: 0.1134

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9624 - loss: 0.1132

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9625 - loss: 0.1131

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9623 - loss: 0.1136

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9623 - loss: 0.1133

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9618 - loss: 0.1141

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9621 - loss: 0.1137

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9622 - loss: 0.1137

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9623 - loss: 0.1134

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9622 - loss: 0.1134

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9623 - loss: 0.1133

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9624 - loss: 0.1131

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9625 - loss: 0.1135

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9627 - loss: 0.1133

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9628 - loss: 0.1130

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9627 - loss: 0.1136

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9627 - loss: 0.1134

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9625 - loss: 0.1141

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9626 - loss: 0.1140

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9627 - loss: 0.1137

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9628 - loss: 0.1135

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9628 - loss: 0.1136

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9627 - loss: 0.1137

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9628 - loss: 0.1135

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9628 - loss: 0.1134

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9629 - loss: 0.1130

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9629 - loss: 0.1129

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9630 - loss: 0.1124

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9630 - loss: 0.1131

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9631 - loss: 0.1128

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9632 - loss: 0.1126

369/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9630 - loss: 0.1129

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9628 - loss: 0.1133

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9626 - loss: 0.1136

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9625 - loss: 0.1137

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9623 - loss: 0.1139

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9622 - loss: 0.1139

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9622 - loss: 0.1138

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9623 - loss: 0.1135

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9622 - loss: 0.1138

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9622 - loss: 0.1141

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9623 - loss: 0.1139

391/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9624 - loss: 0.1137

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9625 - loss: 0.1136

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9626 - loss: 0.1132

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9627 - loss: 0.1129

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9627 - loss: 0.1129

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9628 - loss: 0.1125

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9626 - loss: 0.1130

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9627 - loss: 0.1128

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9627 - loss: 0.1127

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9628 - loss: 0.1124

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9629 - loss: 0.1122

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9629 - loss: 0.1123

415/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9629 - loss: 0.1130

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9628 - loss: 0.1131

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9628 - loss: 0.1131

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9628 - loss: 0.1129

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9629 - loss: 0.1127

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9629 - loss: 0.1128

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9630 - loss: 0.1126

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9631 - loss: 0.1124

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9631 - loss: 0.1123

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9630 - loss: 0.1122

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9631 - loss: 0.1120

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9633 - loss: 0.1116

439/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9634 - loss: 0.1113

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9634 - loss: 0.1116

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9633 - loss: 0.1118

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9633 - loss: 0.1117

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9634 - loss: 0.1116

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9634 - loss: 0.1119

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9636 - loss: 0.1115

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9636 - loss: 0.1115

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9636 - loss: 0.1114

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9636 - loss: 0.1114

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9638 - loss: 0.1110

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9636 - loss: 0.1113

463/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9636 - loss: 0.1114

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9635 - loss: 0.1115

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9635 - loss: 0.1114

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9636 - loss: 0.1113

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9636 - loss: 0.1113

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9635 - loss: 0.1114

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9636 - loss: 0.1113

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9636 - loss: 0.1113

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9636 - loss: 0.1113

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9637 - loss: 0.1111

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9638 - loss: 0.1108

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9638 - loss: 0.1107

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9637 - loss: 0.1108

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9636 - loss: 0.1107

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9636 - loss: 0.1107

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9635 - loss: 0.1111

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9634 - loss: 0.1110

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9635 - loss: 0.1110

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9634 - loss: 0.1111

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9636 - loss: 0.1109

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9636 - loss: 0.1107

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9636 - loss: 0.1107

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9635 - loss: 0.1111

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9637 - loss: 0.1108

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9637 - loss: 0.1107

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9637 - loss: 0.1106

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9637 - loss: 0.1106

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9638 - loss: 0.1106

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9639 - loss: 0.1105

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9638 - loss: 0.1107

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9638 - loss: 0.1107

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9637 - loss: 0.1108

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9638 - loss: 0.1105

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9639 - loss: 0.1102

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9639 - loss: 0.1101

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9640 - loss: 0.1099

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9640 - loss: 0.1103

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9641 - loss: 0.1101

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9641 - loss: 0.1101

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9641 - loss: 0.1102

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9640 - loss: 0.1101

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9639 - loss: 0.1106

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9639 - loss: 0.1105

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9640 - loss: 0.1103

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9641 - loss: 0.1102

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9641 - loss: 0.1104

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9642 - loss: 0.1101

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9643 - loss: 0.1099

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9643 - loss: 0.1099

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9642 - loss: 0.1098

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9640 - loss: 0.1102

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9639 - loss: 0.1105

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9639 - loss: 0.1104

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9639 - loss: 0.1103

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9639 - loss: 0.1102

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9641 - loss: 0.1099

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9641 - loss: 0.1097

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9641 - loss: 0.1096

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9641 - loss: 0.1095

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9641 - loss: 0.1096

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9641 - loss: 0.1095

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9642 - loss: 0.1093

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9642 - loss: 0.1091

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9643 - loss: 0.1088

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9644 - loss: 0.1087

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9644 - loss: 0.1086

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9644 - loss: 0.1086

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9644 - loss: 0.1085

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9645 - loss: 0.1083

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9646 - loss: 0.1082

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9647 - loss: 0.1081

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9647 - loss: 0.1081

606/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.9647 - loss: 0.1081 - val_accuracy: 0.9623 - val_loss: 0.1672

Epoch 18/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 34s 58ms/step - accuracy: 1.0000 - loss: 0.0194

  3/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 1.0000 - loss: 0.0208

  5/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9750 - loss: 0.0654

  7/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9732 - loss: 0.0704

  9/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9792 - loss: 0.0600

 11/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9773 - loss: 0.0713

 13/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9760 - loss: 0.0676

 15/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9771 - loss: 0.0641

 17/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9743 - loss: 0.0666

 19/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9704 - loss: 0.0741

 21/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9717 - loss: 0.0907

 23/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9660 - loss: 0.1101

 25/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9675 - loss: 0.1067

 27/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9664 - loss: 0.1066

 29/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9688 - loss: 0.1012

 31/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9688 - loss: 0.0991

 33/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9706 - loss: 0.0951

 35/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9705 - loss: 0.0975

 37/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9704 - loss: 0.0980

 39/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9712 - loss: 0.0950

 41/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9680 - loss: 0.0996

 43/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9688 - loss: 0.0980

 45/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9681 - loss: 0.1010

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9681 - loss: 0.0990

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9675 - loss: 0.0995

 51/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9675 - loss: 0.0991

 53/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9670 - loss: 0.0986

 55/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9659 - loss: 0.0993

 57/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9655 - loss: 0.0998

 59/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9656 - loss: 0.0990

 61/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9667 - loss: 0.0969

 63/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9673 - loss: 0.0962

 65/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9683 - loss: 0.0940

 67/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9692 - loss: 0.0926

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9692 - loss: 0.0935

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9683 - loss: 0.0964

 73/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9683 - loss: 0.0967

 75/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9688 - loss: 0.0957

 77/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9683 - loss: 0.0960

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9680 - loss: 0.0967

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9668 - loss: 0.1011

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9669 - loss: 0.1003

 85/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9669 - loss: 0.0997

 87/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9670 - loss: 0.0990

 89/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9670 - loss: 0.0998

 91/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9663 - loss: 0.1004

 93/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9667 - loss: 0.0993

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9671 - loss: 0.0984

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9675 - loss: 0.0979

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9669 - loss: 0.0993

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9672 - loss: 0.0987

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9669 - loss: 0.0997

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9670 - loss: 0.1007

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9667 - loss: 0.1006

109/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9673 - loss: 0.0991

111/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9668 - loss: 0.1015

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9654 - loss: 0.1069

115/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9652 - loss: 0.1085

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9655 - loss: 0.1094

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9653 - loss: 0.1099

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9654 - loss: 0.1100

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9654 - loss: 0.1096

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9657 - loss: 0.1089

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9658 - loss: 0.1084

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9656 - loss: 0.1083

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9649 - loss: 0.1093

133/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9645 - loss: 0.1100

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9641 - loss: 0.1101

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9642 - loss: 0.1102

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9647 - loss: 0.1092

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9652 - loss: 0.1081

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9650 - loss: 0.1080

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9655 - loss: 0.1068

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9658 - loss: 0.1063

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9658 - loss: 0.1063

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9661 - loss: 0.1054

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9661 - loss: 0.1059

155/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9661 - loss: 0.1060

157/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9660 - loss: 0.1069

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9658 - loss: 0.1073

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9658 - loss: 0.1071

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9653 - loss: 0.1092

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9653 - loss: 0.1092

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9654 - loss: 0.1093

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9652 - loss: 0.1097

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9651 - loss: 0.1099

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9648 - loss: 0.1102

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9641 - loss: 0.1126

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9643 - loss: 0.1123

179/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9646 - loss: 0.1118

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9648 - loss: 0.1114

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9647 - loss: 0.1114

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9647 - loss: 0.1109

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9649 - loss: 0.1104

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9646 - loss: 0.1107

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9645 - loss: 0.1104

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9649 - loss: 0.1095

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9643 - loss: 0.1121

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9643 - loss: 0.1115

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9640 - loss: 0.1118

201/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9638 - loss: 0.1121

203/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9640 - loss: 0.1115

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9640 - loss: 0.1114

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9642 - loss: 0.1109

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9644 - loss: 0.1103

210/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9644 - loss: 0.1110

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9645 - loss: 0.1113

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9643 - loss: 0.1113

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9644 - loss: 0.1111

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9640 - loss: 0.1127

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9636 - loss: 0.1134

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9634 - loss: 0.1144

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9636 - loss: 0.1140

225/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9633 - loss: 0.1146

227/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9634 - loss: 0.1146

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9632 - loss: 0.1152

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9632 - loss: 0.1150

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9635 - loss: 0.1143

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9637 - loss: 0.1138

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9637 - loss: 0.1136

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9635 - loss: 0.1136

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9634 - loss: 0.1138

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9636 - loss: 0.1132

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9635 - loss: 0.1131

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9634 - loss: 0.1131

249/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9634 - loss: 0.1130

251/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9634 - loss: 0.1127

253/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9636 - loss: 0.1122

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9636 - loss: 0.1119

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9639 - loss: 0.1114

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9636 - loss: 0.1124

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9637 - loss: 0.1118

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9636 - loss: 0.1116

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9634 - loss: 0.1116

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9637 - loss: 0.1111

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9638 - loss: 0.1110

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9637 - loss: 0.1108

273/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9635 - loss: 0.1114

275/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9635 - loss: 0.1111

277/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9636 - loss: 0.1113

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9636 - loss: 0.1111

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9635 - loss: 0.1113

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9633 - loss: 0.1115

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9635 - loss: 0.1111

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9633 - loss: 0.1120

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9630 - loss: 0.1124

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9628 - loss: 0.1127

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9630 - loss: 0.1125

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9630 - loss: 0.1125

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9630 - loss: 0.1124

299/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9630 - loss: 0.1121

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9631 - loss: 0.1118

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9633 - loss: 0.1114

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9634 - loss: 0.1112

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9635 - loss: 0.1111

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9635 - loss: 0.1109

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9635 - loss: 0.1106

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9635 - loss: 0.1106

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9637 - loss: 0.1101

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9637 - loss: 0.1099

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9637 - loss: 0.1102

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9634 - loss: 0.1104

323/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9635 - loss: 0.1099

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9637 - loss: 0.1096

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9634 - loss: 0.1104

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9635 - loss: 0.1103

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9637 - loss: 0.1101

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9638 - loss: 0.1105

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9638 - loss: 0.1102

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9639 - loss: 0.1099

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9639 - loss: 0.1097

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9640 - loss: 0.1095

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9639 - loss: 0.1096

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9639 - loss: 0.1095

347/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9640 - loss: 0.1094

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9641 - loss: 0.1093

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9642 - loss: 0.1092

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9643 - loss: 0.1090

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9643 - loss: 0.1090

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9643 - loss: 0.1089

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9641 - loss: 0.1092

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9642 - loss: 0.1090

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9644 - loss: 0.1085

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9643 - loss: 0.1085

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9642 - loss: 0.1084

369/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9641 - loss: 0.1082

371/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9637 - loss: 0.1091

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9638 - loss: 0.1089

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9636 - loss: 0.1093

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9638 - loss: 0.1092

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9634 - loss: 0.1104

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9633 - loss: 0.1107

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9633 - loss: 0.1107

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9632 - loss: 0.1106

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9633 - loss: 0.1105

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9634 - loss: 0.1103

391/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9635 - loss: 0.1101

393/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9635 - loss: 0.1099

395/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9635 - loss: 0.1097

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9636 - loss: 0.1097

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9635 - loss: 0.1098

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9635 - loss: 0.1098

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9636 - loss: 0.1099

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9637 - loss: 0.1096

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9637 - loss: 0.1096

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9633 - loss: 0.1101

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9634 - loss: 0.1101

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9635 - loss: 0.1099

415/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9633 - loss: 0.1100

417/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9634 - loss: 0.1098

419/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9635 - loss: 0.1096

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9636 - loss: 0.1094

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9637 - loss: 0.1091

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9636 - loss: 0.1096

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9637 - loss: 0.1092

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9639 - loss: 0.1088

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9639 - loss: 0.1086

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9640 - loss: 0.1084

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9640 - loss: 0.1083

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9640 - loss: 0.1082

439/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9639 - loss: 0.1085

441/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9639 - loss: 0.1083

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9638 - loss: 0.1083

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9639 - loss: 0.1080

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9639 - loss: 0.1082

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9639 - loss: 0.1081

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9638 - loss: 0.1085

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9639 - loss: 0.1082

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9639 - loss: 0.1081

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9638 - loss: 0.1087

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9636 - loss: 0.1091

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9637 - loss: 0.1090

463/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9636 - loss: 0.1088

465/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9635 - loss: 0.1094

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9635 - loss: 0.1094

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9634 - loss: 0.1098

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9631 - loss: 0.1101

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9632 - loss: 0.1100

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9633 - loss: 0.1098

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9632 - loss: 0.1097

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9633 - loss: 0.1094

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9635 - loss: 0.1091

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9634 - loss: 0.1092

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9635 - loss: 0.1090

487/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9635 - loss: 0.1089

489/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9636 - loss: 0.1086

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9635 - loss: 0.1087

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9636 - loss: 0.1086

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9636 - loss: 0.1086

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9635 - loss: 0.1084

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9635 - loss: 0.1089

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9634 - loss: 0.1090

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9634 - loss: 0.1089

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9634 - loss: 0.1088

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9635 - loss: 0.1085

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9636 - loss: 0.1083

511/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9636 - loss: 0.1083

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9636 - loss: 0.1082

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9637 - loss: 0.1080

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9637 - loss: 0.1080

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9638 - loss: 0.1077

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9638 - loss: 0.1078

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9637 - loss: 0.1080

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9637 - loss: 0.1081

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9637 - loss: 0.1081

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9636 - loss: 0.1085

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9637 - loss: 0.1083

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9636 - loss: 0.1087

535/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9636 - loss: 0.1088

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9636 - loss: 0.1086

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9636 - loss: 0.1086

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9635 - loss: 0.1089

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9636 - loss: 0.1086

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9638 - loss: 0.1084

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9639 - loss: 0.1081

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9640 - loss: 0.1079

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9640 - loss: 0.1079

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9639 - loss: 0.1084

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9639 - loss: 0.1085

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9639 - loss: 0.1087

559/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9639 - loss: 0.1086

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9640 - loss: 0.1085

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9638 - loss: 0.1089

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9639 - loss: 0.1086

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9640 - loss: 0.1085

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9640 - loss: 0.1082

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9640 - loss: 0.1083

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9638 - loss: 0.1085

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9640 - loss: 0.1082

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9640 - loss: 0.1080

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9642 - loss: 0.1078

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9642 - loss: 0.1076

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9642 - loss: 0.1076

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9642 - loss: 0.1075

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9642 - loss: 0.1075

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9643 - loss: 0.1072

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9643 - loss: 0.1072

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9642 - loss: 0.1073

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9643 - loss: 0.1070

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9644 - loss: 0.1068

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9644 - loss: 0.1066

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9644 - loss: 0.1066

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9644 - loss: 0.1066

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9645 - loss: 0.1064

606/606 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.9644 - loss: 0.1066 - val_accuracy: 0.9581 - val_loss: 0.1637

Epoch 19/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 37s 61ms/step - accuracy: 1.0000 - loss: 0.0185

  3/606 ━━━━━━━━━━━━━━━━━━━━ 28s 48ms/step - accuracy: 0.9792 - loss: 0.0361

  5/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.9563 - loss: 0.0764

  7/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.9643 - loss: 0.0686

  9/606 ━━━━━━━━━━━━━━━━━━━━ 27s 46ms/step - accuracy: 0.9688 - loss: 0.0646

 11/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9688 - loss: 0.0645

 13/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9736 - loss: 0.0569

 15/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9750 - loss: 0.0556

 17/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9761 - loss: 0.0537

 19/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9737 - loss: 0.0641

 21/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9747 - loss: 0.0655

 23/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9742 - loss: 0.0649

 25/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9725 - loss: 0.0748

 27/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9745 - loss: 0.0706

 29/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9720 - loss: 0.0833

 31/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9718 - loss: 0.0839

 33/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9725 - loss: 0.0817

 35/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9732 - loss: 0.0789

 37/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9730 - loss: 0.0788

 39/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9720 - loss: 0.0808

 41/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9726 - loss: 0.0810

 43/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9702 - loss: 0.0835

 45/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9694 - loss: 0.0839

 47/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9707 - loss: 0.0816

 49/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9700 - loss: 0.0846

 51/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9700 - loss: 0.0836

 53/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9705 - loss: 0.0821

 55/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9693 - loss: 0.0843

 57/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9688 - loss: 0.0857

 59/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9698 - loss: 0.0843

 61/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9708 - loss: 0.0825

 63/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9702 - loss: 0.0841

 65/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9702 - loss: 0.0840

 67/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9706 - loss: 0.0831

 69/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9715 - loss: 0.0823

 71/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9718 - loss: 0.0818

 73/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9717 - loss: 0.0818

 75/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9717 - loss: 0.0823

 77/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9716 - loss: 0.0846

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9719 - loss: 0.0834

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9718 - loss: 0.0840

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9699 - loss: 0.0878

 85/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9699 - loss: 0.0876

 87/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9695 - loss: 0.0877

 89/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9695 - loss: 0.0884

 91/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9691 - loss: 0.0890

 93/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9694 - loss: 0.0883

 95/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9684 - loss: 0.0893

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9681 - loss: 0.0894

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9681 - loss: 0.0902

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9678 - loss: 0.0908

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9684 - loss: 0.0897

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9688 - loss: 0.0899

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9690 - loss: 0.0896

109/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9688 - loss: 0.0907

111/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9688 - loss: 0.0934

113/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9676 - loss: 0.0975

115/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9674 - loss: 0.0983

117/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9677 - loss: 0.0975

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9677 - loss: 0.0983

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9682 - loss: 0.0974

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9682 - loss: 0.0981

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9670 - loss: 0.0992

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9670 - loss: 0.0989

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9673 - loss: 0.0989

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9673 - loss: 0.0990

133/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9673 - loss: 0.1002

135/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9676 - loss: 0.0995

137/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9674 - loss: 0.1005

139/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9674 - loss: 0.1008

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9679 - loss: 0.0996

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9674 - loss: 0.0995

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9679 - loss: 0.0987

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9681 - loss: 0.0979

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9681 - loss: 0.0974

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9683 - loss: 0.0968

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9681 - loss: 0.0969

155/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9681 - loss: 0.0970

157/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9678 - loss: 0.0983

159/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9676 - loss: 0.0981

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9678 - loss: 0.0981

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9676 - loss: 0.0985

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9670 - loss: 0.1004

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9669 - loss: 0.1007

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9665 - loss: 0.1012

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9664 - loss: 0.1014

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9666 - loss: 0.1010

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9666 - loss: 0.1015

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9666 - loss: 0.1016

179/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9665 - loss: 0.1015

181/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9667 - loss: 0.1014

183/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9667 - loss: 0.1012

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9669 - loss: 0.1007

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9671 - loss: 0.1000

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9674 - loss: 0.0994

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9670 - loss: 0.1004

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9671 - loss: 0.0999

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9671 - loss: 0.0997

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9672 - loss: 0.0994

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9672 - loss: 0.0993

201/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9669 - loss: 0.0995

203/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9666 - loss: 0.1001

205/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9668 - loss: 0.0997

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9671 - loss: 0.0990

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9671 - loss: 0.0991

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9670 - loss: 0.1015

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9673 - loss: 0.1008

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9673 - loss: 0.1010

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9672 - loss: 0.1013

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9673 - loss: 0.1012

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9671 - loss: 0.1017

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9671 - loss: 0.1016

225/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9667 - loss: 0.1018

227/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9665 - loss: 0.1021

229/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9667 - loss: 0.1015

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9666 - loss: 0.1015

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9666 - loss: 0.1014

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9664 - loss: 0.1019

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9665 - loss: 0.1019

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9661 - loss: 0.1024

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9664 - loss: 0.1020

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9666 - loss: 0.1017

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9662 - loss: 0.1018

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9661 - loss: 0.1019

249/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9660 - loss: 0.1017

251/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9658 - loss: 0.1035

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9657 - loss: 0.1035

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9658 - loss: 0.1031

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9660 - loss: 0.1028

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9660 - loss: 0.1027

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9661 - loss: 0.1025

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9664 - loss: 0.1019

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9664 - loss: 0.1020

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9664 - loss: 0.1019

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9662 - loss: 0.1027

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9664 - loss: 0.1021

273/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9665 - loss: 0.1017

275/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9665 - loss: 0.1016

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9665 - loss: 0.1020

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9662 - loss: 0.1032

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9662 - loss: 0.1039

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9662 - loss: 0.1036

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9660 - loss: 0.1041

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9654 - loss: 0.1047

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9652 - loss: 0.1050

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9650 - loss: 0.1058

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9650 - loss: 0.1060

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9649 - loss: 0.1060

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9646 - loss: 0.1062

299/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9646 - loss: 0.1061

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9646 - loss: 0.1061

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9645 - loss: 0.1061

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9645 - loss: 0.1057

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9647 - loss: 0.1055

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9648 - loss: 0.1052

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9647 - loss: 0.1052

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9647 - loss: 0.1051

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9649 - loss: 0.1046

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9647 - loss: 0.1047

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9646 - loss: 0.1047

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9645 - loss: 0.1050

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9643 - loss: 0.1053

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9643 - loss: 0.1052

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9645 - loss: 0.1047

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9646 - loss: 0.1047

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9647 - loss: 0.1046

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9649 - loss: 0.1041

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9647 - loss: 0.1044

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9648 - loss: 0.1043

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9649 - loss: 0.1040

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9649 - loss: 0.1038

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9649 - loss: 0.1039

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9651 - loss: 0.1034

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9651 - loss: 0.1035

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9652 - loss: 0.1040

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9651 - loss: 0.1047

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9651 - loss: 0.1046

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9651 - loss: 0.1046

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9652 - loss: 0.1046

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9653 - loss: 0.1043

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9654 - loss: 0.1040

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9655 - loss: 0.1037

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9654 - loss: 0.1036

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9656 - loss: 0.1033

369/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9656 - loss: 0.1037

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9653 - loss: 0.1043

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9651 - loss: 0.1045

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9650 - loss: 0.1046

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9651 - loss: 0.1042

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9652 - loss: 0.1039

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9653 - loss: 0.1038

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9652 - loss: 0.1041

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9650 - loss: 0.1043

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9650 - loss: 0.1044

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9651 - loss: 0.1043

391/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9651 - loss: 0.1042

393/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9650 - loss: 0.1041

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9651 - loss: 0.1039

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9653 - loss: 0.1035

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9654 - loss: 0.1033

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9654 - loss: 0.1029

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9653 - loss: 0.1034

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9654 - loss: 0.1031

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9654 - loss: 0.1031

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9654 - loss: 0.1032

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9653 - loss: 0.1033

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9653 - loss: 0.1034

415/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9654 - loss: 0.1031

417/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9652 - loss: 0.1037

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9652 - loss: 0.1035

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9653 - loss: 0.1033

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9651 - loss: 0.1033

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9651 - loss: 0.1033

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9651 - loss: 0.1032

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9651 - loss: 0.1030

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9652 - loss: 0.1028

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9654 - loss: 0.1024

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9654 - loss: 0.1022

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9655 - loss: 0.1032

439/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9655 - loss: 0.1030

441/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9657 - loss: 0.1027

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9656 - loss: 0.1028

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9657 - loss: 0.1027

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9658 - loss: 0.1025

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9658 - loss: 0.1024

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9660 - loss: 0.1020

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9659 - loss: 0.1021

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9658 - loss: 0.1027

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9657 - loss: 0.1029

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9658 - loss: 0.1028

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9657 - loss: 0.1029

463/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9658 - loss: 0.1028

465/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9657 - loss: 0.1032

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9659 - loss: 0.1029

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9657 - loss: 0.1029

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9658 - loss: 0.1028

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9657 - loss: 0.1028

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9656 - loss: 0.1031

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9655 - loss: 0.1031

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9656 - loss: 0.1031

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9657 - loss: 0.1029

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9658 - loss: 0.1027

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9656 - loss: 0.1027

487/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9657 - loss: 0.1025

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9656 - loss: 0.1024

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9655 - loss: 0.1024

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9653 - loss: 0.1027

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9654 - loss: 0.1026

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9655 - loss: 0.1025

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9656 - loss: 0.1023

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9656 - loss: 0.1021

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9655 - loss: 0.1024

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9656 - loss: 0.1022

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9656 - loss: 0.1023

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9656 - loss: 0.1023

511/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9654 - loss: 0.1026

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9655 - loss: 0.1026

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9656 - loss: 0.1024

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9656 - loss: 0.1024

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9657 - loss: 0.1021

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9656 - loss: 0.1025

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9655 - loss: 0.1028

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9656 - loss: 0.1025

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9655 - loss: 0.1027

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9656 - loss: 0.1025

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9656 - loss: 0.1025

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9656 - loss: 0.1023

535/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9658 - loss: 0.1020

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9659 - loss: 0.1017

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9658 - loss: 0.1022

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9657 - loss: 0.1021

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9657 - loss: 0.1024

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9654 - loss: 0.1028

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9655 - loss: 0.1028

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9656 - loss: 0.1026

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9656 - loss: 0.1025

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9657 - loss: 0.1023

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9658 - loss: 0.1022

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9659 - loss: 0.1021

559/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9660 - loss: 0.1018

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9661 - loss: 0.1017

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9661 - loss: 0.1019

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9660 - loss: 0.1019

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9661 - loss: 0.1018

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9662 - loss: 0.1018

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9662 - loss: 0.1017

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9663 - loss: 0.1014

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9664 - loss: 0.1012

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9664 - loss: 0.1011

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9664 - loss: 0.1010

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9665 - loss: 0.1007

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9664 - loss: 0.1008

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9664 - loss: 0.1008

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9663 - loss: 0.1011

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9664 - loss: 0.1010

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9662 - loss: 0.1011

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9663 - loss: 0.1008

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9663 - loss: 0.1007

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9664 - loss: 0.1004

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9665 - loss: 0.1003

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9665 - loss: 0.1002

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9665 - loss: 0.1003

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9665 - loss: 0.1001

606/606 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.9665 - loss: 0.1001 - val_accuracy: 0.9596 - val_loss: 0.1642

Epoch 20/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 34s 58ms/step - accuracy: 1.0000 - loss: 0.0231

  3/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9583 - loss: 0.0714

  5/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9563 - loss: 0.0770

  7/606 ━━━━━━━━━━━━━━━━━━━━ 24s 41ms/step - accuracy: 0.9643 - loss: 0.0664

  9/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9722 - loss: 0.0570

 11/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9744 - loss: 0.0583

 13/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9784 - loss: 0.0510

 15/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9750 - loss: 0.0592

 17/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9761 - loss: 0.0616

 19/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9770 - loss: 0.0587

 21/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9747 - loss: 0.0780

 23/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9728 - loss: 0.0801

 25/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9725 - loss: 0.0789

 27/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9734 - loss: 0.0822

 29/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9741 - loss: 0.0786

 31/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9748 - loss: 0.0781

 33/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9754 - loss: 0.0774

 35/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9741 - loss: 0.0771

 37/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9738 - loss: 0.0779

 39/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9736 - loss: 0.0794

 41/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9733 - loss: 0.0785

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9731 - loss: 0.0788

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9729 - loss: 0.0794

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9721 - loss: 0.0788

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9700 - loss: 0.0857

 51/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9700 - loss: 0.0853

 53/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9699 - loss: 0.0856

 55/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9693 - loss: 0.0860

 57/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9704 - loss: 0.0840

 59/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9714 - loss: 0.0821

 61/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9723 - loss: 0.0807

 63/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9727 - loss: 0.0816

 65/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9731 - loss: 0.0808

 67/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9729 - loss: 0.0805

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9724 - loss: 0.0835

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9718 - loss: 0.0846

 73/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9713 - loss: 0.0858

 75/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9717 - loss: 0.0852

 77/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9704 - loss: 0.0865

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9691 - loss: 0.0882

 81/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9688 - loss: 0.0893

 83/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9676 - loss: 0.0911

 85/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9676 - loss: 0.0911

 87/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9680 - loss: 0.0905

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9684 - loss: 0.0906

 91/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9688 - loss: 0.0900

 93/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9688 - loss: 0.0899

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9688 - loss: 0.0896

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9684 - loss: 0.0904

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9678 - loss: 0.0919

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9681 - loss: 0.0908

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9678 - loss: 0.0926

105/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9679 - loss: 0.0924

107/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9673 - loss: 0.0932

109/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9670 - loss: 0.0937

111/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9665 - loss: 0.0976

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9660 - loss: 0.0991

115/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9660 - loss: 0.0995

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9663 - loss: 0.0992

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9666 - loss: 0.0987

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9667 - loss: 0.0998

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9670 - loss: 0.0995

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9672 - loss: 0.0988

127/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9675 - loss: 0.0982

129/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9678 - loss: 0.0974

131/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9671 - loss: 0.0982

133/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9671 - loss: 0.0981

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9669 - loss: 0.0994

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9667 - loss: 0.0995

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9665 - loss: 0.0993

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9661 - loss: 0.0997

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9663 - loss: 0.0987

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9662 - loss: 0.0985

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9662 - loss: 0.0981

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9660 - loss: 0.0985

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9659 - loss: 0.0983

153/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9661 - loss: 0.0975

155/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9659 - loss: 0.0979

157/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9658 - loss: 0.0977

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9658 - loss: 0.0977

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9662 - loss: 0.0968

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9661 - loss: 0.0978

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9661 - loss: 0.0973

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9656 - loss: 0.0984

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9645 - loss: 0.1001

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9640 - loss: 0.1013

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9639 - loss: 0.1015

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9636 - loss: 0.1020

177/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9635 - loss: 0.1024

179/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9637 - loss: 0.1022

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9639 - loss: 0.1018

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9635 - loss: 0.1033

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9635 - loss: 0.1030

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9637 - loss: 0.1025

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9640 - loss: 0.1020

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9642 - loss: 0.1015

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9642 - loss: 0.1012

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9644 - loss: 0.1008

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9645 - loss: 0.1005

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9647 - loss: 0.1001

201/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9647 - loss: 0.1004

203/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9647 - loss: 0.1001

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9651 - loss: 0.0993

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9650 - loss: 0.0993

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9650 - loss: 0.0995

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9652 - loss: 0.0996

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9651 - loss: 0.0998

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9651 - loss: 0.0996

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9650 - loss: 0.0994

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9650 - loss: 0.0990

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9646 - loss: 0.1010

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9644 - loss: 0.1015

225/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9646 - loss: 0.1010

227/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9645 - loss: 0.1008

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9645 - loss: 0.1007

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9647 - loss: 0.1006

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9646 - loss: 0.1007

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9648 - loss: 0.1004

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9649 - loss: 0.1004

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9648 - loss: 0.1006

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9646 - loss: 0.1008

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9644 - loss: 0.1009

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9647 - loss: 0.1003

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9648 - loss: 0.1001

249/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9645 - loss: 0.1002

251/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9644 - loss: 0.1004

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9642 - loss: 0.1003

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9645 - loss: 0.0997

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9646 - loss: 0.0996

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9646 - loss: 0.0993

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9648 - loss: 0.0990

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9646 - loss: 0.0994

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9647 - loss: 0.0991

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9649 - loss: 0.0987

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9650 - loss: 0.0982

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9651 - loss: 0.0981

273/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9651 - loss: 0.0979

275/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9651 - loss: 0.0989

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9648 - loss: 0.1000

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9649 - loss: 0.0996

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9646 - loss: 0.1001

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9647 - loss: 0.0998

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9647 - loss: 0.0997

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9645 - loss: 0.1002

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9645 - loss: 0.1002

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9645 - loss: 0.1002

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9645 - loss: 0.1002

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9647 - loss: 0.0998

297/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9650 - loss: 0.0993

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9649 - loss: 0.0994

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9649 - loss: 0.0991

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9650 - loss: 0.0987

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9648 - loss: 0.0997

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9647 - loss: 0.0999

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9646 - loss: 0.1000

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9646 - loss: 0.0997

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9647 - loss: 0.0995

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9649 - loss: 0.0992

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9646 - loss: 0.0994

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9647 - loss: 0.0993

321/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9649 - loss: 0.0992

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9648 - loss: 0.0993

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9647 - loss: 0.0995

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9649 - loss: 0.0991

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9651 - loss: 0.0986

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9653 - loss: 0.0985

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9654 - loss: 0.0982

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9651 - loss: 0.0990

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9650 - loss: 0.0991

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9650 - loss: 0.0995

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9649 - loss: 0.0999

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9651 - loss: 0.0996

345/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9651 - loss: 0.0994

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9651 - loss: 0.0995

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9651 - loss: 0.0997

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9652 - loss: 0.0996

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9651 - loss: 0.0997

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9651 - loss: 0.0996

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9652 - loss: 0.0997

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9652 - loss: 0.0994

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9654 - loss: 0.0989

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9656 - loss: 0.0986

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9656 - loss: 0.0990

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9657 - loss: 0.0987

369/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9656 - loss: 0.0986

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9657 - loss: 0.0984

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9657 - loss: 0.0984

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9657 - loss: 0.0983

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9656 - loss: 0.0984

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9655 - loss: 0.0985

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9656 - loss: 0.0987

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9657 - loss: 0.0983

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9656 - loss: 0.0986

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9656 - loss: 0.0984

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9657 - loss: 0.0983

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9659 - loss: 0.0980

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9660 - loss: 0.0976

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9661 - loss: 0.0975

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9660 - loss: 0.0976

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9661 - loss: 0.0973

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9662 - loss: 0.0970

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9663 - loss: 0.0968

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9664 - loss: 0.0966

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9664 - loss: 0.0966

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9665 - loss: 0.0964

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9664 - loss: 0.0968

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9664 - loss: 0.0968

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9663 - loss: 0.0981

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9662 - loss: 0.0980

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9662 - loss: 0.0979

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9664 - loss: 0.0976

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9664 - loss: 0.0974

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9665 - loss: 0.0971

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9666 - loss: 0.0968

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9666 - loss: 0.0966

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9668 - loss: 0.0963

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9667 - loss: 0.0963

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9669 - loss: 0.0959

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9667 - loss: 0.0963

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9668 - loss: 0.0963

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9666 - loss: 0.0964

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9668 - loss: 0.0961

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9669 - loss: 0.0959

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9669 - loss: 0.0957

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9669 - loss: 0.0954

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9669 - loss: 0.0955

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9670 - loss: 0.0954

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9669 - loss: 0.0958

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9669 - loss: 0.0957

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9668 - loss: 0.0960

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9669 - loss: 0.0959

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9669 - loss: 0.0959

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9669 - loss: 0.0959

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9669 - loss: 0.0960

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9669 - loss: 0.0960

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9670 - loss: 0.0959

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9670 - loss: 0.0956

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9670 - loss: 0.0957

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9671 - loss: 0.0955

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9672 - loss: 0.0953

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9672 - loss: 0.0952

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9673 - loss: 0.0949

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9674 - loss: 0.0947

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9674 - loss: 0.0946

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9673 - loss: 0.0946

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9674 - loss: 0.0943

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9674 - loss: 0.0942

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9674 - loss: 0.0945

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9673 - loss: 0.0946

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9674 - loss: 0.0945

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9673 - loss: 0.0946

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9673 - loss: 0.0945

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9673 - loss: 0.0946

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9673 - loss: 0.0945

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9674 - loss: 0.0941

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9673 - loss: 0.0943

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9674 - loss: 0.0942

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9675 - loss: 0.0942

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9675 - loss: 0.0941

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9675 - loss: 0.0940

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9675 - loss: 0.0939

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9673 - loss: 0.0944

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9673 - loss: 0.0944

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9674 - loss: 0.0944

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9675 - loss: 0.0941

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9675 - loss: 0.0939

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9676 - loss: 0.0940

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9677 - loss: 0.0937

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9676 - loss: 0.0940

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9676 - loss: 0.0940

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9676 - loss: 0.0939

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9675 - loss: 0.0943

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9676 - loss: 0.0942

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9676 - loss: 0.0943

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9675 - loss: 0.0944

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9676 - loss: 0.0943

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9675 - loss: 0.0945

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9676 - loss: 0.0943

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9675 - loss: 0.0947

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9675 - loss: 0.0946

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9675 - loss: 0.0945

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9675 - loss: 0.0943

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9676 - loss: 0.0942

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9676 - loss: 0.0939

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9677 - loss: 0.0937

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9677 - loss: 0.0939

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9677 - loss: 0.0939

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9678 - loss: 0.0937

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9679 - loss: 0.0935

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9680 - loss: 0.0932

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9681 - loss: 0.0930

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9681 - loss: 0.0933

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9680 - loss: 0.0934

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9681 - loss: 0.0932

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9681 - loss: 0.0931

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9681 - loss: 0.0931

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9682 - loss: 0.0929

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9683 - loss: 0.0927

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9682 - loss: 0.0926

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9682 - loss: 0.0925

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9682 - loss: 0.0924

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9682 - loss: 0.0923

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9682 - loss: 0.0924

606/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.9683 - loss: 0.0923 - val_accuracy: 0.9530 - val_loss: 0.1986

Epoch 21/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 36s 61ms/step - accuracy: 0.9688 - loss: 0.0738

  3/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9792 - loss: 0.0505

  5/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9750 - loss: 0.0541

  7/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9821 - loss: 0.0432

  9/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9792 - loss: 0.0461

 11/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9801 - loss: 0.0425

 13/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9784 - loss: 0.0432

 15/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9771 - loss: 0.0532

 17/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9761 - loss: 0.0565

 19/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9770 - loss: 0.0562

 21/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9762 - loss: 0.0748

 23/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9769 - loss: 0.0737

 25/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9737 - loss: 0.0842

 27/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9757 - loss: 0.0794

 29/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9741 - loss: 0.0801

 31/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9748 - loss: 0.0771

 33/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9735 - loss: 0.0771

 35/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9750 - loss: 0.0736

 37/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9755 - loss: 0.0718

 39/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9760 - loss: 0.0718

 41/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9764 - loss: 0.0699

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9775 - loss: 0.0675

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9778 - loss: 0.0661

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9781 - loss: 0.0662

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9777 - loss: 0.0666

 51/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9755 - loss: 0.0705

 53/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9746 - loss: 0.0720

 55/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9739 - loss: 0.0745

 57/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9737 - loss: 0.0738

 59/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9740 - loss: 0.0733

 61/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9739 - loss: 0.0744

 63/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9742 - loss: 0.0736

 65/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9740 - loss: 0.0747

 67/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9734 - loss: 0.0760

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9737 - loss: 0.0760

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9740 - loss: 0.0750

 73/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9743 - loss: 0.0744

 75/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9742 - loss: 0.0746

 77/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9736 - loss: 0.0765

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9731 - loss: 0.0780

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9715 - loss: 0.0801

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9706 - loss: 0.0810

 85/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9710 - loss: 0.0800

 87/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9713 - loss: 0.0794

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9716 - loss: 0.0787

 91/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9712 - loss: 0.0790

 93/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9711 - loss: 0.0792

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9714 - loss: 0.0788

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9720 - loss: 0.0780

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9719 - loss: 0.0791

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9722 - loss: 0.0789

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9721 - loss: 0.0785

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9723 - loss: 0.0790

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9720 - loss: 0.0796

109/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9722 - loss: 0.0788

111/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9724 - loss: 0.0782

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9721 - loss: 0.0791

115/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9709 - loss: 0.0860

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9714 - loss: 0.0849

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9714 - loss: 0.0850

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9711 - loss: 0.0850

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9705 - loss: 0.0875

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9703 - loss: 0.0889

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9697 - loss: 0.0898

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9697 - loss: 0.0895

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9699 - loss: 0.0887

133/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9695 - loss: 0.0901

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9697 - loss: 0.0898

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9694 - loss: 0.0903

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9688 - loss: 0.0913

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9676 - loss: 0.0932

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9681 - loss: 0.0926

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9681 - loss: 0.0928

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9685 - loss: 0.0921

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9690 - loss: 0.0915

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9690 - loss: 0.0921

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9688 - loss: 0.0939

155/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9688 - loss: 0.0936

157/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9684 - loss: 0.0946

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9682 - loss: 0.0951

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9678 - loss: 0.0959

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9678 - loss: 0.0958

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9670 - loss: 0.0970

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9671 - loss: 0.0968

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9665 - loss: 0.0978

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9667 - loss: 0.0976

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9664 - loss: 0.0987

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9668 - loss: 0.0982

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9666 - loss: 0.1002

179/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9668 - loss: 0.0998

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9665 - loss: 0.1002

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9664 - loss: 0.1007

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9662 - loss: 0.1007

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9656 - loss: 0.1014

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9651 - loss: 0.1024

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9653 - loss: 0.1018

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9652 - loss: 0.1019

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9652 - loss: 0.1018

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9654 - loss: 0.1016

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9655 - loss: 0.1018

201/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9658 - loss: 0.1014

203/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9658 - loss: 0.1015

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9660 - loss: 0.1010

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9660 - loss: 0.1007

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9659 - loss: 0.1006

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9661 - loss: 0.1005

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9660 - loss: 0.1005

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9663 - loss: 0.0998

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9659 - loss: 0.1006

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9660 - loss: 0.1010

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9661 - loss: 0.1010

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9657 - loss: 0.1018

225/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9656 - loss: 0.1019

227/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9659 - loss: 0.1015

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9659 - loss: 0.1015

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9659 - loss: 0.1013

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9659 - loss: 0.1012

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9660 - loss: 0.1010

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9660 - loss: 0.1007

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9661 - loss: 0.1004

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9662 - loss: 0.1001

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9658 - loss: 0.1010

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9659 - loss: 0.1008

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9658 - loss: 0.1009

249/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9656 - loss: 0.1011

251/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9659 - loss: 0.1007

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9660 - loss: 0.1004

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9661 - loss: 0.1005

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9661 - loss: 0.1003

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9663 - loss: 0.0997

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9662 - loss: 0.0997

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9661 - loss: 0.0997

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9662 - loss: 0.0994

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9658 - loss: 0.0999

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9658 - loss: 0.0998

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9661 - loss: 0.0993

273/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9660 - loss: 0.0994

275/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9661 - loss: 0.0993

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9662 - loss: 0.0993

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9661 - loss: 0.0993

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9659 - loss: 0.0994

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9659 - loss: 0.0994

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9656 - loss: 0.1003

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9656 - loss: 0.1013

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9656 - loss: 0.1010

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9656 - loss: 0.1008

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9657 - loss: 0.1012

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9655 - loss: 0.1015

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9654 - loss: 0.1015

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9654 - loss: 0.1013

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9655 - loss: 0.1010

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9658 - loss: 0.1007

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9658 - loss: 0.1004

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9656 - loss: 0.1004

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9657 - loss: 0.1002

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9657 - loss: 0.1001

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9659 - loss: 0.1000

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9660 - loss: 0.0998

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9661 - loss: 0.0994

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9662 - loss: 0.0991

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9659 - loss: 0.0996

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9658 - loss: 0.0995

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9660 - loss: 0.0995

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9661 - loss: 0.0991

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9662 - loss: 0.0988

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9664 - loss: 0.0983

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9665 - loss: 0.0981

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9667 - loss: 0.0976

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9665 - loss: 0.0989

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9665 - loss: 0.0988

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9666 - loss: 0.0985

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9667 - loss: 0.0983

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9667 - loss: 0.0982

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9668 - loss: 0.0979

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9668 - loss: 0.0977

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9668 - loss: 0.0982

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9667 - loss: 0.0980

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9665 - loss: 0.0983

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9666 - loss: 0.0980

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9667 - loss: 0.0979

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9668 - loss: 0.0978

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9669 - loss: 0.0977

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9669 - loss: 0.0978

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9670 - loss: 0.0975

369/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9669 - loss: 0.0976

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9668 - loss: 0.0975

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9668 - loss: 0.0974

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9669 - loss: 0.0973

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9668 - loss: 0.0973

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9669 - loss: 0.0971

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9669 - loss: 0.0969

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9668 - loss: 0.0971

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9668 - loss: 0.0971

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9667 - loss: 0.0972

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9667 - loss: 0.0975

391/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9669 - loss: 0.0971

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9670 - loss: 0.0969

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9671 - loss: 0.0966

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9670 - loss: 0.0965

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9672 - loss: 0.0962

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9673 - loss: 0.0960

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9673 - loss: 0.0961

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9674 - loss: 0.0958

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9674 - loss: 0.0954

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9675 - loss: 0.0953

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9675 - loss: 0.0953

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9674 - loss: 0.0956

415/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9672 - loss: 0.0957

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9674 - loss: 0.0955

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9674 - loss: 0.0955

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9675 - loss: 0.0953

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9676 - loss: 0.0959

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9675 - loss: 0.0962

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9674 - loss: 0.0961

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9675 - loss: 0.0958

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9677 - loss: 0.0955

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9676 - loss: 0.0956

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9677 - loss: 0.0953

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9679 - loss: 0.0949

439/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9680 - loss: 0.0946

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9680 - loss: 0.0946

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9680 - loss: 0.0947

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9682 - loss: 0.0944

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9683 - loss: 0.0942

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9682 - loss: 0.0945

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9683 - loss: 0.0944

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9683 - loss: 0.0946

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9683 - loss: 0.0943

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9684 - loss: 0.0942

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9683 - loss: 0.0944

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9682 - loss: 0.0945

463/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9683 - loss: 0.0943

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9682 - loss: 0.0946

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9681 - loss: 0.0949

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9682 - loss: 0.0947

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9684 - loss: 0.0944

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9682 - loss: 0.0947

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9682 - loss: 0.0945

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9682 - loss: 0.0943

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9684 - loss: 0.0941

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9684 - loss: 0.0940

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9684 - loss: 0.0938

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9686 - loss: 0.0935

487/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9686 - loss: 0.0935

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9684 - loss: 0.0936

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9682 - loss: 0.0938

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9682 - loss: 0.0937

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9681 - loss: 0.0939

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9681 - loss: 0.0939

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9682 - loss: 0.0938

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9681 - loss: 0.0938

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9683 - loss: 0.0935

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9684 - loss: 0.0933

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9683 - loss: 0.0935

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9683 - loss: 0.0933

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9684 - loss: 0.0930

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9683 - loss: 0.0932

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9682 - loss: 0.0933

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9682 - loss: 0.0935

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9681 - loss: 0.0935

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9680 - loss: 0.0937

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9681 - loss: 0.0935

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9680 - loss: 0.0936

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9680 - loss: 0.0934

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9680 - loss: 0.0942

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9681 - loss: 0.0940

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9682 - loss: 0.0938

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9681 - loss: 0.0938

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9681 - loss: 0.0937

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9682 - loss: 0.0936

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9682 - loss: 0.0935

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9682 - loss: 0.0935

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9683 - loss: 0.0933

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9684 - loss: 0.0934

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9685 - loss: 0.0934

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9685 - loss: 0.0933

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9686 - loss: 0.0932

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9686 - loss: 0.0930

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9685 - loss: 0.0931

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9684 - loss: 0.0933

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9685 - loss: 0.0930

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9685 - loss: 0.0931

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9684 - loss: 0.0937

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9684 - loss: 0.0935

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9685 - loss: 0.0933

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9685 - loss: 0.0933

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9686 - loss: 0.0931

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9687 - loss: 0.0929

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9687 - loss: 0.0928

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9688 - loss: 0.0926

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9688 - loss: 0.0925

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9687 - loss: 0.0927

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9687 - loss: 0.0926

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9687 - loss: 0.0925

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9687 - loss: 0.0924

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9688 - loss: 0.0922

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9688 - loss: 0.0921

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9688 - loss: 0.0919

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9689 - loss: 0.0917

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9689 - loss: 0.0917

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9688 - loss: 0.0918

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9688 - loss: 0.0917

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9689 - loss: 0.0915

606/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.9689 - loss: 0.0915 - val_accuracy: 0.9533 - val_loss: 0.2056

Epoch 22/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 1.0000 - loss: 0.0496

  3/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9792 - loss: 0.0671

  5/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9875 - loss: 0.0434

  7/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9911 - loss: 0.0373

  9/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9896 - loss: 0.0359

 11/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9858 - loss: 0.0411

 13/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9832 - loss: 0.0406

 15/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9854 - loss: 0.0375

 17/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9816 - loss: 0.0465

 19/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9819 - loss: 0.0456

 21/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9792 - loss: 0.0544

 23/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9783 - loss: 0.0560

 25/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9775 - loss: 0.0618

 27/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9792 - loss: 0.0588

 29/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9806 - loss: 0.0554

 31/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9808 - loss: 0.0553

 33/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9820 - loss: 0.0524

 35/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9821 - loss: 0.0511

 37/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9797 - loss: 0.0571

 39/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9808 - loss: 0.0547

 41/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9787 - loss: 0.0588

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9775 - loss: 0.0649

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9785 - loss: 0.0626

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9787 - loss: 0.0623

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9783 - loss: 0.0620

 51/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9786 - loss: 0.0615

 53/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9794 - loss: 0.0606

 55/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9790 - loss: 0.0621

 57/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9770 - loss: 0.0644

 59/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9767 - loss: 0.0650

 61/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9754 - loss: 0.0685

 63/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9752 - loss: 0.0697

 65/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9760 - loss: 0.0686

 67/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9767 - loss: 0.0679

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9764 - loss: 0.0690

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9771 - loss: 0.0675

 73/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9773 - loss: 0.0676

 75/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9767 - loss: 0.0689

 77/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9761 - loss: 0.0707

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9759 - loss: 0.0709

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9765 - loss: 0.0698

 83/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9763 - loss: 0.0699

 85/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9761 - loss: 0.0710

 87/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9759 - loss: 0.0710

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9758 - loss: 0.0714

 91/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9763 - loss: 0.0705

 93/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9761 - loss: 0.0706

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9763 - loss: 0.0698

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9758 - loss: 0.0703

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9751 - loss: 0.0729

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9746 - loss: 0.0733

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9748 - loss: 0.0730

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9747 - loss: 0.0741

107/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9746 - loss: 0.0742

109/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9751 - loss: 0.0732

111/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9747 - loss: 0.0769

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9743 - loss: 0.0772

115/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9734 - loss: 0.0796

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9733 - loss: 0.0798

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9730 - loss: 0.0815

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9734 - loss: 0.0810

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9736 - loss: 0.0811

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9740 - loss: 0.0804

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9732 - loss: 0.0817

129/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9734 - loss: 0.0819

131/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9726 - loss: 0.0837

133/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9725 - loss: 0.0833

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9725 - loss: 0.0834

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9729 - loss: 0.0827

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9723 - loss: 0.0830

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9723 - loss: 0.0830

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9725 - loss: 0.0829

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9726 - loss: 0.0821

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9728 - loss: 0.0819

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9727 - loss: 0.0815

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9725 - loss: 0.0821

153/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9726 - loss: 0.0814

155/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9726 - loss: 0.0815

157/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9721 - loss: 0.0820

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9721 - loss: 0.0819

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9724 - loss: 0.0811

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9724 - loss: 0.0810

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9720 - loss: 0.0820

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9714 - loss: 0.0838

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9708 - loss: 0.0846

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9709 - loss: 0.0844

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9713 - loss: 0.0839

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9712 - loss: 0.0840

177/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9709 - loss: 0.0847

179/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9710 - loss: 0.0850

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9712 - loss: 0.0853

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9713 - loss: 0.0851

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9713 - loss: 0.0849

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9716 - loss: 0.0843

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9714 - loss: 0.0842

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9715 - loss: 0.0837

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9718 - loss: 0.0832

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9720 - loss: 0.0828

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9721 - loss: 0.0827

199/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9720 - loss: 0.0832

201/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9720 - loss: 0.0831

203/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9723 - loss: 0.0824

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9726 - loss: 0.0819

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9727 - loss: 0.0815

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9728 - loss: 0.0810

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9730 - loss: 0.0803

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9732 - loss: 0.0803

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9728 - loss: 0.0811

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9728 - loss: 0.0815

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9729 - loss: 0.0818

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9729 - loss: 0.0816

223/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9725 - loss: 0.0825

225/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9725 - loss: 0.0825

227/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9725 - loss: 0.0822

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9722 - loss: 0.0838

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9721 - loss: 0.0834

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9721 - loss: 0.0834

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9718 - loss: 0.0838

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9717 - loss: 0.0840

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9716 - loss: 0.0840

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9715 - loss: 0.0842

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9716 - loss: 0.0840

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9717 - loss: 0.0840

247/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9717 - loss: 0.0842

249/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9715 - loss: 0.0845

251/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9715 - loss: 0.0846

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9716 - loss: 0.0846

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9714 - loss: 0.0850

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9715 - loss: 0.0848

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9715 - loss: 0.0846

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9715 - loss: 0.0845

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9716 - loss: 0.0842

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9715 - loss: 0.0846

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9714 - loss: 0.0845

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9714 - loss: 0.0844

271/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9712 - loss: 0.0853

273/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9710 - loss: 0.0857

275/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9709 - loss: 0.0856

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9708 - loss: 0.0863

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9705 - loss: 0.0864

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9703 - loss: 0.0864

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9702 - loss: 0.0866

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9703 - loss: 0.0864

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9703 - loss: 0.0863

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9699 - loss: 0.0866

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9697 - loss: 0.0873

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9697 - loss: 0.0874

295/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9695 - loss: 0.0877

297/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9694 - loss: 0.0878

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9694 - loss: 0.0877

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9696 - loss: 0.0873

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9695 - loss: 0.0875

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9696 - loss: 0.0874

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9697 - loss: 0.0874

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9698 - loss: 0.0872

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9700 - loss: 0.0868

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9701 - loss: 0.0865

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9700 - loss: 0.0866

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9699 - loss: 0.0866

319/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9698 - loss: 0.0867

321/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9698 - loss: 0.0869

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9697 - loss: 0.0870

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9698 - loss: 0.0870

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9699 - loss: 0.0867

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9699 - loss: 0.0868

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9699 - loss: 0.0870

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9699 - loss: 0.0869

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9701 - loss: 0.0867

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9699 - loss: 0.0869

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9700 - loss: 0.0866

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9702 - loss: 0.0862

343/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9702 - loss: 0.0862

345/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9700 - loss: 0.0865

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9701 - loss: 0.0863

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9701 - loss: 0.0861

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9700 - loss: 0.0861

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9701 - loss: 0.0860

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9700 - loss: 0.0863

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9702 - loss: 0.0859

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9703 - loss: 0.0856

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9705 - loss: 0.0852

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9706 - loss: 0.0854

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9705 - loss: 0.0856

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9706 - loss: 0.0852

369/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9705 - loss: 0.0853

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9706 - loss: 0.0852

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9707 - loss: 0.0850

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9708 - loss: 0.0848

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9708 - loss: 0.0847

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9706 - loss: 0.0855

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9708 - loss: 0.0852

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9708 - loss: 0.0850

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9709 - loss: 0.0850

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9708 - loss: 0.0853

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9707 - loss: 0.0855

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9705 - loss: 0.0857

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9702 - loss: 0.0860

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9702 - loss: 0.0860

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9702 - loss: 0.0859

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9702 - loss: 0.0857

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9703 - loss: 0.0855

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9704 - loss: 0.0855

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9704 - loss: 0.0857

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9702 - loss: 0.0857

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9702 - loss: 0.0856

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9703 - loss: 0.0853

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9703 - loss: 0.0854

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9703 - loss: 0.0861

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9701 - loss: 0.0863

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9700 - loss: 0.0862

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9702 - loss: 0.0860

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9703 - loss: 0.0858

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9704 - loss: 0.0857

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9705 - loss: 0.0854

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9706 - loss: 0.0852

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9706 - loss: 0.0851

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9706 - loss: 0.0850

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9705 - loss: 0.0850

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9705 - loss: 0.0848

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9705 - loss: 0.0848

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9707 - loss: 0.0846

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9708 - loss: 0.0842

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9709 - loss: 0.0841

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9708 - loss: 0.0844

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9708 - loss: 0.0843

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9708 - loss: 0.0844

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9706 - loss: 0.0848

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9707 - loss: 0.0845

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9709 - loss: 0.0842

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9709 - loss: 0.0842

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9706 - loss: 0.0846

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9705 - loss: 0.0849

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9705 - loss: 0.0848

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9704 - loss: 0.0849

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9705 - loss: 0.0847

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9705 - loss: 0.0848

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9706 - loss: 0.0847

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9707 - loss: 0.0845

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9706 - loss: 0.0843

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9705 - loss: 0.0844

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9706 - loss: 0.0842

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9706 - loss: 0.0841

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9705 - loss: 0.0841

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9706 - loss: 0.0839

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9707 - loss: 0.0836

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9707 - loss: 0.0836

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9707 - loss: 0.0835

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9706 - loss: 0.0835

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9706 - loss: 0.0837

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9704 - loss: 0.0839

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9704 - loss: 0.0840

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9705 - loss: 0.0841

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9705 - loss: 0.0839

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9706 - loss: 0.0837

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9706 - loss: 0.0837

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9703 - loss: 0.0843

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9704 - loss: 0.0842

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9705 - loss: 0.0839

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9706 - loss: 0.0837

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9705 - loss: 0.0837

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9705 - loss: 0.0836

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9706 - loss: 0.0835

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9707 - loss: 0.0834

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9708 - loss: 0.0833

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9707 - loss: 0.0834

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9707 - loss: 0.0832

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9707 - loss: 0.0831

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9708 - loss: 0.0828

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9708 - loss: 0.0829

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9708 - loss: 0.0827

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9708 - loss: 0.0827

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9707 - loss: 0.0829

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9708 - loss: 0.0828

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9708 - loss: 0.0828

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9709 - loss: 0.0826

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9709 - loss: 0.0824

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9710 - loss: 0.0824

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9710 - loss: 0.0824

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9709 - loss: 0.0826

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9709 - loss: 0.0829

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9709 - loss: 0.0827

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9709 - loss: 0.0831

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9709 - loss: 0.0830

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9708 - loss: 0.0830

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9709 - loss: 0.0827

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9709 - loss: 0.0830

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9710 - loss: 0.0828

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9710 - loss: 0.0827

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9710 - loss: 0.0827

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9711 - loss: 0.0825

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9711 - loss: 0.0824

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9712 - loss: 0.0822

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9713 - loss: 0.0821

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9713 - loss: 0.0821

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9713 - loss: 0.0820

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9713 - loss: 0.0818

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9713 - loss: 0.0818

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9713 - loss: 0.0818

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9714 - loss: 0.0816

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9715 - loss: 0.0814

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9715 - loss: 0.0813

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9715 - loss: 0.0812

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9715 - loss: 0.0812

606/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.9715 - loss: 0.0812 - val_accuracy: 0.9591 - val_loss: 0.1724

Epoch 23/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 38s 64ms/step - accuracy: 1.0000 - loss: 0.0080

  3/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.9896 - loss: 0.0246

  5/606 ━━━━━━━━━━━━━━━━━━━━ 27s 45ms/step - accuracy: 0.9812 - loss: 0.0267

  7/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9777 - loss: 0.0435

  9/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9757 - loss: 0.0502

 11/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9744 - loss: 0.0487

 13/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9712 - loss: 0.0591

 15/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9750 - loss: 0.0529

 17/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9779 - loss: 0.0489

 19/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9753 - loss: 0.0701

 21/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9777 - loss: 0.0655

 23/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9783 - loss: 0.0621

 25/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9787 - loss: 0.0607

 27/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9757 - loss: 0.0709

 29/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9763 - loss: 0.0692

 31/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9768 - loss: 0.0677

 33/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9773 - loss: 0.0699

 35/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9777 - loss: 0.0685

 37/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9764 - loss: 0.0689

 39/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9768 - loss: 0.0674

 41/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9771 - loss: 0.0661

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9767 - loss: 0.0654

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9771 - loss: 0.0640

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9767 - loss: 0.0651

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9764 - loss: 0.0656

 51/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9761 - loss: 0.0655

 53/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9770 - loss: 0.0636

 55/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9778 - loss: 0.0631

 57/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9775 - loss: 0.0623

 59/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9778 - loss: 0.0613

 61/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9775 - loss: 0.0610

 63/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9762 - loss: 0.0648

 65/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9764 - loss: 0.0636

 67/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9762 - loss: 0.0637

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9751 - loss: 0.0648

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9745 - loss: 0.0654

 73/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9743 - loss: 0.0649

 75/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9742 - loss: 0.0659

 77/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9736 - loss: 0.0660

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9743 - loss: 0.0655

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9745 - loss: 0.0649

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9748 - loss: 0.0649

 85/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9746 - loss: 0.0648

 87/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9745 - loss: 0.0657

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9747 - loss: 0.0651

 91/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9742 - loss: 0.0655

 93/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9745 - loss: 0.0664

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9743 - loss: 0.0663

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9745 - loss: 0.0658

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9741 - loss: 0.0660

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9740 - loss: 0.0672

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9742 - loss: 0.0669

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9738 - loss: 0.0682

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9743 - loss: 0.0674

109/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9739 - loss: 0.0703

111/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9738 - loss: 0.0707

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9737 - loss: 0.0716

115/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9731 - loss: 0.0737

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9728 - loss: 0.0745

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9730 - loss: 0.0743

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9731 - loss: 0.0743

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9736 - loss: 0.0735

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9737 - loss: 0.0736

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9739 - loss: 0.0733

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9736 - loss: 0.0737

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9733 - loss: 0.0762

133/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9734 - loss: 0.0760

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9731 - loss: 0.0765

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9729 - loss: 0.0763

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9721 - loss: 0.0771

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9716 - loss: 0.0777

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9720 - loss: 0.0770

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9716 - loss: 0.0778

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9717 - loss: 0.0776

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9717 - loss: 0.0778

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9716 - loss: 0.0782

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9718 - loss: 0.0779

155/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9718 - loss: 0.0777

157/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9719 - loss: 0.0772

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9717 - loss: 0.0787

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9717 - loss: 0.0784

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9714 - loss: 0.0783

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9710 - loss: 0.0784

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9708 - loss: 0.0785

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9708 - loss: 0.0786

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9708 - loss: 0.0788

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9707 - loss: 0.0794

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9704 - loss: 0.0813

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9705 - loss: 0.0811

179/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9701 - loss: 0.0813

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9701 - loss: 0.0811

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9701 - loss: 0.0816

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9701 - loss: 0.0816

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9698 - loss: 0.0830

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9696 - loss: 0.0835

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9696 - loss: 0.0836

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9697 - loss: 0.0832

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9697 - loss: 0.0832

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9695 - loss: 0.0831

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9697 - loss: 0.0829

201/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9698 - loss: 0.0826

203/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9698 - loss: 0.0836

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9701 - loss: 0.0833

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9697 - loss: 0.0847

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9698 - loss: 0.0843

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9699 - loss: 0.0843

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9701 - loss: 0.0838

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9701 - loss: 0.0840

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9703 - loss: 0.0834

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9705 - loss: 0.0833

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9706 - loss: 0.0830

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9703 - loss: 0.0833

225/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9701 - loss: 0.0835

227/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9697 - loss: 0.0843

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9696 - loss: 0.0843

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9696 - loss: 0.0842

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9694 - loss: 0.0852

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9694 - loss: 0.0849

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9695 - loss: 0.0848

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9693 - loss: 0.0849

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9693 - loss: 0.0849

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9693 - loss: 0.0847

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9694 - loss: 0.0845

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9694 - loss: 0.0844

249/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9694 - loss: 0.0843

251/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9694 - loss: 0.0843

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9691 - loss: 0.0848

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9690 - loss: 0.0849

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9689 - loss: 0.0851

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9689 - loss: 0.0850

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9691 - loss: 0.0846

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9692 - loss: 0.0845

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9695 - loss: 0.0840

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9696 - loss: 0.0838

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9694 - loss: 0.0839

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9694 - loss: 0.0839

273/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9697 - loss: 0.0834

275/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9698 - loss: 0.0833

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9699 - loss: 0.0832

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9695 - loss: 0.0841

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9696 - loss: 0.0838

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9697 - loss: 0.0837

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9696 - loss: 0.0841

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9695 - loss: 0.0852

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9697 - loss: 0.0849

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9696 - loss: 0.0851

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9695 - loss: 0.0850

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9695 - loss: 0.0853

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9697 - loss: 0.0850

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9697 - loss: 0.0848

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9696 - loss: 0.0848

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9696 - loss: 0.0848

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9696 - loss: 0.0847

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9696 - loss: 0.0846

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9695 - loss: 0.0847

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9696 - loss: 0.0844

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9695 - loss: 0.0845

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9697 - loss: 0.0842

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9698 - loss: 0.0838

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9698 - loss: 0.0838

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9696 - loss: 0.0840

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9694 - loss: 0.0846

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9695 - loss: 0.0844

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9695 - loss: 0.0844

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9694 - loss: 0.0856

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9695 - loss: 0.0854

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9694 - loss: 0.0859

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9696 - loss: 0.0855

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9697 - loss: 0.0853

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9698 - loss: 0.0850

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9697 - loss: 0.0851

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9697 - loss: 0.0855

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9696 - loss: 0.0856

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9694 - loss: 0.0859

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9696 - loss: 0.0856

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9697 - loss: 0.0852

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9696 - loss: 0.0852

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9698 - loss: 0.0849

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9699 - loss: 0.0846

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9700 - loss: 0.0844

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9700 - loss: 0.0844

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9701 - loss: 0.0841

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9702 - loss: 0.0841

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9701 - loss: 0.0840

369/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9700 - loss: 0.0841

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9700 - loss: 0.0841

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9701 - loss: 0.0838

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9703 - loss: 0.0834

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9702 - loss: 0.0833

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9703 - loss: 0.0836

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9702 - loss: 0.0837

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9703 - loss: 0.0835

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9703 - loss: 0.0835

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9704 - loss: 0.0834

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9704 - loss: 0.0832

391/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9703 - loss: 0.0832

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9703 - loss: 0.0831

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9704 - loss: 0.0830

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9706 - loss: 0.0827

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9706 - loss: 0.0826

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9705 - loss: 0.0827

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9706 - loss: 0.0826

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9706 - loss: 0.0824

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9706 - loss: 0.0822

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9707 - loss: 0.0819

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9708 - loss: 0.0817

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9707 - loss: 0.0817

415/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9707 - loss: 0.0818

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9708 - loss: 0.0815

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9709 - loss: 0.0813

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9708 - loss: 0.0818

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9708 - loss: 0.0818

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9709 - loss: 0.0817

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9709 - loss: 0.0814

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9709 - loss: 0.0816

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9709 - loss: 0.0814

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9710 - loss: 0.0813

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9710 - loss: 0.0811

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9712 - loss: 0.0809

439/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9710 - loss: 0.0810

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9711 - loss: 0.0810

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9711 - loss: 0.0808

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9710 - loss: 0.0813

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9709 - loss: 0.0816

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9708 - loss: 0.0815

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9708 - loss: 0.0815

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9708 - loss: 0.0813

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9708 - loss: 0.0813

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9708 - loss: 0.0814

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9709 - loss: 0.0812

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9710 - loss: 0.0811

463/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9709 - loss: 0.0812

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9710 - loss: 0.0811

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9711 - loss: 0.0809

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9712 - loss: 0.0807

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9713 - loss: 0.0806

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9714 - loss: 0.0804

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9713 - loss: 0.0804

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9714 - loss: 0.0802

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9713 - loss: 0.0802

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9713 - loss: 0.0800

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9712 - loss: 0.0801

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9711 - loss: 0.0801

487/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9712 - loss: 0.0801

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9713 - loss: 0.0798

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9714 - loss: 0.0797

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9713 - loss: 0.0797

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9713 - loss: 0.0799

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9713 - loss: 0.0798

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9714 - loss: 0.0796

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9714 - loss: 0.0796

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9714 - loss: 0.0795

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9713 - loss: 0.0795

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9713 - loss: 0.0795

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9713 - loss: 0.0794

511/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9714 - loss: 0.0794

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9714 - loss: 0.0794

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9715 - loss: 0.0791

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9714 - loss: 0.0794

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9714 - loss: 0.0795

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9714 - loss: 0.0794

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9716 - loss: 0.0792

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9717 - loss: 0.0790

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9716 - loss: 0.0790

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9717 - loss: 0.0788

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9717 - loss: 0.0788

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9716 - loss: 0.0790

535/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9715 - loss: 0.0789

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9715 - loss: 0.0789

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9716 - loss: 0.0788

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9716 - loss: 0.0786

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9716 - loss: 0.0786

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9717 - loss: 0.0785

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9717 - loss: 0.0786

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9717 - loss: 0.0784

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9716 - loss: 0.0784

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9716 - loss: 0.0785

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9716 - loss: 0.0787

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9717 - loss: 0.0784

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9717 - loss: 0.0786

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9716 - loss: 0.0787

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9716 - loss: 0.0786

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9717 - loss: 0.0785

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9717 - loss: 0.0785

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9717 - loss: 0.0786

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9718 - loss: 0.0784

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9719 - loss: 0.0782

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9719 - loss: 0.0782

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9719 - loss: 0.0780

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9720 - loss: 0.0779

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9721 - loss: 0.0778

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9721 - loss: 0.0776

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9721 - loss: 0.0775

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9721 - loss: 0.0776

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9720 - loss: 0.0776

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9720 - loss: 0.0775

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9720 - loss: 0.0774

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9721 - loss: 0.0773

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9722 - loss: 0.0771

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9722 - loss: 0.0770

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9723 - loss: 0.0768

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9724 - loss: 0.0766

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9724 - loss: 0.0767

606/606 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.9724 - loss: 0.0766 - val_accuracy: 0.9623 - val_loss: 0.1628

Epoch 24/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.9688 - loss: 0.0743

  3/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9688 - loss: 0.0509

  5/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9812 - loss: 0.0338

  7/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9821 - loss: 0.0312

  9/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9861 - loss: 0.0270

 11/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9886 - loss: 0.0229

 13/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9880 - loss: 0.0358

 15/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9875 - loss: 0.0368

 17/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9871 - loss: 0.0358

 19/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9836 - loss: 0.0424

 21/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9836 - loss: 0.0429

 23/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9837 - loss: 0.0483

 25/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9825 - loss: 0.0582

 27/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9826 - loss: 0.0605

 29/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9828 - loss: 0.0613

 31/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9829 - loss: 0.0599

 33/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9773 - loss: 0.0683

 35/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9768 - loss: 0.0685

 37/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9780 - loss: 0.0659

 39/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9768 - loss: 0.0669

 41/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9756 - loss: 0.0748

 43/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9753 - loss: 0.0729

 45/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9764 - loss: 0.0699

 47/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9767 - loss: 0.0678

 49/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9758 - loss: 0.0691

 51/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9767 - loss: 0.0670

 53/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9752 - loss: 0.0686

 55/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9750 - loss: 0.0682

 57/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9753 - loss: 0.0669

 59/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9751 - loss: 0.0672

 61/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9739 - loss: 0.0698

 63/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9747 - loss: 0.0683

 65/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9750 - loss: 0.0675

 67/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9748 - loss: 0.0691

 69/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9755 - loss: 0.0685

 71/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9762 - loss: 0.0673

 73/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9765 - loss: 0.0668

 75/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9758 - loss: 0.0679

 77/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9756 - loss: 0.0683

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9763 - loss: 0.0672

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9761 - loss: 0.0680

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9759 - loss: 0.0682

 85/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9765 - loss: 0.0672

 87/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9759 - loss: 0.0703

 89/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9761 - loss: 0.0695

 91/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9760 - loss: 0.0691

 93/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9755 - loss: 0.0692

 95/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9757 - loss: 0.0686

 97/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9755 - loss: 0.0695

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9751 - loss: 0.0716

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9743 - loss: 0.0730

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9745 - loss: 0.0723

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9744 - loss: 0.0723

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9749 - loss: 0.0715

109/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9753 - loss: 0.0704

111/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9755 - loss: 0.0715

113/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9757 - loss: 0.0712

115/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9753 - loss: 0.0722

117/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9746 - loss: 0.0739

119/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9751 - loss: 0.0729

121/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9749 - loss: 0.0730

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9743 - loss: 0.0750

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9747 - loss: 0.0741

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9747 - loss: 0.0753

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9746 - loss: 0.0756

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9742 - loss: 0.0758

133/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9744 - loss: 0.0755

135/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9748 - loss: 0.0750

137/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9747 - loss: 0.0748

139/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9739 - loss: 0.0756

141/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9743 - loss: 0.0748

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9744 - loss: 0.0746

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9748 - loss: 0.0739

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9749 - loss: 0.0733

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9750 - loss: 0.0730

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9750 - loss: 0.0732

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9749 - loss: 0.0735

155/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9752 - loss: 0.0728

157/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9753 - loss: 0.0726

159/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9754 - loss: 0.0725

161/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9746 - loss: 0.0742

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9749 - loss: 0.0737

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9746 - loss: 0.0744

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9742 - loss: 0.0753

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9745 - loss: 0.0748

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9746 - loss: 0.0749

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9747 - loss: 0.0746

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9750 - loss: 0.0741

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9746 - loss: 0.0747

179/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9747 - loss: 0.0743

181/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9748 - loss: 0.0742

183/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9749 - loss: 0.0739

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9748 - loss: 0.0739

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9744 - loss: 0.0742

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9742 - loss: 0.0744

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9740 - loss: 0.0743

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9743 - loss: 0.0738

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9744 - loss: 0.0733

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9746 - loss: 0.0727

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9749 - loss: 0.0722

201/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9751 - loss: 0.0717

203/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9752 - loss: 0.0714

205/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9752 - loss: 0.0715

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9752 - loss: 0.0711

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9750 - loss: 0.0714

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9751 - loss: 0.0712

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9748 - loss: 0.0716

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9750 - loss: 0.0710

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9749 - loss: 0.0709

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9746 - loss: 0.0721

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9743 - loss: 0.0731

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9742 - loss: 0.0731

225/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9737 - loss: 0.0741

227/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9736 - loss: 0.0742

229/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9737 - loss: 0.0741

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9738 - loss: 0.0739

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9738 - loss: 0.0740

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9741 - loss: 0.0735

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9740 - loss: 0.0735

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9740 - loss: 0.0735

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9739 - loss: 0.0732

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9738 - loss: 0.0739

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9735 - loss: 0.0747

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9732 - loss: 0.0749

249/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9729 - loss: 0.0752

251/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9731 - loss: 0.0749

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9732 - loss: 0.0746

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9734 - loss: 0.0743

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9734 - loss: 0.0742

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9733 - loss: 0.0741

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9735 - loss: 0.0738

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9736 - loss: 0.0737

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9737 - loss: 0.0735

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9738 - loss: 0.0734

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9737 - loss: 0.0735

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9739 - loss: 0.0730

273/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9740 - loss: 0.0731

275/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9740 - loss: 0.0734

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9738 - loss: 0.0746

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9738 - loss: 0.0748

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9738 - loss: 0.0748

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9738 - loss: 0.0746

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9738 - loss: 0.0749

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9740 - loss: 0.0746

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9739 - loss: 0.0749

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9741 - loss: 0.0747

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9741 - loss: 0.0747

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9743 - loss: 0.0744

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9742 - loss: 0.0743

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9740 - loss: 0.0748

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9740 - loss: 0.0745

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9740 - loss: 0.0744

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9742 - loss: 0.0742

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9743 - loss: 0.0738

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9743 - loss: 0.0737

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9742 - loss: 0.0741

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9741 - loss: 0.0742

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9743 - loss: 0.0738

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9743 - loss: 0.0737

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9742 - loss: 0.0735

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9742 - loss: 0.0737

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9743 - loss: 0.0736

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9743 - loss: 0.0734

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9743 - loss: 0.0732

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9744 - loss: 0.0734

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9744 - loss: 0.0732

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9746 - loss: 0.0729

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9744 - loss: 0.0730

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9745 - loss: 0.0727

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9745 - loss: 0.0730

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9745 - loss: 0.0728

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9743 - loss: 0.0734

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9742 - loss: 0.0734

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9742 - loss: 0.0734

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9743 - loss: 0.0731

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9744 - loss: 0.0729

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9744 - loss: 0.0730

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9745 - loss: 0.0728

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9746 - loss: 0.0725

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9747 - loss: 0.0723

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9748 - loss: 0.0719

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9749 - loss: 0.0718

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9748 - loss: 0.0722

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9748 - loss: 0.0721

369/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9748 - loss: 0.0720

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9749 - loss: 0.0718

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9750 - loss: 0.0715

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9752 - loss: 0.0713

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9753 - loss: 0.0711

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9752 - loss: 0.0712

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9751 - loss: 0.0712

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9752 - loss: 0.0711

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9752 - loss: 0.0712

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9753 - loss: 0.0709

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9754 - loss: 0.0707

391/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9755 - loss: 0.0705

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9756 - loss: 0.0702

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9756 - loss: 0.0702

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9756 - loss: 0.0703

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9756 - loss: 0.0703

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9755 - loss: 0.0705

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9756 - loss: 0.0705

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9755 - loss: 0.0704

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9757 - loss: 0.0702

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9756 - loss: 0.0703

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9756 - loss: 0.0703

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9757 - loss: 0.0702

415/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9758 - loss: 0.0706

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9759 - loss: 0.0703

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9758 - loss: 0.0702

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9756 - loss: 0.0706

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9755 - loss: 0.0707

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9754 - loss: 0.0707

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9756 - loss: 0.0706

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9755 - loss: 0.0706

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9756 - loss: 0.0704

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9756 - loss: 0.0703

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9756 - loss: 0.0702

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9758 - loss: 0.0699

439/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9758 - loss: 0.0698

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9758 - loss: 0.0697

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9755 - loss: 0.0701

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9756 - loss: 0.0700

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9755 - loss: 0.0704

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9756 - loss: 0.0702

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9757 - loss: 0.0700

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9756 - loss: 0.0701

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9757 - loss: 0.0699

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9757 - loss: 0.0700

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9757 - loss: 0.0700

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9757 - loss: 0.0700

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9757 - loss: 0.0699

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9757 - loss: 0.0699

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9756 - loss: 0.0698

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9755 - loss: 0.0700

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9755 - loss: 0.0702

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9754 - loss: 0.0702

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9754 - loss: 0.0701

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9754 - loss: 0.0699

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9754 - loss: 0.0699

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9755 - loss: 0.0697

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9756 - loss: 0.0695

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - accuracy: 0.9757 - loss: 0.0694

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9757 - loss: 0.0692

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9758 - loss: 0.0690

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9758 - loss: 0.0690

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9757 - loss: 0.0690

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9758 - loss: 0.0688

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9757 - loss: 0.0696

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9756 - loss: 0.0696

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9757 - loss: 0.0694

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9757 - loss: 0.0693

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9757 - loss: 0.0692

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9758 - loss: 0.0690

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9758 - loss: 0.0690

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9758 - loss: 0.0690

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9758 - loss: 0.0691

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9758 - loss: 0.0691

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9756 - loss: 0.0696

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9756 - loss: 0.0696

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9756 - loss: 0.0696

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9755 - loss: 0.0698

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9755 - loss: 0.0697

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9756 - loss: 0.0695

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9757 - loss: 0.0693

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9755 - loss: 0.0699

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.9755 - loss: 0.0698

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9755 - loss: 0.0699

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9754 - loss: 0.0698

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9755 - loss: 0.0698

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9755 - loss: 0.0698

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9755 - loss: 0.0697

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9756 - loss: 0.0700

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9755 - loss: 0.0701

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9755 - loss: 0.0700

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9755 - loss: 0.0700

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9754 - loss: 0.0702

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9754 - loss: 0.0704

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.9754 - loss: 0.0705

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9755 - loss: 0.0703

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9754 - loss: 0.0703

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9755 - loss: 0.0701

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9754 - loss: 0.0701

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9753 - loss: 0.0709

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9753 - loss: 0.0709

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9754 - loss: 0.0707

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9755 - loss: 0.0707

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9755 - loss: 0.0706

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9756 - loss: 0.0705

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9757 - loss: 0.0704

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9757 - loss: 0.0703

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9757 - loss: 0.0702

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9756 - loss: 0.0702

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9757 - loss: 0.0701

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9756 - loss: 0.0701

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9756 - loss: 0.0700

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9757 - loss: 0.0698

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9757 - loss: 0.0697

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9757 - loss: 0.0697

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9758 - loss: 0.0695

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9759 - loss: 0.0693

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9758 - loss: 0.0693

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9759 - loss: 0.0693

606/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.9759 - loss: 0.0692 - val_accuracy: 0.9576 - val_loss: 0.1854

Epoch 25/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 1.0000 - loss: 0.0333

  3/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 1.0000 - loss: 0.0215

  5/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9937 - loss: 0.0266

  7/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9911 - loss: 0.0283

  9/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9931 - loss: 0.0233

 11/606 ━━━━━━━━━━━━━━━━━━━━ 25s 42ms/step - accuracy: 0.9886 - loss: 0.0300

 13/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9904 - loss: 0.0277

 15/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9875 - loss: 0.0316

 17/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9871 - loss: 0.0348

 19/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9868 - loss: 0.0397

 21/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9866 - loss: 0.0438

 23/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9864 - loss: 0.0434

 25/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9862 - loss: 0.0427

 27/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9850 - loss: 0.0481

 29/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9860 - loss: 0.0454

 31/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9859 - loss: 0.0467

 33/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9858 - loss: 0.0451

 35/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9866 - loss: 0.0438

 37/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9873 - loss: 0.0425

 39/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9880 - loss: 0.0410

 41/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9863 - loss: 0.0455

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9869 - loss: 0.0444

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9875 - loss: 0.0431

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9880 - loss: 0.0416

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9885 - loss: 0.0412

 51/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9877 - loss: 0.0424

 53/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9882 - loss: 0.0410

 55/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9881 - loss: 0.0404

 57/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9885 - loss: 0.0394

 59/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9868 - loss: 0.0461

 61/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9857 - loss: 0.0492

 63/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9856 - loss: 0.0486

 65/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9846 - loss: 0.0502

 67/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9841 - loss: 0.0512

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9823 - loss: 0.0545

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9828 - loss: 0.0540

 73/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9824 - loss: 0.0552

 75/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9829 - loss: 0.0545

 77/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9817 - loss: 0.0569

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9814 - loss: 0.0579

 81/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9819 - loss: 0.0571

 83/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9823 - loss: 0.0567

 85/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9816 - loss: 0.0581

 87/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9813 - loss: 0.0582

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9814 - loss: 0.0582

 91/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9818 - loss: 0.0576

 93/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9819 - loss: 0.0577

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9819 - loss: 0.0580

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9813 - loss: 0.0592

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9807 - loss: 0.0606

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9808 - loss: 0.0604

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9809 - loss: 0.0600

105/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9810 - loss: 0.0597

107/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9810 - loss: 0.0592

109/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9808 - loss: 0.0594

111/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9797 - loss: 0.0624

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9801 - loss: 0.0617

115/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9796 - loss: 0.0631

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9794 - loss: 0.0634

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9793 - loss: 0.0646

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9791 - loss: 0.0647

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9779 - loss: 0.0668

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9778 - loss: 0.0666

127/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9779 - loss: 0.0661

129/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9780 - loss: 0.0659

131/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9781 - loss: 0.0661

133/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9777 - loss: 0.0666

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9775 - loss: 0.0667

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9776 - loss: 0.0662

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9775 - loss: 0.0665

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9776 - loss: 0.0660

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9777 - loss: 0.0656

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9780 - loss: 0.0649

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9775 - loss: 0.0662

149/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9773 - loss: 0.0666

151/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9776 - loss: 0.0661

153/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9775 - loss: 0.0662

155/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9772 - loss: 0.0665

157/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9771 - loss: 0.0667

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9772 - loss: 0.0662

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9773 - loss: 0.0664

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9772 - loss: 0.0674

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9771 - loss: 0.0674

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9770 - loss: 0.0682

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9767 - loss: 0.0688

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9764 - loss: 0.0687

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9763 - loss: 0.0689

175/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9761 - loss: 0.0693

177/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9763 - loss: 0.0689

179/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9763 - loss: 0.0689

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9763 - loss: 0.0686

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9764 - loss: 0.0685

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9765 - loss: 0.0685

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9764 - loss: 0.0691

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9762 - loss: 0.0690

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9763 - loss: 0.0686

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9765 - loss: 0.0681

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9763 - loss: 0.0684

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9765 - loss: 0.0678

199/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9764 - loss: 0.0678

201/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9764 - loss: 0.0679

203/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9766 - loss: 0.0675

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9768 - loss: 0.0673

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9768 - loss: 0.0673

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9770 - loss: 0.0669

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9770 - loss: 0.0667

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9771 - loss: 0.0663

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9767 - loss: 0.0668

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9764 - loss: 0.0677

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9762 - loss: 0.0687

221/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9761 - loss: 0.0688

223/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9763 - loss: 0.0684

225/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9758 - loss: 0.0699

227/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9759 - loss: 0.0698

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9758 - loss: 0.0700

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9761 - loss: 0.0698

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9761 - loss: 0.0695

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9759 - loss: 0.0698

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9760 - loss: 0.0699

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9761 - loss: 0.0697

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9760 - loss: 0.0695

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9757 - loss: 0.0697

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9758 - loss: 0.0696

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - accuracy: 0.9755 - loss: 0.0700

249/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9754 - loss: 0.0706

251/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9753 - loss: 0.0710

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9752 - loss: 0.0709

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9750 - loss: 0.0711

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9752 - loss: 0.0707

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9753 - loss: 0.0704

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9752 - loss: 0.0704

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9754 - loss: 0.0700

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9754 - loss: 0.0698

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9754 - loss: 0.0698

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9755 - loss: 0.0696

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 42ms/step - accuracy: 0.9757 - loss: 0.0693

273/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9757 - loss: 0.0694

275/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9758 - loss: 0.0694

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9760 - loss: 0.0691

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9758 - loss: 0.0696

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9756 - loss: 0.0708

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9756 - loss: 0.0708

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9754 - loss: 0.0711

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9752 - loss: 0.0716

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9752 - loss: 0.0714

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9753 - loss: 0.0714

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9753 - loss: 0.0714

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9753 - loss: 0.0712

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 42ms/step - accuracy: 0.9755 - loss: 0.0708

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9756 - loss: 0.0705

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9758 - loss: 0.0701

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9757 - loss: 0.0706

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9755 - loss: 0.0707

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9756 - loss: 0.0709

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9755 - loss: 0.0709

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9757 - loss: 0.0706

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9758 - loss: 0.0702

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9760 - loss: 0.0699

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9760 - loss: 0.0697

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9760 - loss: 0.0699

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.9760 - loss: 0.0697

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9757 - loss: 0.0698

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9759 - loss: 0.0695

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9758 - loss: 0.0694

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9760 - loss: 0.0692

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9759 - loss: 0.0692

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9760 - loss: 0.0693

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9759 - loss: 0.0693

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9758 - loss: 0.0694

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9758 - loss: 0.0692

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9759 - loss: 0.0691

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9758 - loss: 0.0690

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step - accuracy: 0.9758 - loss: 0.0689

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9759 - loss: 0.0687

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9756 - loss: 0.0693

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9758 - loss: 0.0690

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9758 - loss: 0.0689

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9760 - loss: 0.0687

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9761 - loss: 0.0684

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9762 - loss: 0.0682

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9763 - loss: 0.0680

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9763 - loss: 0.0678

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9764 - loss: 0.0677

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9763 - loss: 0.0679

369/606 ━━━━━━━━━━━━━━━━━━━━ 10s 42ms/step - accuracy: 0.9762 - loss: 0.0680

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9761 - loss: 0.0679

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9761 - loss: 0.0679

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9762 - loss: 0.0678

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9762 - loss: 0.0676

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9762 - loss: 0.0675

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9760 - loss: 0.0676

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9761 - loss: 0.0676

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9761 - loss: 0.0674

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9763 - loss: 0.0671

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9761 - loss: 0.0673

391/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9763 - loss: 0.0671

393/606 ━━━━━━━━━━━━━━━━━━━━ 9s 42ms/step - accuracy: 0.9763 - loss: 0.0671

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9763 - loss: 0.0670

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9765 - loss: 0.0667

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9764 - loss: 0.0666

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9765 - loss: 0.0664

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9765 - loss: 0.0662

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9765 - loss: 0.0661

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9765 - loss: 0.0659

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9765 - loss: 0.0658

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9766 - loss: 0.0656

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9765 - loss: 0.0656

415/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9765 - loss: 0.0658

417/606 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - accuracy: 0.9765 - loss: 0.0658

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9763 - loss: 0.0660

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9762 - loss: 0.0659

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 42ms/step - accuracy: 0.9761 - loss: 0.0663

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9760 - loss: 0.0663

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9761 - loss: 0.0661

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9761 - loss: 0.0661

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9762 - loss: 0.0659

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9763 - loss: 0.0658

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9764 - loss: 0.0656

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9764 - loss: 0.0656

439/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9765 - loss: 0.0654

441/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9765 - loss: 0.0654

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9764 - loss: 0.0661

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9764 - loss: 0.0661

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9764 - loss: 0.0660

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9765 - loss: 0.0660

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9765 - loss: 0.0660

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9765 - loss: 0.0659

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9764 - loss: 0.0661

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9764 - loss: 0.0663

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9764 - loss: 0.0661

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9763 - loss: 0.0662

463/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9764 - loss: 0.0660

465/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9765 - loss: 0.0659

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9765 - loss: 0.0658

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9765 - loss: 0.0659

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9764 - loss: 0.0659

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9763 - loss: 0.0660

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9764 - loss: 0.0660

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9765 - loss: 0.0658

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9765 - loss: 0.0657

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9766 - loss: 0.0655

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9767 - loss: 0.0653

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9767 - loss: 0.0652

487/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9768 - loss: 0.0650

489/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9769 - loss: 0.0648

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9768 - loss: 0.0648

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9768 - loss: 0.0648

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9769 - loss: 0.0646

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9769 - loss: 0.0647

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9770 - loss: 0.0644

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9768 - loss: 0.0647

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9769 - loss: 0.0645

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9770 - loss: 0.0643

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9771 - loss: 0.0642

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9772 - loss: 0.0640

511/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9771 - loss: 0.0640

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9772 - loss: 0.0641

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9772 - loss: 0.0641

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9772 - loss: 0.0641

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9773 - loss: 0.0639

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9773 - loss: 0.0638

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9774 - loss: 0.0636

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9774 - loss: 0.0636

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9774 - loss: 0.0637

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9774 - loss: 0.0637

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9774 - loss: 0.0636

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9774 - loss: 0.0635

535/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9773 - loss: 0.0635

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9774 - loss: 0.0635

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9774 - loss: 0.0633

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9775 - loss: 0.0633

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9775 - loss: 0.0632

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9775 - loss: 0.0632

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9775 - loss: 0.0632

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9774 - loss: 0.0635

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9775 - loss: 0.0633

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9775 - loss: 0.0632

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9775 - loss: 0.0632

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9776 - loss: 0.0631

559/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9775 - loss: 0.0633

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9775 - loss: 0.0633

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9776 - loss: 0.0632

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9777 - loss: 0.0630

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9776 - loss: 0.0631

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9776 - loss: 0.0631

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9777 - loss: 0.0629

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9777 - loss: 0.0629

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9778 - loss: 0.0627

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9778 - loss: 0.0625

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9779 - loss: 0.0624

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9779 - loss: 0.0623

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9780 - loss: 0.0622

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9780 - loss: 0.0621

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9781 - loss: 0.0620

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9781 - loss: 0.0618

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9781 - loss: 0.0619

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9781 - loss: 0.0618

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9782 - loss: 0.0617

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9782 - loss: 0.0616

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9781 - loss: 0.0616

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9782 - loss: 0.0614

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9783 - loss: 0.0613

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9783 - loss: 0.0612

606/606 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.9783 - loss: 0.0611 - val_accuracy: 0.9598 - val_loss: 0.1884

Epoch 26/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 38s 64ms/step - accuracy: 1.0000 - loss: 0.0166

  3/606 ━━━━━━━━━━━━━━━━━━━━ 27s 46ms/step - accuracy: 1.0000 - loss: 0.0140

  5/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9875 - loss: 0.0293

  7/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9866 - loss: 0.0305

  9/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9896 - loss: 0.0272

 11/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9915 - loss: 0.0239

 13/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9904 - loss: 0.0240

 15/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9917 - loss: 0.0227

 17/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9926 - loss: 0.0222

 19/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9918 - loss: 0.0269

 21/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9911 - loss: 0.0293

 23/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9918 - loss: 0.0296

 25/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9925 - loss: 0.0277

 27/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9907 - loss: 0.0368

 29/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9903 - loss: 0.0371

 31/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9909 - loss: 0.0351

 33/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9915 - loss: 0.0341

 35/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9902 - loss: 0.0378

 37/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9882 - loss: 0.0412

 39/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9888 - loss: 0.0402

 41/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9893 - loss: 0.0399

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9862 - loss: 0.0484

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9868 - loss: 0.0466

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9867 - loss: 0.0470

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9860 - loss: 0.0489

 51/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9859 - loss: 0.0487

 53/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9841 - loss: 0.0577

 55/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9841 - loss: 0.0564

 57/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9819 - loss: 0.0602

 59/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9815 - loss: 0.0620

 61/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9816 - loss: 0.0620

 63/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9802 - loss: 0.0706

 65/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9793 - loss: 0.0731

 67/606 ━━━━━━━━━━━━━━━━━━━━ 23s 43ms/step - accuracy: 0.9790 - loss: 0.0740

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9792 - loss: 0.0728

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9789 - loss: 0.0743

 73/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9777 - loss: 0.0767

 75/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9779 - loss: 0.0765

 77/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9781 - loss: 0.0770

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9775 - loss: 0.0782

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9776 - loss: 0.0774

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9767 - loss: 0.0803

 85/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9765 - loss: 0.0829

 87/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9763 - loss: 0.0827

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9761 - loss: 0.0834

 91/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9753 - loss: 0.0843

 93/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9745 - loss: 0.0849

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9734 - loss: 0.0873

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9723 - loss: 0.0886

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9725 - loss: 0.0887

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9715 - loss: 0.0894

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9721 - loss: 0.0886

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9723 - loss: 0.0888

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9725 - loss: 0.0883

109/606 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.9725 - loss: 0.0883

111/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9724 - loss: 0.0881

113/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9723 - loss: 0.0889

115/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9723 - loss: 0.0885

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9720 - loss: 0.0923

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9724 - loss: 0.0910

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9721 - loss: 0.0938

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9713 - loss: 0.0960

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9707 - loss: 0.0975

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9712 - loss: 0.0966

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9712 - loss: 0.0964

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9714 - loss: 0.0955

133/606 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.9716 - loss: 0.0954

135/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9715 - loss: 0.0952

137/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9710 - loss: 0.0965

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9714 - loss: 0.0957

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9710 - loss: 0.0961

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9714 - loss: 0.0952

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9718 - loss: 0.0945

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9719 - loss: 0.0938

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9717 - loss: 0.0936

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9719 - loss: 0.0931

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9720 - loss: 0.0923

155/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9720 - loss: 0.0918

157/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9719 - loss: 0.0916

159/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9719 - loss: 0.0921

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9719 - loss: 0.0917

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9720 - loss: 0.0910

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9718 - loss: 0.0919

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9719 - loss: 0.0913

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9719 - loss: 0.0916

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9722 - loss: 0.0910

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9720 - loss: 0.0912

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9720 - loss: 0.0912

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9723 - loss: 0.0905

179/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9724 - loss: 0.0903

181/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9727 - loss: 0.0896

183/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9728 - loss: 0.0894

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9731 - loss: 0.0888

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9731 - loss: 0.0886

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9732 - loss: 0.0881

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9733 - loss: 0.0877

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9734 - loss: 0.0876

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9734 - loss: 0.0873

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9737 - loss: 0.0866

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9736 - loss: 0.0863

201/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9739 - loss: 0.0859

203/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9741 - loss: 0.0853

205/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9742 - loss: 0.0850

207/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9740 - loss: 0.0851

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9741 - loss: 0.0847

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9744 - loss: 0.0842

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9743 - loss: 0.0843

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9743 - loss: 0.0846

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9744 - loss: 0.0846

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9745 - loss: 0.0841

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9745 - loss: 0.0837

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9744 - loss: 0.0844

225/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9743 - loss: 0.0843

227/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9744 - loss: 0.0840

229/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9746 - loss: 0.0836

231/606 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - accuracy: 0.9744 - loss: 0.0837

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9742 - loss: 0.0839

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9745 - loss: 0.0833

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9747 - loss: 0.0829

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9746 - loss: 0.0829

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9746 - loss: 0.0829

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9745 - loss: 0.0830

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9746 - loss: 0.0828

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9747 - loss: 0.0826

249/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9746 - loss: 0.0825

251/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9746 - loss: 0.0824

253/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9743 - loss: 0.0826

255/606 ━━━━━━━━━━━━━━━━━━━━ 15s 43ms/step - accuracy: 0.9744 - loss: 0.0823

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9746 - loss: 0.0818

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9747 - loss: 0.0817

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9747 - loss: 0.0813

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9749 - loss: 0.0807

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9751 - loss: 0.0803

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9752 - loss: 0.0799

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9753 - loss: 0.0795

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9753 - loss: 0.0795

273/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9754 - loss: 0.0792

275/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9752 - loss: 0.0795

277/606 ━━━━━━━━━━━━━━━━━━━━ 14s 43ms/step - accuracy: 0.9752 - loss: 0.0797

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9750 - loss: 0.0803

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9750 - loss: 0.0801

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9750 - loss: 0.0800

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9750 - loss: 0.0799

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9751 - loss: 0.0797

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9751 - loss: 0.0796

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9748 - loss: 0.0805

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9747 - loss: 0.0804

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9747 - loss: 0.0802

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9745 - loss: 0.0802

299/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9746 - loss: 0.0799

301/606 ━━━━━━━━━━━━━━━━━━━━ 13s 43ms/step - accuracy: 0.9748 - loss: 0.0795

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9747 - loss: 0.0794

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9747 - loss: 0.0792

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9749 - loss: 0.0789

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9748 - loss: 0.0790

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9747 - loss: 0.0791

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9748 - loss: 0.0788

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9750 - loss: 0.0785

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9751 - loss: 0.0783

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9750 - loss: 0.0781

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9750 - loss: 0.0780

323/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9749 - loss: 0.0778

325/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9751 - loss: 0.0774

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9752 - loss: 0.0776

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9750 - loss: 0.0775

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9752 - loss: 0.0771

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9751 - loss: 0.0770

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9753 - loss: 0.0766

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9753 - loss: 0.0763

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9752 - loss: 0.0764

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9753 - loss: 0.0762

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9754 - loss: 0.0760

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9755 - loss: 0.0757

347/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9753 - loss: 0.0759

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9755 - loss: 0.0756

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9755 - loss: 0.0755

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9756 - loss: 0.0752

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9757 - loss: 0.0749

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9758 - loss: 0.0746

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9758 - loss: 0.0747

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9759 - loss: 0.0743

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9760 - loss: 0.0741

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9760 - loss: 0.0739

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9761 - loss: 0.0737

369/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9761 - loss: 0.0735

371/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9760 - loss: 0.0735

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9760 - loss: 0.0734

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9758 - loss: 0.0737

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9760 - loss: 0.0736

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9761 - loss: 0.0733

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9761 - loss: 0.0730

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9763 - loss: 0.0727

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9764 - loss: 0.0724

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9764 - loss: 0.0723

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9765 - loss: 0.0721

391/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9766 - loss: 0.0718

393/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9765 - loss: 0.0718

395/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9766 - loss: 0.0715

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9767 - loss: 0.0712

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9767 - loss: 0.0711

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9768 - loss: 0.0709

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9769 - loss: 0.0707

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9769 - loss: 0.0706

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9770 - loss: 0.0703

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9770 - loss: 0.0703

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9771 - loss: 0.0701

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9772 - loss: 0.0699

415/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9772 - loss: 0.0703

417/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9768 - loss: 0.0708

419/606 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - accuracy: 0.9766 - loss: 0.0710

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9767 - loss: 0.0707

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9767 - loss: 0.0705

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9767 - loss: 0.0707

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9768 - loss: 0.0706

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9768 - loss: 0.0704

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9768 - loss: 0.0706

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9768 - loss: 0.0707

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9769 - loss: 0.0704

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9769 - loss: 0.0704

439/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9769 - loss: 0.0704

441/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9770 - loss: 0.0701

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9769 - loss: 0.0703

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9770 - loss: 0.0700

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9771 - loss: 0.0698

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9771 - loss: 0.0697

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9771 - loss: 0.0696

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9772 - loss: 0.0693

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9770 - loss: 0.0697

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9771 - loss: 0.0695

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9771 - loss: 0.0693

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9772 - loss: 0.0690

463/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9771 - loss: 0.0691

465/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9772 - loss: 0.0691

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9771 - loss: 0.0692

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9772 - loss: 0.0690

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9773 - loss: 0.0688

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9773 - loss: 0.0687

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9774 - loss: 0.0686

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9775 - loss: 0.0685

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9774 - loss: 0.0685

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9775 - loss: 0.0683

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9776 - loss: 0.0681

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9776 - loss: 0.0679

487/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9777 - loss: 0.0677

489/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9777 - loss: 0.0677

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9777 - loss: 0.0675

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9778 - loss: 0.0673

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9779 - loss: 0.0671

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9779 - loss: 0.0671

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9779 - loss: 0.0672

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9779 - loss: 0.0671

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9779 - loss: 0.0670

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9779 - loss: 0.0669

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9780 - loss: 0.0667

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9780 - loss: 0.0666

511/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9780 - loss: 0.0665

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9781 - loss: 0.0663

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9782 - loss: 0.0662

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9782 - loss: 0.0661

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9782 - loss: 0.0661

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9782 - loss: 0.0661

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9783 - loss: 0.0660

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9783 - loss: 0.0658

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9784 - loss: 0.0657

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9784 - loss: 0.0656

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9783 - loss: 0.0656

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9782 - loss: 0.0659

535/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9783 - loss: 0.0656

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9782 - loss: 0.0659

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9783 - loss: 0.0658

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9783 - loss: 0.0656

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9782 - loss: 0.0655

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9782 - loss: 0.0656

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9783 - loss: 0.0655

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9783 - loss: 0.0656

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9783 - loss: 0.0656

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9784 - loss: 0.0654

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9784 - loss: 0.0653

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9785 - loss: 0.0651

559/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9784 - loss: 0.0653

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9783 - loss: 0.0653

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9784 - loss: 0.0652

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9785 - loss: 0.0651

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9786 - loss: 0.0649

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9786 - loss: 0.0648

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9787 - loss: 0.0648

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9787 - loss: 0.0647

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9788 - loss: 0.0645

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9789 - loss: 0.0644

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9790 - loss: 0.0642

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9789 - loss: 0.0643

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9789 - loss: 0.0641

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9789 - loss: 0.0640

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9789 - loss: 0.0639

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9788 - loss: 0.0639

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9789 - loss: 0.0638

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9790 - loss: 0.0637

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9789 - loss: 0.0636

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9790 - loss: 0.0634

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9790 - loss: 0.0633

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9791 - loss: 0.0631

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9791 - loss: 0.0631

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9792 - loss: 0.0629

606/606 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.9792 - loss: 0.0629 - val_accuracy: 0.9537 - val_loss: 0.2357

Epoch 27/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 1.0000 - loss: 0.0081

  3/606 ━━━━━━━━━━━━━━━━━━━━ 27s 46ms/step - accuracy: 0.9896 - loss: 0.0250

  5/606 ━━━━━━━━━━━━━━━━━━━━ 27s 46ms/step - accuracy: 0.9812 - loss: 0.0293

  7/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9866 - loss: 0.0245

  9/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9896 - loss: 0.0211

 11/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9886 - loss: 0.0238

 13/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9880 - loss: 0.0233

 15/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9896 - loss: 0.0231

 17/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9908 - loss: 0.0214

 19/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9901 - loss: 0.0272

 21/606 ━━━━━━━━━━━━━━━━━━━━ 25s 43ms/step - accuracy: 0.9896 - loss: 0.0280

 23/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9891 - loss: 0.0280

 25/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9862 - loss: 0.0299

 27/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9861 - loss: 0.0289

 29/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9871 - loss: 0.0273

 31/606 ━━━━━━━━━━━━━━━━━━━━ 24s 43ms/step - accuracy: 0.9869 - loss: 0.0306

 33/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9867 - loss: 0.0297

 35/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9866 - loss: 0.0296

 37/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9865 - loss: 0.0294

 39/606 ━━━━━━━━━━━━━━━━━━━━ 24s 42ms/step - accuracy: 0.9872 - loss: 0.0289

 41/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9870 - loss: 0.0284

 43/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9869 - loss: 0.0280

 45/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9875 - loss: 0.0268

 47/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9880 - loss: 0.0259

 49/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9879 - loss: 0.0256

 51/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9884 - loss: 0.0250

 53/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9876 - loss: 0.0271

 55/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9881 - loss: 0.0269

 57/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9868 - loss: 0.0295

 59/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9862 - loss: 0.0305

 61/606 ━━━━━━━━━━━━━━━━━━━━ 23s 42ms/step - accuracy: 0.9851 - loss: 0.0345

 63/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9841 - loss: 0.0378

 65/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9841 - loss: 0.0378

 67/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9837 - loss: 0.0386

 69/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9832 - loss: 0.0391

 71/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9828 - loss: 0.0393

 73/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9833 - loss: 0.0390

 75/606 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.9825 - loss: 0.0405

 77/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9825 - loss: 0.0407

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9830 - loss: 0.0401

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9823 - loss: 0.0411

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9823 - loss: 0.0422

 85/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9824 - loss: 0.0427

 87/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9824 - loss: 0.0428

 89/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9824 - loss: 0.0432

 91/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9825 - loss: 0.0430

 93/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9829 - loss: 0.0425

 95/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9822 - loss: 0.0452

 97/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9823 - loss: 0.0447

 99/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9817 - loss: 0.0455

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9817 - loss: 0.0457

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9818 - loss: 0.0455

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9818 - loss: 0.0458

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9816 - loss: 0.0460

109/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9819 - loss: 0.0454

111/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9823 - loss: 0.0449

113/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9820 - loss: 0.0452

115/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9821 - loss: 0.0460

117/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9821 - loss: 0.0470

119/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9819 - loss: 0.0472

121/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9814 - loss: 0.0499

123/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9815 - loss: 0.0504

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9812 - loss: 0.0509

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9813 - loss: 0.0510

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9813 - loss: 0.0516

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9812 - loss: 0.0523

133/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9814 - loss: 0.0522

135/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9815 - loss: 0.0522

137/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9815 - loss: 0.0519

139/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9811 - loss: 0.0522

141/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9809 - loss: 0.0524

143/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9810 - loss: 0.0521

145/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9812 - loss: 0.0517

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9813 - loss: 0.0519

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9811 - loss: 0.0523

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9812 - loss: 0.0520

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9808 - loss: 0.0520

155/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9810 - loss: 0.0517

157/606 ━━━━━━━━━━━━━━━━━━━━ 19s 42ms/step - accuracy: 0.9813 - loss: 0.0512

159/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9813 - loss: 0.0510

161/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9814 - loss: 0.0514

163/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9812 - loss: 0.0522

165/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9811 - loss: 0.0524

167/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9811 - loss: 0.0531

169/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9811 - loss: 0.0531

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9806 - loss: 0.0546

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9809 - loss: 0.0543

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9805 - loss: 0.0559

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9802 - loss: 0.0565

179/606 ━━━━━━━━━━━━━━━━━━━━ 18s 42ms/step - accuracy: 0.9799 - loss: 0.0566

181/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9798 - loss: 0.0566

183/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9795 - loss: 0.0580

185/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9797 - loss: 0.0577

187/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9798 - loss: 0.0575

189/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9795 - loss: 0.0579

191/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9795 - loss: 0.0575

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9798 - loss: 0.0571

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9798 - loss: 0.0571

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9797 - loss: 0.0571

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 42ms/step - accuracy: 0.9796 - loss: 0.0572

201/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9795 - loss: 0.0572

203/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9797 - loss: 0.0569

205/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9797 - loss: 0.0566

207/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9799 - loss: 0.0561

209/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9797 - loss: 0.0561

211/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9799 - loss: 0.0558

213/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9798 - loss: 0.0558

215/606 ━━━━━━━━━━━━━━━━━━━━ 16s 42ms/step - accuracy: 0.9798 - loss: 0.0559

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9797 - loss: 0.0567

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 41ms/step - accuracy: 0.9795 - loss: 0.0569

221/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9792 - loss: 0.0582

223/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9793 - loss: 0.0580

225/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9790 - loss: 0.0581

227/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9792 - loss: 0.0579

229/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9793 - loss: 0.0579

231/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9793 - loss: 0.0579

233/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9795 - loss: 0.0577

235/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9797 - loss: 0.0573

237/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9798 - loss: 0.0571

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9795 - loss: 0.0572

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - accuracy: 0.9795 - loss: 0.0572

243/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9793 - loss: 0.0576

245/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9793 - loss: 0.0575

247/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9793 - loss: 0.0578

249/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9793 - loss: 0.0576

251/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9791 - loss: 0.0579

253/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9790 - loss: 0.0582

255/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9788 - loss: 0.0583

257/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9787 - loss: 0.0583

259/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9788 - loss: 0.0584

261/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9789 - loss: 0.0581

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 41ms/step - accuracy: 0.9791 - loss: 0.0579

265/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9792 - loss: 0.0576

267/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9794 - loss: 0.0573

269/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9794 - loss: 0.0577

271/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9796 - loss: 0.0574

273/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9797 - loss: 0.0570

275/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9799 - loss: 0.0567

277/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9799 - loss: 0.0570

279/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9797 - loss: 0.0578

281/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9799 - loss: 0.0574

283/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9798 - loss: 0.0574

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.9798 - loss: 0.0572

287/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9799 - loss: 0.0571

289/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9797 - loss: 0.0574

291/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9798 - loss: 0.0571

293/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9796 - loss: 0.0573

295/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9797 - loss: 0.0571

297/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9797 - loss: 0.0570

299/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9796 - loss: 0.0570

301/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9798 - loss: 0.0567

303/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9798 - loss: 0.0568

305/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9799 - loss: 0.0565

307/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9799 - loss: 0.0570

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9801 - loss: 0.0567

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 41ms/step - accuracy: 0.9802 - loss: 0.0566

313/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9803 - loss: 0.0564

315/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9804 - loss: 0.0564

317/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9802 - loss: 0.0566

319/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9803 - loss: 0.0563

321/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9804 - loss: 0.0561

323/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9806 - loss: 0.0558

325/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9806 - loss: 0.0557

327/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9806 - loss: 0.0559

329/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9807 - loss: 0.0557

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9808 - loss: 0.0555

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9809 - loss: 0.0553

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 41ms/step - accuracy: 0.9809 - loss: 0.0552

337/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9809 - loss: 0.0551

339/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9810 - loss: 0.0548

341/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9811 - loss: 0.0548

343/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9812 - loss: 0.0545

345/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9812 - loss: 0.0546

347/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9811 - loss: 0.0548

349/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9810 - loss: 0.0548

351/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9809 - loss: 0.0549

353/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9809 - loss: 0.0548

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9809 - loss: 0.0550

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9809 - loss: 0.0549

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9810 - loss: 0.0546

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - accuracy: 0.9811 - loss: 0.0543

363/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9812 - loss: 0.0541

365/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9812 - loss: 0.0540

367/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9813 - loss: 0.0541

369/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9813 - loss: 0.0540

371/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9813 - loss: 0.0539

373/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9814 - loss: 0.0537

375/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9815 - loss: 0.0535

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9816 - loss: 0.0533

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9817 - loss: 0.0532

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9817 - loss: 0.0531

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9817 - loss: 0.0531

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - accuracy: 0.9818 - loss: 0.0529

387/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9818 - loss: 0.0528

389/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9819 - loss: 0.0527

391/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9819 - loss: 0.0526

393/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9819 - loss: 0.0523

395/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9820 - loss: 0.0522

397/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9820 - loss: 0.0521

399/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9820 - loss: 0.0520

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9821 - loss: 0.0518

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9822 - loss: 0.0516

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9823 - loss: 0.0514

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9823 - loss: 0.0513

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - accuracy: 0.9824 - loss: 0.0512

411/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9824 - loss: 0.0510

413/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9824 - loss: 0.0510

415/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9825 - loss: 0.0508

417/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9825 - loss: 0.0505

419/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9826 - loss: 0.0504

421/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9826 - loss: 0.0504

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9826 - loss: 0.0502

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9824 - loss: 0.0504

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9824 - loss: 0.0505

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9825 - loss: 0.0503

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9825 - loss: 0.0502

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 0.9824 - loss: 0.0504

435/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9825 - loss: 0.0502

437/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9826 - loss: 0.0500

439/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9826 - loss: 0.0499

441/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9826 - loss: 0.0500

443/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9824 - loss: 0.0505

445/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9824 - loss: 0.0503

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9825 - loss: 0.0503

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9824 - loss: 0.0504

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9823 - loss: 0.0507

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9822 - loss: 0.0511

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9823 - loss: 0.0509

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9824 - loss: 0.0508

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9824 - loss: 0.0507

461/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9823 - loss: 0.0509

463/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9822 - loss: 0.0510

465/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9822 - loss: 0.0511

467/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9823 - loss: 0.0510

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9823 - loss: 0.0511

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9823 - loss: 0.0512

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9824 - loss: 0.0510

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9822 - loss: 0.0512

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9823 - loss: 0.0511

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9823 - loss: 0.0511

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9823 - loss: 0.0510

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.9823 - loss: 0.0508

485/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9823 - loss: 0.0509

487/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9824 - loss: 0.0507

489/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9825 - loss: 0.0506

491/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9825 - loss: 0.0505

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9825 - loss: 0.0505

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9826 - loss: 0.0505

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9826 - loss: 0.0504

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9826 - loss: 0.0504

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9825 - loss: 0.0503

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9826 - loss: 0.0502

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9826 - loss: 0.0504

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - accuracy: 0.9827 - loss: 0.0502

509/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9827 - loss: 0.0500

511/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9827 - loss: 0.0501

513/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9827 - loss: 0.0501

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9827 - loss: 0.0500

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9828 - loss: 0.0499

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9827 - loss: 0.0499

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9827 - loss: 0.0499

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9827 - loss: 0.0498

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9827 - loss: 0.0498

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9827 - loss: 0.0498

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9827 - loss: 0.0497

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9826 - loss: 0.0498

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9826 - loss: 0.0497

535/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9827 - loss: 0.0496

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9827 - loss: 0.0495

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9827 - loss: 0.0495

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9827 - loss: 0.0496

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9827 - loss: 0.0494

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9827 - loss: 0.0493

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9827 - loss: 0.0492

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9828 - loss: 0.0491

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9828 - loss: 0.0492

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9827 - loss: 0.0493

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9827 - loss: 0.0492

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.9828 - loss: 0.0491

559/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9828 - loss: 0.0490

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9828 - loss: 0.0490

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9829 - loss: 0.0489

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9827 - loss: 0.0492

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9827 - loss: 0.0491

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9828 - loss: 0.0491

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9828 - loss: 0.0490

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9828 - loss: 0.0490

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9829 - loss: 0.0489

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9829 - loss: 0.0487

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9830 - loss: 0.0486

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.9830 - loss: 0.0486

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9831 - loss: 0.0485

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9830 - loss: 0.0484

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9830 - loss: 0.0484

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9831 - loss: 0.0483

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9830 - loss: 0.0483

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9830 - loss: 0.0482

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9831 - loss: 0.0481

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9831 - loss: 0.0480

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9832 - loss: 0.0479

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9833 - loss: 0.0478

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9832 - loss: 0.0479

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9833 - loss: 0.0478

606/606 ━━━━━━━━━━━━━━━━━━━━ 29s 47ms/step - accuracy: 0.9833 - loss: 0.0478 - val_accuracy: 0.9598 - val_loss: 0.1752

Epoch 28/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 37s 63ms/step - accuracy: 1.0000 - loss: 0.0033

  3/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 1.0000 - loss: 0.0150

  5/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 1.0000 - loss: 0.0197

  7/606 ━━━━━━━━━━━━━━━━━━━━ 27s 46ms/step - accuracy: 1.0000 - loss: 0.0171

  9/606 ━━━━━━━━━━━━━━━━━━━━ 27s 46ms/step - accuracy: 0.9965 - loss: 0.0187

 11/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9972 - loss: 0.0191

 13/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9952 - loss: 0.0223

 15/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9937 - loss: 0.0221

 17/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9926 - loss: 0.0233

 19/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9901 - loss: 0.0276

 21/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9896 - loss: 0.0274

 23/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9891 - loss: 0.0302

 25/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9887 - loss: 0.0295

 27/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9884 - loss: 0.0299

 29/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9881 - loss: 0.0330

 31/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9889 - loss: 0.0315

 33/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9896 - loss: 0.0301

 35/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9902 - loss: 0.0287

 37/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9907 - loss: 0.0276

 39/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9904 - loss: 0.0276

 41/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9909 - loss: 0.0268

 43/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9898 - loss: 0.0273

 45/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9882 - loss: 0.0303

 47/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9887 - loss: 0.0292

 49/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9892 - loss: 0.0284

 51/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9884 - loss: 0.0292

 53/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9888 - loss: 0.0283

 55/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9869 - loss: 0.0356

 57/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9874 - loss: 0.0345

 59/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9878 - loss: 0.0339

 61/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9862 - loss: 0.0389

 63/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9861 - loss: 0.0391

 65/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9856 - loss: 0.0399

 67/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9851 - loss: 0.0407

 69/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9855 - loss: 0.0400

 71/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9855 - loss: 0.0399

 73/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9850 - loss: 0.0408

 75/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9854 - loss: 0.0400

 77/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9858 - loss: 0.0401

 79/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9858 - loss: 0.0400

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9857 - loss: 0.0415

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9857 - loss: 0.0425

 85/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9857 - loss: 0.0425

 87/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9853 - loss: 0.0424

 89/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9849 - loss: 0.0427

 91/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9849 - loss: 0.0426

 93/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9852 - loss: 0.0423

 95/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9849 - loss: 0.0440

 97/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9852 - loss: 0.0436

 99/606 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - accuracy: 0.9852 - loss: 0.0435

101/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9845 - loss: 0.0451

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9848 - loss: 0.0444

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9845 - loss: 0.0446

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9845 - loss: 0.0442

109/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9845 - loss: 0.0438

111/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9845 - loss: 0.0446

113/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9840 - loss: 0.0456

115/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9834 - loss: 0.0468

117/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9832 - loss: 0.0468

119/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9832 - loss: 0.0466

121/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9832 - loss: 0.0475

123/606 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.9827 - loss: 0.0476

125/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9825 - loss: 0.0487

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 43ms/step - accuracy: 0.9820 - loss: 0.0493

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9818 - loss: 0.0495

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9816 - loss: 0.0500

133/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9814 - loss: 0.0505

135/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9812 - loss: 0.0528

137/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9815 - loss: 0.0523

139/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9813 - loss: 0.0527

141/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9814 - loss: 0.0527

143/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9810 - loss: 0.0540

145/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9812 - loss: 0.0535

147/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9815 - loss: 0.0530

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9813 - loss: 0.0533

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9810 - loss: 0.0542

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9808 - loss: 0.0546

155/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9808 - loss: 0.0545

157/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9811 - loss: 0.0541

159/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9811 - loss: 0.0538

161/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9806 - loss: 0.0545

163/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9806 - loss: 0.0542

165/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9805 - loss: 0.0551

167/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9807 - loss: 0.0545

169/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9806 - loss: 0.0552

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9808 - loss: 0.0548

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9807 - loss: 0.0556

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9804 - loss: 0.0561

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9806 - loss: 0.0559

179/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9806 - loss: 0.0562

181/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9805 - loss: 0.0565

183/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9805 - loss: 0.0582

185/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9806 - loss: 0.0581

187/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9806 - loss: 0.0582

189/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9808 - loss: 0.0579

191/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9810 - loss: 0.0575

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9812 - loss: 0.0571

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9812 - loss: 0.0569

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9814 - loss: 0.0566

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9816 - loss: 0.0563

201/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9818 - loss: 0.0561

203/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9818 - loss: 0.0559

205/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9819 - loss: 0.0556

207/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9817 - loss: 0.0554

209/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9819 - loss: 0.0550

211/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9821 - loss: 0.0546

213/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9821 - loss: 0.0547

215/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9818 - loss: 0.0547

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9817 - loss: 0.0548

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9819 - loss: 0.0545

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9815 - loss: 0.0555

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9815 - loss: 0.0555

225/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9815 - loss: 0.0555

227/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9810 - loss: 0.0565

229/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9809 - loss: 0.0566

231/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9808 - loss: 0.0567

233/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9810 - loss: 0.0563

235/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9810 - loss: 0.0560

237/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9810 - loss: 0.0558

239/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9809 - loss: 0.0557

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9804 - loss: 0.0566

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9805 - loss: 0.0564

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9806 - loss: 0.0562

246/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9806 - loss: 0.0563

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9804 - loss: 0.0564

248/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9805 - loss: 0.0565

250/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9805 - loss: 0.0565

251/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9805 - loss: 0.0564

253/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9802 - loss: 0.0565

255/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9803 - loss: 0.0564

257/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9803 - loss: 0.0562

259/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9805 - loss: 0.0559

261/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9805 - loss: 0.0558

263/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9805 - loss: 0.0557

265/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9805 - loss: 0.0561

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9806 - loss: 0.0559

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9806 - loss: 0.0558

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9806 - loss: 0.0557

273/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9808 - loss: 0.0556

275/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9809 - loss: 0.0552

277/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9807 - loss: 0.0570

279/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9807 - loss: 0.0568

281/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9809 - loss: 0.0566

283/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9808 - loss: 0.0566

285/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9808 - loss: 0.0565

287/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9808 - loss: 0.0565

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9809 - loss: 0.0564

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9809 - loss: 0.0564

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9807 - loss: 0.0566

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9808 - loss: 0.0565

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9810 - loss: 0.0562

299/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9807 - loss: 0.0564

301/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9808 - loss: 0.0562

303/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9808 - loss: 0.0560

305/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9809 - loss: 0.0557

307/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9811 - loss: 0.0555

309/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9811 - loss: 0.0554

311/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9811 - loss: 0.0553

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9812 - loss: 0.0551

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9813 - loss: 0.0548

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9812 - loss: 0.0550

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9813 - loss: 0.0548

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9812 - loss: 0.0548

323/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9812 - loss: 0.0546

325/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9812 - loss: 0.0549

327/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9813 - loss: 0.0546

329/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9813 - loss: 0.0544

331/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9813 - loss: 0.0542

333/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9814 - loss: 0.0540

335/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9815 - loss: 0.0537

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9814 - loss: 0.0537

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9815 - loss: 0.0535

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9815 - loss: 0.0535

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9814 - loss: 0.0534

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9815 - loss: 0.0533

347/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9816 - loss: 0.0530

349/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9816 - loss: 0.0530

351/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9817 - loss: 0.0528

353/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9817 - loss: 0.0528

355/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9818 - loss: 0.0525

357/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9818 - loss: 0.0528

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9819 - loss: 0.0525

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9820 - loss: 0.0523

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9821 - loss: 0.0521

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9819 - loss: 0.0522

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9819 - loss: 0.0523

369/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9820 - loss: 0.0520

371/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9820 - loss: 0.0519

373/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9821 - loss: 0.0517

375/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9822 - loss: 0.0515

377/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9823 - loss: 0.0514

379/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9823 - loss: 0.0514

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9823 - loss: 0.0513

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9824 - loss: 0.0511

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9824 - loss: 0.0511

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9825 - loss: 0.0509

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9825 - loss: 0.0507

391/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9825 - loss: 0.0506

393/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9826 - loss: 0.0505

395/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9827 - loss: 0.0502

397/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9828 - loss: 0.0500

399/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9828 - loss: 0.0498

401/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9829 - loss: 0.0496

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9829 - loss: 0.0496

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9830 - loss: 0.0494

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9830 - loss: 0.0493

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9831 - loss: 0.0490

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9831 - loss: 0.0489

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9832 - loss: 0.0487

415/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9831 - loss: 0.0489

417/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9831 - loss: 0.0488

419/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9832 - loss: 0.0486

421/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9832 - loss: 0.0487

423/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9832 - loss: 0.0486

425/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9832 - loss: 0.0484

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9833 - loss: 0.0482

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9834 - loss: 0.0481

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9834 - loss: 0.0481

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9835 - loss: 0.0480

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9835 - loss: 0.0480

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9835 - loss: 0.0479

439/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9836 - loss: 0.0478

441/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9836 - loss: 0.0476

443/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9836 - loss: 0.0475

445/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9835 - loss: 0.0477

447/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9834 - loss: 0.0479

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9834 - loss: 0.0478

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9834 - loss: 0.0479

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9834 - loss: 0.0477

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9834 - loss: 0.0478

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9832 - loss: 0.0479

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9833 - loss: 0.0478

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9833 - loss: 0.0478

463/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9834 - loss: 0.0477

465/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9835 - loss: 0.0476

467/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9835 - loss: 0.0475

469/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9835 - loss: 0.0476

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9833 - loss: 0.0479

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9834 - loss: 0.0478

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9834 - loss: 0.0478

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9834 - loss: 0.0477

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9835 - loss: 0.0476

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9835 - loss: 0.0475

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9836 - loss: 0.0473

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9836 - loss: 0.0473

487/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9835 - loss: 0.0473

489/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9836 - loss: 0.0472

491/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9836 - loss: 0.0470

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9837 - loss: 0.0469

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9837 - loss: 0.0468

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9837 - loss: 0.0467

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9837 - loss: 0.0467

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9837 - loss: 0.0466

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9837 - loss: 0.0466

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9837 - loss: 0.0465

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9837 - loss: 0.0464

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9837 - loss: 0.0464

511/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9837 - loss: 0.0464

513/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9838 - loss: 0.0462

515/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9838 - loss: 0.0462

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9837 - loss: 0.0463

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9837 - loss: 0.0462

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9838 - loss: 0.0460

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9839 - loss: 0.0459

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9839 - loss: 0.0458

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9840 - loss: 0.0457

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9840 - loss: 0.0456

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9839 - loss: 0.0457

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9839 - loss: 0.0455

535/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9840 - loss: 0.0454

537/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9841 - loss: 0.0453

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9841 - loss: 0.0452

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9842 - loss: 0.0450

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9842 - loss: 0.0449

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9843 - loss: 0.0448

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9842 - loss: 0.0449

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9842 - loss: 0.0450

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9842 - loss: 0.0449

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9843 - loss: 0.0448

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9842 - loss: 0.0448

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9842 - loss: 0.0448

559/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9843 - loss: 0.0447

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9843 - loss: 0.0446

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9843 - loss: 0.0446

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9843 - loss: 0.0446

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9842 - loss: 0.0447

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9842 - loss: 0.0446

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9842 - loss: 0.0445

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9843 - loss: 0.0444

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9843 - loss: 0.0443

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9844 - loss: 0.0441

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9845 - loss: 0.0441

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9845 - loss: 0.0440

583/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9845 - loss: 0.0438

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9846 - loss: 0.0437

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9845 - loss: 0.0439

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9846 - loss: 0.0438

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9846 - loss: 0.0437

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9846 - loss: 0.0437

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9846 - loss: 0.0438

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9846 - loss: 0.0437

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9846 - loss: 0.0436

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9847 - loss: 0.0436

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9846 - loss: 0.0437

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9846 - loss: 0.0437

606/606 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.9846 - loss: 0.0436 - val_accuracy: 0.9513 - val_loss: 0.2348

Epoch 29/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 1.0000 - loss: 0.0189

  2/606 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 1.0000 - loss: 0.0117

  3/606 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.9896 - loss: 0.0176

  5/606 ━━━━━━━━━━━━━━━━━━━━ 28s 48ms/step - accuracy: 0.9937 - loss: 0.0166

  7/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.9955 - loss: 0.0131

  9/606 ━━━━━━━━━━━━━━━━━━━━ 27s 46ms/step - accuracy: 0.9965 - loss: 0.0122

 11/606 ━━━━━━━━━━━━━━━━━━━━ 27s 46ms/step - accuracy: 0.9943 - loss: 0.0136

 13/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9928 - loss: 0.0152

 15/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9937 - loss: 0.0151

 17/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9945 - loss: 0.0154

 19/606 ━━━━━━━━━━━━━━━━━━━━ 26s 44ms/step - accuracy: 0.9934 - loss: 0.0159

 21/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9940 - loss: 0.0146

 23/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9946 - loss: 0.0140

 25/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9950 - loss: 0.0140

 27/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9942 - loss: 0.0179

 29/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9946 - loss: 0.0178

 31/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9950 - loss: 0.0173

 33/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9943 - loss: 0.0202

 35/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9946 - loss: 0.0192

 37/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9949 - loss: 0.0199

 39/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9936 - loss: 0.0224

 41/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9939 - loss: 0.0213

 43/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9927 - loss: 0.0238

 45/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9917 - loss: 0.0257

 47/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9914 - loss: 0.0259

 49/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9892 - loss: 0.0291

 51/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9890 - loss: 0.0291

 53/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9894 - loss: 0.0283

 55/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9892 - loss: 0.0286

 57/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9896 - loss: 0.0282

 59/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9889 - loss: 0.0308

 61/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9892 - loss: 0.0299

 63/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9891 - loss: 0.0313

 65/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9894 - loss: 0.0307

 67/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9897 - loss: 0.0299

 69/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9896 - loss: 0.0318

 71/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9894 - loss: 0.0336

 73/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9897 - loss: 0.0334

 75/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9892 - loss: 0.0338

 77/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9890 - loss: 0.0337

 79/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9889 - loss: 0.0340

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9892 - loss: 0.0336

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9887 - loss: 0.0339

 85/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9886 - loss: 0.0338

 87/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9881 - loss: 0.0342

 89/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9881 - loss: 0.0340

 91/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9883 - loss: 0.0334

 93/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9886 - loss: 0.0329

 95/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9885 - loss: 0.0334

 97/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9878 - loss: 0.0343

 99/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9880 - loss: 0.0340

101/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9882 - loss: 0.0335

103/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9879 - loss: 0.0344

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9878 - loss: 0.0360

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9874 - loss: 0.0360

109/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9877 - loss: 0.0355

111/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9873 - loss: 0.0356

113/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9873 - loss: 0.0363

115/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9875 - loss: 0.0359

117/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9874 - loss: 0.0358

119/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9871 - loss: 0.0383

121/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9873 - loss: 0.0378

123/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9868 - loss: 0.0385

125/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9870 - loss: 0.0381

127/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9870 - loss: 0.0378

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9862 - loss: 0.0397

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9859 - loss: 0.0407

133/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9859 - loss: 0.0409

135/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9859 - loss: 0.0410

137/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9854 - loss: 0.0414

139/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9852 - loss: 0.0415

141/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9854 - loss: 0.0411

143/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9856 - loss: 0.0408

145/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9851 - loss: 0.0412

147/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9853 - loss: 0.0407

149/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9853 - loss: 0.0406

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9855 - loss: 0.0401

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9857 - loss: 0.0398

155/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9857 - loss: 0.0396

157/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9857 - loss: 0.0401

159/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9858 - loss: 0.0399

161/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9860 - loss: 0.0397

163/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9858 - loss: 0.0397

165/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9856 - loss: 0.0400

167/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9854 - loss: 0.0408

169/606 ━━━━━━━━━━━━━━━━━━━━ 19s 43ms/step - accuracy: 0.9854 - loss: 0.0407

171/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9854 - loss: 0.0406

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9852 - loss: 0.0409

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9854 - loss: 0.0406

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9855 - loss: 0.0404

179/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9853 - loss: 0.0406

181/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9855 - loss: 0.0405

183/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9855 - loss: 0.0410

185/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9856 - loss: 0.0407

187/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9858 - loss: 0.0405

189/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9858 - loss: 0.0405

191/606 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.9858 - loss: 0.0405

193/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9856 - loss: 0.0404

195/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9853 - loss: 0.0409

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9854 - loss: 0.0407

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9854 - loss: 0.0407

201/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9855 - loss: 0.0405

203/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9855 - loss: 0.0404

205/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9857 - loss: 0.0402

207/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9858 - loss: 0.0400

209/606 ━━━━━━━━━━━━━━━━━━━━ 17s 43ms/step - accuracy: 0.9859 - loss: 0.0397

211/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9859 - loss: 0.0402

213/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9859 - loss: 0.0403

215/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9858 - loss: 0.0414

217/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9859 - loss: 0.0412

219/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9859 - loss: 0.0413

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9859 - loss: 0.0413

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9858 - loss: 0.0413

225/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9857 - loss: 0.0412

227/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9855 - loss: 0.0412

229/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9854 - loss: 0.0414

231/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9851 - loss: 0.0416

233/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9851 - loss: 0.0416

235/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9852 - loss: 0.0414

237/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9851 - loss: 0.0414

239/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9850 - loss: 0.0424

241/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9850 - loss: 0.0424

243/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9848 - loss: 0.0426

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9847 - loss: 0.0429

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9847 - loss: 0.0429

249/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9846 - loss: 0.0430

251/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9844 - loss: 0.0431

253/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9846 - loss: 0.0430

255/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9847 - loss: 0.0427

257/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9847 - loss: 0.0429

259/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9847 - loss: 0.0430

261/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9848 - loss: 0.0428

263/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9849 - loss: 0.0427

265/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9849 - loss: 0.0430

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9847 - loss: 0.0439

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9847 - loss: 0.0439

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9848 - loss: 0.0437

273/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9845 - loss: 0.0439

275/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9844 - loss: 0.0441

277/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9844 - loss: 0.0443

279/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9845 - loss: 0.0441

281/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9845 - loss: 0.0446

283/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9845 - loss: 0.0449

285/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9843 - loss: 0.0457

287/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9844 - loss: 0.0456

289/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9844 - loss: 0.0456

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9844 - loss: 0.0458

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9843 - loss: 0.0458

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9843 - loss: 0.0457

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9844 - loss: 0.0455

299/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9845 - loss: 0.0453

301/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9845 - loss: 0.0454

303/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9846 - loss: 0.0452

305/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9847 - loss: 0.0450

307/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9846 - loss: 0.0450

309/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9844 - loss: 0.0455

311/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9843 - loss: 0.0454

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9844 - loss: 0.0452

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9844 - loss: 0.0453

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9845 - loss: 0.0451

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9846 - loss: 0.0450

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9847 - loss: 0.0449

323/606 ━━━━━━━━━━━━━━━━━━━━ 12s 43ms/step - accuracy: 0.9848 - loss: 0.0448

325/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9848 - loss: 0.0448

327/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9849 - loss: 0.0446

329/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9849 - loss: 0.0448

331/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9850 - loss: 0.0445

333/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9850 - loss: 0.0446

335/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9851 - loss: 0.0444

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9849 - loss: 0.0447

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9850 - loss: 0.0445

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9851 - loss: 0.0444

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9851 - loss: 0.0443

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9852 - loss: 0.0441

347/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9853 - loss: 0.0441

349/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9854 - loss: 0.0439

351/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9855 - loss: 0.0438

353/606 ━━━━━━━━━━━━━━━━━━━━ 11s 43ms/step - accuracy: 0.9856 - loss: 0.0436

355/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9856 - loss: 0.0435

357/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9856 - loss: 0.0433

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9856 - loss: 0.0433

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9857 - loss: 0.0432

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9858 - loss: 0.0430

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9859 - loss: 0.0429

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9859 - loss: 0.0429

369/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9859 - loss: 0.0427

371/606 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9859 - loss: 0.0426

373/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9860 - loss: 0.0425

375/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9860 - loss: 0.0425

377/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9859 - loss: 0.0426

379/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9860 - loss: 0.0425

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9861 - loss: 0.0423

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.9860 - loss: 0.0423

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9860 - loss: 0.0424

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9859 - loss: 0.0424

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9859 - loss: 0.0423

391/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9860 - loss: 0.0422

393/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9860 - loss: 0.0422

395/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9861 - loss: 0.0421

397/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9861 - loss: 0.0420

399/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9860 - loss: 0.0421

401/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9861 - loss: 0.0420

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9860 - loss: 0.0420

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9860 - loss: 0.0422

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9860 - loss: 0.0420

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9860 - loss: 0.0420

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9859 - loss: 0.0420

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9859 - loss: 0.0421

415/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9858 - loss: 0.0421

417/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9859 - loss: 0.0419

419/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9858 - loss: 0.0421

421/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9858 - loss: 0.0419

423/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9858 - loss: 0.0419

425/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9857 - loss: 0.0419

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9856 - loss: 0.0421

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9856 - loss: 0.0421

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9856 - loss: 0.0421

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9856 - loss: 0.0420

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9856 - loss: 0.0420

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9856 - loss: 0.0420

439/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9857 - loss: 0.0418

441/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9858 - loss: 0.0418

443/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9856 - loss: 0.0421

445/606 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9855 - loss: 0.0422

447/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9855 - loss: 0.0422

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9854 - loss: 0.0424

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9854 - loss: 0.0422

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9855 - loss: 0.0421

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9854 - loss: 0.0420

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9854 - loss: 0.0420

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9855 - loss: 0.0420

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9856 - loss: 0.0418

463/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9856 - loss: 0.0418

465/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9856 - loss: 0.0417

467/606 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9857 - loss: 0.0417

469/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9857 - loss: 0.0415

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9857 - loss: 0.0415

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9858 - loss: 0.0414

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9857 - loss: 0.0415

477/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9857 - loss: 0.0414

479/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9858 - loss: 0.0414

481/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9858 - loss: 0.0413

483/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9859 - loss: 0.0412

485/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9860 - loss: 0.0410

487/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9860 - loss: 0.0409

489/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9861 - loss: 0.0407

491/606 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.9861 - loss: 0.0407

493/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9861 - loss: 0.0406

495/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9861 - loss: 0.0406

497/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9861 - loss: 0.0406

499/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9861 - loss: 0.0405

501/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9860 - loss: 0.0405

503/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9861 - loss: 0.0404

505/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9861 - loss: 0.0403

507/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9861 - loss: 0.0402

509/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9861 - loss: 0.0402

511/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9862 - loss: 0.0401

513/606 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9862 - loss: 0.0402

515/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9862 - loss: 0.0403

517/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9862 - loss: 0.0402

519/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9863 - loss: 0.0400

521/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9863 - loss: 0.0399

523/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9864 - loss: 0.0399

525/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9863 - loss: 0.0399

527/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9862 - loss: 0.0400

529/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9862 - loss: 0.0400

531/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9862 - loss: 0.0399

533/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9862 - loss: 0.0398

535/606 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.9861 - loss: 0.0399

537/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9861 - loss: 0.0399

539/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9861 - loss: 0.0398

541/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9862 - loss: 0.0397

543/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9862 - loss: 0.0396

545/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9862 - loss: 0.0395

547/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9862 - loss: 0.0395

549/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9863 - loss: 0.0394

551/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9863 - loss: 0.0394

553/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9863 - loss: 0.0395

555/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9864 - loss: 0.0394

557/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9864 - loss: 0.0394

559/606 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.9865 - loss: 0.0393

561/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9865 - loss: 0.0392

563/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9865 - loss: 0.0392

565/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9864 - loss: 0.0393

567/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9864 - loss: 0.0394

569/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9865 - loss: 0.0393

571/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9865 - loss: 0.0393

573/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9865 - loss: 0.0392

575/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9866 - loss: 0.0391

577/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9866 - loss: 0.0390

579/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9866 - loss: 0.0389

581/606 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.9867 - loss: 0.0389

583/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9867 - loss: 0.0389

585/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9867 - loss: 0.0388

587/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9867 - loss: 0.0388

589/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9868 - loss: 0.0387

591/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9868 - loss: 0.0387

593/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9867 - loss: 0.0388

595/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9868 - loss: 0.0387

597/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9868 - loss: 0.0386

599/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9869 - loss: 0.0386

601/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9869 - loss: 0.0385

603/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9869 - loss: 0.0384

605/606 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9869 - loss: 0.0383

606/606 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.9869 - loss: 0.0383 - val_accuracy: 0.9554 - val_loss: 0.2318

Epoch 30/30

  1/606 ━━━━━━━━━━━━━━━━━━━━ 42s 71ms/step - accuracy: 1.0000 - loss: 0.0033

  3/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 1.0000 - loss: 0.0119

  5/606 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.9937 - loss: 0.0152

  7/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.9955 - loss: 0.0124

  9/606 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.9965 - loss: 0.0105

 11/606 ━━━━━━━━━━━━━━━━━━━━ 27s 46ms/step - accuracy: 0.9972 - loss: 0.0104

 13/606 ━━━━━━━━━━━━━━━━━━━━ 27s 46ms/step - accuracy: 0.9976 - loss: 0.0111

 15/606 ━━━━━━━━━━━━━━━━━━━━ 26s 46ms/step - accuracy: 0.9958 - loss: 0.0159

 17/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9945 - loss: 0.0191

 19/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9934 - loss: 0.0202

 21/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9926 - loss: 0.0245

 23/606 ━━━━━━━━━━━━━━━━━━━━ 26s 45ms/step - accuracy: 0.9932 - loss: 0.0230

 25/606 ━━━━━━━━━━━━━━━━━━━━ 25s 45ms/step - accuracy: 0.9925 - loss: 0.0266

 27/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9931 - loss: 0.0248

 29/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9935 - loss: 0.0234

 31/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9940 - loss: 0.0228

 33/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9943 - loss: 0.0218

 35/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9946 - loss: 0.0206

 37/606 ━━━━━━━━━━━━━━━━━━━━ 25s 44ms/step - accuracy: 0.9949 - loss: 0.0198

 39/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9952 - loss: 0.0190

 41/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9947 - loss: 0.0195

 43/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9949 - loss: 0.0190

 45/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9951 - loss: 0.0190

 47/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9953 - loss: 0.0183

 49/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9955 - loss: 0.0177

 51/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9957 - loss: 0.0171

 53/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9959 - loss: 0.0165

 55/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9955 - loss: 0.0170

 57/606 ━━━━━━━━━━━━━━━━━━━━ 24s 44ms/step - accuracy: 0.9956 - loss: 0.0167

 59/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9958 - loss: 0.0166

 61/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9959 - loss: 0.0165

 63/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9955 - loss: 0.0182

 65/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9952 - loss: 0.0199

 67/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9953 - loss: 0.0197

 69/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9955 - loss: 0.0194

 71/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9947 - loss: 0.0200

 73/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9940 - loss: 0.0215

 75/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9942 - loss: 0.0214

 77/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9943 - loss: 0.0211

 79/606 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - accuracy: 0.9937 - loss: 0.0215

 81/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9938 - loss: 0.0211

 83/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9940 - loss: 0.0209

 85/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9934 - loss: 0.0218

 87/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9935 - loss: 0.0214

 89/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9933 - loss: 0.0222

 91/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9928 - loss: 0.0233

 93/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9929 - loss: 0.0231

 95/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9931 - loss: 0.0228

 97/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9919 - loss: 0.0260

 99/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9921 - loss: 0.0257

101/606 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - accuracy: 0.9920 - loss: 0.0257

103/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9921 - loss: 0.0255

105/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9917 - loss: 0.0265

107/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9918 - loss: 0.0267

109/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9920 - loss: 0.0266

111/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9918 - loss: 0.0265

113/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9917 - loss: 0.0270

115/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9916 - loss: 0.0273

117/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9912 - loss: 0.0282

118/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9913 - loss: 0.0280

119/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9913 - loss: 0.0280

121/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9910 - loss: 0.0288

123/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9909 - loss: 0.0289

125/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9905 - loss: 0.0296

127/606 ━━━━━━━━━━━━━━━━━━━━ 21s 44ms/step - accuracy: 0.9904 - loss: 0.0316

129/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9906 - loss: 0.0313

131/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9907 - loss: 0.0310

133/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9904 - loss: 0.0318

135/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9898 - loss: 0.0321

137/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9891 - loss: 0.0339

139/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9888 - loss: 0.0342

141/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9885 - loss: 0.0345

143/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9882 - loss: 0.0348

145/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9884 - loss: 0.0346

147/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9883 - loss: 0.0344

149/606 ━━━━━━━━━━━━━━━━━━━━ 20s 44ms/step - accuracy: 0.9885 - loss: 0.0341

151/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9886 - loss: 0.0338

153/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9886 - loss: 0.0337

155/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9883 - loss: 0.0340

157/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9885 - loss: 0.0341

159/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9884 - loss: 0.0340

161/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9884 - loss: 0.0340

163/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9883 - loss: 0.0345

165/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9884 - loss: 0.0346

167/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9882 - loss: 0.0352

169/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9882 - loss: 0.0352

171/606 ━━━━━━━━━━━━━━━━━━━━ 19s 44ms/step - accuracy: 0.9881 - loss: 0.0353

173/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9877 - loss: 0.0361

175/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9875 - loss: 0.0364

177/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9875 - loss: 0.0363

179/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9873 - loss: 0.0371

181/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9872 - loss: 0.0373

183/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9874 - loss: 0.0371

185/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9873 - loss: 0.0370

187/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9871 - loss: 0.0379

189/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9869 - loss: 0.0396

191/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9871 - loss: 0.0393

193/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9872 - loss: 0.0390

194/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9871 - loss: 0.0390

195/606 ━━━━━━━━━━━━━━━━━━━━ 18s 44ms/step - accuracy: 0.9870 - loss: 0.0390

197/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9868 - loss: 0.0392

199/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9867 - loss: 0.0395

201/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9865 - loss: 0.0397

203/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9866 - loss: 0.0395

205/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9866 - loss: 0.0394

207/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9867 - loss: 0.0391

209/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9867 - loss: 0.0395

211/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9865 - loss: 0.0399

213/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9864 - loss: 0.0408

215/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9865 - loss: 0.0405

217/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9865 - loss: 0.0404

219/606 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.9859 - loss: 0.0421

221/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9856 - loss: 0.0430

223/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9857 - loss: 0.0429

225/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9857 - loss: 0.0431

227/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9857 - loss: 0.0432

229/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9858 - loss: 0.0432

231/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9859 - loss: 0.0431

233/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9861 - loss: 0.0430

235/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9862 - loss: 0.0428

237/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9862 - loss: 0.0428

239/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9859 - loss: 0.0431

241/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9860 - loss: 0.0429

243/606 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9861 - loss: 0.0426

245/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9862 - loss: 0.0424

247/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9862 - loss: 0.0423

249/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9863 - loss: 0.0421

251/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9863 - loss: 0.0422

253/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9864 - loss: 0.0420

255/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9863 - loss: 0.0422

257/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9863 - loss: 0.0422

259/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9861 - loss: 0.0423

261/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9861 - loss: 0.0422

263/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9860 - loss: 0.0422

265/606 ━━━━━━━━━━━━━━━━━━━━ 15s 44ms/step - accuracy: 0.9861 - loss: 0.0420

267/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9862 - loss: 0.0418

269/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9863 - loss: 0.0415

271/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9862 - loss: 0.0417

273/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9861 - loss: 0.0417

275/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9862 - loss: 0.0415

277/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9861 - loss: 0.0419

279/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9861 - loss: 0.0421

281/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9862 - loss: 0.0419

283/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9862 - loss: 0.0418

285/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9862 - loss: 0.0418

287/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9862 - loss: 0.0418

289/606 ━━━━━━━━━━━━━━━━━━━━ 14s 44ms/step - accuracy: 0.9861 - loss: 0.0422

291/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9861 - loss: 0.0420

293/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9860 - loss: 0.0421

295/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9859 - loss: 0.0429

297/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9860 - loss: 0.0428

299/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9861 - loss: 0.0427

301/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9860 - loss: 0.0430

303/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9861 - loss: 0.0430

305/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9862 - loss: 0.0429

307/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9863 - loss: 0.0427

309/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9863 - loss: 0.0425

311/606 ━━━━━━━━━━━━━━━━━━━━ 13s 44ms/step - accuracy: 0.9864 - loss: 0.0424

313/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9865 - loss: 0.0422

315/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9865 - loss: 0.0421

317/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9866 - loss: 0.0420

319/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9867 - loss: 0.0419

321/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9866 - loss: 0.0420

323/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9866 - loss: 0.0418

325/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9867 - loss: 0.0417

327/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9865 - loss: 0.0423

329/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9866 - loss: 0.0421

331/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9866 - loss: 0.0420

333/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9866 - loss: 0.0420

335/606 ━━━━━━━━━━━━━━━━━━━━ 12s 44ms/step - accuracy: 0.9866 - loss: 0.0419

337/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9866 - loss: 0.0423

339/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9864 - loss: 0.0423

341/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9864 - loss: 0.0421

343/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9864 - loss: 0.0421

345/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9864 - loss: 0.0421

347/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9865 - loss: 0.0419

349/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9865 - loss: 0.0418

351/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9866 - loss: 0.0417

353/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9866 - loss: 0.0415

355/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9866 - loss: 0.0414

357/606 ━━━━━━━━━━━━━━━━━━━━ 11s 44ms/step - accuracy: 0.9866 - loss: 0.0416

359/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9866 - loss: 0.0417

361/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9865 - loss: 0.0418

363/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9866 - loss: 0.0417

365/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9866 - loss: 0.0416

367/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9864 - loss: 0.0420

369/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9864 - loss: 0.0420

371/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9864 - loss: 0.0420

373/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9864 - loss: 0.0418

375/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9864 - loss: 0.0418

377/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9864 - loss: 0.0419

379/606 ━━━━━━━━━━━━━━━━━━━━ 10s 44ms/step - accuracy: 0.9865 - loss: 0.0418

381/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9865 - loss: 0.0417

383/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9865 - loss: 0.0417

385/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9864 - loss: 0.0416

387/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9865 - loss: 0.0416

389/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9866 - loss: 0.0414

391/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9866 - loss: 0.0414

393/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9866 - loss: 0.0412

395/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9867 - loss: 0.0410

397/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9868 - loss: 0.0409

399/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9868 - loss: 0.0408

401/606 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - accuracy: 0.9868 - loss: 0.0406

403/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9868 - loss: 0.0406

405/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9869 - loss: 0.0404

407/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9869 - loss: 0.0403

409/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9870 - loss: 0.0401

411/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9871 - loss: 0.0400

413/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9871 - loss: 0.0399

415/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9871 - loss: 0.0398

417/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9872 - loss: 0.0396

419/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9872 - loss: 0.0396

421/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9872 - loss: 0.0395

423/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9873 - loss: 0.0393

425/606 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - accuracy: 0.9873 - loss: 0.0393

427/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9872 - loss: 0.0394

429/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9872 - loss: 0.0394

431/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9872 - loss: 0.0393

433/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9872 - loss: 0.0392

435/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9871 - loss: 0.0393

437/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9871 - loss: 0.0394

439/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9871 - loss: 0.0392

441/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9872 - loss: 0.0391

443/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9872 - loss: 0.0390

445/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9872 - loss: 0.0389

447/606 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9872 - loss: 0.0388

449/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9871 - loss: 0.0390

451/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9871 - loss: 0.0388

453/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9871 - loss: 0.0390

455/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9872 - loss: 0.0388

457/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9871 - loss: 0.0389

459/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9871 - loss: 0.0388

461/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9871 - loss: 0.0387

463/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9872 - loss: 0.0386

465/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9872 - loss: 0.0385

467/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9873 - loss: 0.0384

469/606 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - accuracy: 0.9873 - loss: 0.0383

471/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9874 - loss: 0.0381

473/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9874 - loss: 0.0380

475/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9875 - loss: 0.0379

476/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9875 - loss: 0.0379

478/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9876 - loss: 0.0377

480/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9876 - loss: 0.0377

482/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9876 - loss: 0.0376

484/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9877 - loss: 0.0374

486/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9877 - loss: 0.0373

488/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9878 - loss: 0.0372

490/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9878 - loss: 0.0370

492/606 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9878 - loss: 0.0370

494/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9878 - loss: 0.0370

496/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9878 - loss: 0.0369

498/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9878 - loss: 0.0368

500/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9879 - loss: 0.0368

502/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9879 - loss: 0.0367

504/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9879 - loss: 0.0366

506/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9880 - loss: 0.0365

508/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9879 - loss: 0.0364

510/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9879 - loss: 0.0365

512/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9879 - loss: 0.0364

514/606 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9880 - loss: 0.0363

516/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9879 - loss: 0.0363

518/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9880 - loss: 0.0362

520/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9880 - loss: 0.0362

522/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9880 - loss: 0.0361

524/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9881 - loss: 0.0360

526/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9881 - loss: 0.0360

528/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9881 - loss: 0.0359

530/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9881 - loss: 0.0358

532/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9881 - loss: 0.0359

534/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9881 - loss: 0.0358

536/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9882 - loss: 0.0358

538/606 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step - accuracy: 0.9882 - loss: 0.0357

540/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9883 - loss: 0.0355

542/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9882 - loss: 0.0358

544/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9882 - loss: 0.0359

546/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9882 - loss: 0.0358

548/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9882 - loss: 0.0358

550/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9882 - loss: 0.0358

552/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9882 - loss: 0.0356

554/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9882 - loss: 0.0356

556/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9882 - loss: 0.0356

558/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9882 - loss: 0.0355

560/606 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.9881 - loss: 0.0357

562/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9881 - loss: 0.0357

564/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9881 - loss: 0.0356

566/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9882 - loss: 0.0355

568/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9882 - loss: 0.0355

570/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9882 - loss: 0.0354

572/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9883 - loss: 0.0353

574/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9883 - loss: 0.0352

576/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9882 - loss: 0.0353

578/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9882 - loss: 0.0354

580/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9883 - loss: 0.0353

582/606 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.9883 - loss: 0.0352

584/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9883 - loss: 0.0351

586/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9883 - loss: 0.0351

588/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9884 - loss: 0.0350

590/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9883 - loss: 0.0351

592/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9883 - loss: 0.0350

594/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9884 - loss: 0.0350

596/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9883 - loss: 0.0350

598/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9883 - loss: 0.0349

600/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9884 - loss: 0.0348

602/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9884 - loss: 0.0347

604/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9884 - loss: 0.0348

606/606 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9884 - loss: 0.0348

606/606 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.9884 - loss: 0.0348 - val_accuracy: 0.9364 - val_loss: 0.3411

Fim do treino: 13:34:50
Tempo total de treino: 847.0s (14.1 min)

In [17]:
# ─── 2.3f  Classificador maioritário ───────────────────────────────────

# Contar labels no val
val_label_counts = val_s['label'].value_counts()
majority_class = val_label_counts.idxmax()
majority_acc = val_label_counts.max() / len(val_s)

# Acurácia de validação final do modelo
final_val_acc = history.history['val_accuracy'][-1]

print(f'=== Classificador Maioritário ===')
print(f'Classe maioritária no val: {majority_class} ({val_label_counts.max()}/{len(val_s)})')
print(f'Acurácia do classificador maioritário: {majority_acc:.4f} ({majority_acc*100:.2f}%)')
print(f'\nAcurácia de validação final (época 30): {final_val_acc:.4f} ({final_val_acc*100:.2f}%)')
print(f'Diferença: {(final_val_acc - majority_acc)*100:+.2f} pp')

if final_val_acc > majority_acc:
    print('\n✅ O modelo supera o classificador maioritário.')
else:
    print('\n⚠️ O modelo NÃO supera o classificador maioritário!')

=== Classificador Maioritário ===
Classe maioritária no val: Parasitized (2055/4107)
Acurácia do classificador maioritário: 0.5004 (50.04%)

Acurácia de validação final (época 30): 0.9364 (93.64%)
Diferença: +43.61 pp

✅ O modelo supera o classificador maioritário.

---
## 2.4 — Curvas e Diagnóstico

In [18]:
# ─── 2.4a  Guardar history em CSV ──────────────────────────────────────
hist_df = pd.DataFrame(history.history)
hist_df.index += 1  # épocas 1-indexed
hist_df.index.name = 'epoch'
hist_df.to_csv(AULA2 / 'history_baseline.csv')
print(f'History guardado em aula2/history_baseline.csv ({len(hist_df)} épocas)')
hist_df.head()

History guardado em aula2/history_baseline.csv (30 épocas)

       accuracy      loss  val_accuracy  val_loss
epoch
1      0.846594  0.417272      0.940833  0.284739
2      0.917183  0.320591      0.943268  0.404837
3      0.939525  0.191080      0.953737  0.175435
4      0.945304  0.166640      0.943755  0.228984
5      0.947988  0.162414      0.952277  0.190497

In [19]:
# ─── 2.4b  Plot de loss e accuracy ─────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

epochs_range = range(1, EPOCHS + 1)

# Loss
ax1.plot(epochs_range, hist_df['loss'], 'b-o', markersize=3, label='Treino')
ax1.plot(epochs_range, hist_df['val_loss'], 'r-o', markersize=3, label='Validação')
ax1.set_xlabel('Época')
ax1.set_ylabel('Loss')
ax1.set_title('Loss por Época')
ax1.legend()
ax1.grid(True, alpha=0.3)

# Accuracy
ax2.plot(epochs_range, hist_df['accuracy'], 'b-o', markersize=3, label='Treino')
ax2.plot(epochs_range, hist_df['val_accuracy'], 'r-o', markersize=3, label='Validação')
ax2.set_xlabel('Época')
ax2.set_ylabel('Accuracy')
ax2.set_title('Accuracy por Época')
ax2.legend()
ax2.grid(True, alpha=0.3)

plt.suptitle('Baseline CNN — Curvas de Aprendizagem', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig(AULA2 / 'curvas_baseline.png', dpi=150, bbox_inches='tight')
plt.show()
print('Gráfico guardado em aula2/curvas_baseline.png')

Gráfico guardado em aula2/curvas_baseline.png

C:\Users\vilar\AppData\Local\Temp\ipykernel_26088\2295760125.py:27: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [20]:
# ─── 2.4c  Tabela de diagnóstico ───────────────────────────────────────

# Melhor época (menor val_loss)
best_epoch = int(hist_df['val_loss'].idxmin())
best_val_loss = hist_df.loc[best_epoch, 'val_loss']
best_train_acc = hist_df.loc[best_epoch, 'accuracy']
best_val_acc = hist_df.loc[best_epoch, 'val_accuracy']
best_train_loss = hist_df.loc[best_epoch, 'loss']

# Diagnóstico baseado nos números
gap_acc = best_train_acc - best_val_acc
gap_loss = best_val_loss - best_train_loss

if best_val_acc < majority_acc + 0.05:
    diagnostico = 'Underfitting'
    justificacao = (f'A acurácia de validação ({best_val_acc:.4f}) está próxima '
                    f'do classificador maioritário ({majority_acc:.4f}), '
                    f'indicando que o modelo não consegue aprender padrões úteis.')
elif gap_acc > 0.10:
    diagnostico = 'Overfitting'
    justificacao = (f'Gap treino-val de {gap_acc:.4f} em accuracy e {gap_loss:.4f} em loss. '
                    f'O modelo memoriza o treino (acc={best_train_acc:.4f}) '
                    f'mas generaliza mal (val_acc={best_val_acc:.4f}).')
elif gap_acc > 0.05:
    diagnostico = 'Overfitting ligeiro'
    justificacao = (f'Gap treino-val de {gap_acc:.4f} em accuracy. '
                    f'Acc treino={best_train_acc:.4f}, val={best_val_acc:.4f}. '
                    f'Há sinais de sobreajuste mas o modelo ainda generaliza razoavelmente.')
else:
    diagnostico = 'Adequado'
    justificacao = (f'Gap treino-val pequeno ({gap_acc:.4f} em accuracy). '
                    f'Acc treino={best_train_acc:.4f}, val={best_val_acc:.4f}. '
                    f'O modelo generaliza bem.')

print('=== Tabela 2.4 — Diagnóstico ===')
print(f'Época com menor val_loss:     {best_epoch}')
print(f'Val loss (nessa época):       {best_val_loss:.4f}')
print(f'Acc treino (nessa época):     {best_train_acc:.4f} ({best_train_acc*100:.2f}%)')
print(f'Acc val (nessa época):        {best_val_acc:.4f} ({best_val_acc*100:.2f}%)')
print(f'Classificador maioritário:    {majority_acc:.4f} ({majority_acc*100:.2f}%)')
print(f'Diagnóstico:                  {diagnostico}')
print(f'Justificação:                 {justificacao}')

# Última época para comparação
print(f'\n--- Última época (30) ---')
print(f'Acc treino: {hist_df.loc[30, "accuracy"]:.4f}')
print(f'Acc val:    {hist_df.loc[30, "val_accuracy"]:.4f}')
print(f'Loss treino: {hist_df.loc[30, "loss"]:.4f}')
print(f'Loss val:    {hist_df.loc[30, "val_loss"]:.4f}')

=== Tabela 2.4 — Diagnóstico ===
Época com menor val_loss:     7
Val loss (nessa época):       0.1387
Acc treino (nessa época):     0.9491 (94.91%)
Acc val (nessa época):        0.9627 (96.27%)
Classificador maioritário:    0.5004 (50.04%)
Diagnóstico:                  Adequado
Justificação:                 Gap treino-val pequeno (-0.0136 em accuracy). Acc treino=0.9491, val=0.9627. O modelo generaliza bem.

--- Última época (30) ---
Acc treino: 0.9884
Acc val:    0.9364
Loss treino: 0.0348
Loss val:    0.3411

In [21]:
# ─── 2.4d  Gerar RESULTADOS.md ────────────────────────────────────────

resultados_md = f"""# Aula Prática 2 — Resultados

## 2.1 — Caracterização do Dataset

| Classe | N.º imagens | % | Dimensão típica | Observações |
|--------|-------------|---|-----------------|-------------|
"""

for _, row in summary_table.iterrows():
    resultados_md += f"| {row['Classe']} | {row['N.º imagens']} | {row['%']} | {row['Dimensão típica']} | {row['Observações']} |\n"

resultados_md += f"""
**Total:** {len(df)} imagens  
**Grupos únicos:** {df['grupo'].nunique()}  
**Imagens corrompidas:** {len(corrupted_paths)}  
**Duplicados (md5):** {n_dup_total} imagens em {n_dup_groups} grupos

## 2.2 — Divisão sem fugas

**Método:** Reutilização dos splits do D1 (GroupShuffleSplit, seed 42).  
**Justificação:** Garante consistência com o trabalho anterior e respeita a integridade de grupos.

| Verificação | Resultado |
|------------|----------|
| Interseção MD5 train∩val | {len(inter_tv)} |
| Interseção MD5 train∩test | {len(inter_tt)} |
| Interseção MD5 val∩test | {len(inter_vt)} |
| Interseção grupo train∩val | {len(inter_g_tv)} |
| Interseção grupo train∩test | {len(inter_g_tt)} |
| Interseção grupo val∩test | {len(inter_g_vt)} |

| Split | N | Parasitized % | Uninfected % |
|-------|---|--------------|-------------|
"""

for split_name in ['train', 'val', 'test']:
    sub = splits_final[splits_final['split'] == split_name]
    pct = sub['label'].value_counts(normalize=True) * 100
    p_pct = pct.get('Parasitized', 0)
    u_pct = pct.get('Uninfected', 0)
    resultados_md += f"| {split_name} | {len(sub)} | {p_pct:.1f}% | {u_pct:.1f}% |\n"

resultados_md += f"""
## 2.3 — Baseline CNN

**Arquitetura:** Input(180,180,3) → Rescaling(1/255) → 4×[Conv2D(f,3,relu)+MaxPool(2)] com f∈[32,64,128,256] → GAP → Dense({num_classes}, softmax)  
**Optimizer:** Adam  
**Loss:** sparse_categorical_crossentropy  
**Épocas:** {EPOCHS} (sem EarlyStopping)  
**Tempo de treino:** {train_time:.1f}s ({train_time/60:.1f} min)

Verificação de parâmetros:
- Conv2D #1: (3×3×3+1)×32 = {conv1_params} ({'✅' if conv1_params == layer_configs[0][1] else '❌'})
- Conv2D #2: (3×3×32+1)×64 = {conv2_params} ({'✅' if conv2_params == layer_configs[1][1] else '❌'})

## 2.4 — Diagnóstico

| Métrica | Valor |
|---------|-------|
| Época com menor val_loss | {best_epoch} |
| Acc treino (nessa época) | {best_train_acc:.4f} ({best_train_acc*100:.2f}%) |
| Acc val (nessa época) | {best_val_acc:.4f} ({best_val_acc*100:.2f}%) |
| Classificador maioritário | {majority_acc:.4f} ({majority_acc*100:.2f}%) |
| Diagnóstico | {diagnostico} |

**Justificação:** {justificacao}

## Notas / O que correu mal

"""

# Notas baseadas na execução
notas = []
if len(corrupted_paths) > 0:
    notas.append(f'- Encontradas {len(corrupted_paths)} imagem(ns) corrompida(s)')
if n_dup_total > 0:
    notas.append(f'- Encontrados {n_dup_total} ficheiros com hash MD5 duplicado ({n_dup_groups} grupos)')
if len(inter_tv) + len(inter_tt) + len(inter_vt) > 0:
    notas.append('- ⚠️ Existem hashes duplicados entre splits (possível fuga de dados)')
if len(inter_g_tv) + len(inter_g_tt) + len(inter_g_vt) > 0:
    notas.append('- ⚠️ Existem grupos partilhados entre splits (fuga de grupo)')
if n_missing > 0:
    notas.append(f'- {n_missing} imagens nos splits D1 não encontradas no scan (possível limpeza/remoção)')
if not notas:
    notas.append('- Nenhum problema encontrado')

resultados_md += '\n'.join(notas) + '\n'

with open(AULA2 / 'RESULTADOS.md', 'w', encoding='utf-8') as f:
    f.write(resultados_md)

print('RESULTADOS.md criado em aula2/')
print(resultados_md)

RESULTADOS.md criado em aula2/
# Aula Prática 2 — Resultados

## 2.1 — Caracterização do Dataset

| Classe | N.º imagens | % | Dimensão típica | Observações |
|--------|-------------|---|-----------------|-------------|
| Parasitized | 13779 | 50.0% | 133×133 | dimensões variáveis (range 348×345) |
| Uninfected | 13779 | 50.0% | 130×130 | dimensões variáveis (range 198×186) |

**Total:** 27558 imagens
**Grupos únicos:** 200
**Imagens corrompidas:** 0
**Duplicados (md5):** 0 imagens em 0 grupos

## 2.2 — Divisão sem fugas

**Método:** Reutilização dos splits do D1 (GroupShuffleSplit, seed 42).
**Justificação:** Garante consistência com o trabalho anterior e respeita a integridade de grupos.

| Verificação | Resultado |
|------------|----------|
| Interseção MD5 train∩val | 0 |
| Interseção MD5 train∩test | 0 |
| Interseção MD5 val∩test | 0 |
| Interseção grupo train∩val | 0 |
| Interseção grupo train∩test | 0 |
| Interseção grupo val∩test | 0 |

| Split | N | Parasitized % | Uninfected % |
|-------|---|--------------|-------------|
| train | 19380 | 50.1% | 49.9% |
| val | 4107 | 50.0% | 50.0% |
| test | 4071 | 49.4% | 50.6% |

## 2.3 — Baseline CNN

**Arquitetura:** Input(180,180,3) → Rescaling(1/255) → 4×[Conv2D(f,3,relu)+MaxPool(2)] com f∈[32,64,128,256] → GAP → Dense(2, softmax)
**Optimizer:** Adam
**Loss:** sparse_categorical_crossentropy
**Épocas:** 30 (sem EarlyStopping)
**Tempo de treino:** 847.0s (14.1 min)

Verificação de parâmetros:
- Conv2D #1: (3×3×3+1)×32 = 896 (✅)
- Conv2D #2: (3×3×32+1)×64 = 18496 (✅)

## 2.4 — Diagnóstico

| Métrica | Valor |
|---------|-------|
| Época com menor val_loss | 7 |
| Acc treino (nessa época) | 0.9491 (94.91%) |
| Acc val (nessa época) | 0.9627 (96.27%) |
| Classificador maioritário | 0.5004 (50.04%) |
| Diagnóstico | Adequado |

**Justificação:** Gap treino-val pequeno (-0.0136 em accuracy). Acc treino=0.9491, val=0.9627. O modelo generaliza bem.

## Notas / O que correu mal

- Nenhum problema encontrado

In [22]:
# ─── Atualizar AI_LOG.md ──────────────────────────────────────────────
import datetime

ai_log_path = ROOT / 'AI_LOG.md'
today = datetime.date.today().strftime('%Y-%m-%d')

new_entry = (
    f'| {today} | Antigravity (Claude Opus 4.6) | '
    f'Aula Prática 2 completa — caracterização do dataset (2.1), '
    f'divisão sem fugas por grupo e md5 (2.2), '
    f'baseline CNN 4×Conv+GAP 30 épocas (2.3), '
    f'curvas de aprendizagem e diagnóstico (2.4) | '
    f'Aceite: notebook aula2/aula2_P1.ipynb com todas as secções, '
    f'reutilização dos splits do D1 por consistência, '
    f'arquitetura exata do enunciado, '
    f'RESULTADOS.md com tabelas preenchidas. '
    f'Tempo de treino: {train_time:.0f}s, '
    f'melhor época: {best_epoch}, '
    f'acc val: {best_val_acc:.4f}. | |\n'
)

with open(ai_log_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Adicionar no fim
content = content.rstrip() + '\n' + new_entry

with open(ai_log_path, 'w', encoding='utf-8') as f:
    f.write(content)

print(f'AI_LOG.md atualizado com entrada de {today}')
print('Campo de verificação deixado em branco para preenchimento manual.')

AI_LOG.md atualizado com entrada de 2026-10-03
Campo de verificação deixado em branco para preenchimento manual.

In [23]:
# ─── Resumo final ─────────────────────────────────────────────────────
print('=' * 60)
print('RESUMO FINAL — Aula Prática 2')
print('=' * 60)
print(f'Tempo de treino:            {train_time:.1f}s ({train_time/60:.1f} min)')
print(f'Melhor época (min val_loss): {best_epoch}')
print(f'Acc treino (melhor época):  {best_train_acc:.4f} ({best_train_acc*100:.2f}%)')
print(f'Acc val (melhor época):     {best_val_acc:.4f} ({best_val_acc*100:.2f}%)')
print(f'Classificador maioritário:  {majority_acc:.4f} ({majority_acc*100:.2f}%)')
print(f'Diagnóstico:                {diagnostico}')
print(f'\nFicheiros gerados:')
print(f'  aula2/aula2_P1.ipynb      (este notebook)')
print(f'  aula2/splits.csv           ({len(splits_final)} linhas)')
print(f'  aula2/history_baseline.csv ({EPOCHS} épocas)')
print(f'  aula2/curvas_baseline.png')
print(f'  aula2/RESULTADOS.md')
print(f'  AI_LOG.md (atualizado)')
print(f'  .gitignore (aula2/split/ adicionado)')
print(f'\nAssunções:')
print(f'  - Reutilizados os splits do D1 (GroupShuffleSplit, seed 42)')
print(f'  - Dataset em data/raw/cell_images/ (2 classes)')
print(f'  - Backend Keras 3 + PyTorch')
print(f'  - Conjunto de teste NÃO avaliado')
print('=' * 60)

============================================================
RESUMO FINAL — Aula Prática 2
============================================================
Tempo de treino:            847.0s (14.1 min)
Melhor época (min val_loss): 7
Acc treino (melhor época):  0.9491 (94.91%)
Acc val (melhor época):     0.9627 (96.27%)
Classificador maioritário:  0.5004 (50.04%)
Diagnóstico:                Adequado

Ficheiros gerados:
  aula2/aula2_P1.ipynb      (este notebook)
  aula2/splits.csv           (27558 linhas)
  aula2/history_baseline.csv (30 épocas)
  aula2/curvas_baseline.png
  aula2/RESULTADOS.md
  AI_LOG.md (atualizado)
  .gitignore (aula2/split/ adicionado)

Assunções:
  - Reutilizados os splits do D1 (GroupShuffleSplit, seed 42)
  - Dataset em data/raw/cell_images/ (2 classes)
  - Backend Keras 3 + PyTorch
  - Conjunto de teste NÃO avaliado
============================================================